### ISSUE TITLE
请问TCA降维后的数据通常怎么使用

### ISSUE THREAD

**Issue by zzeric** [jindongwang/transferlearning#1]
看cta_python的测试代码, 源数据是162维, x_src取前81维作为源域数据, y_src取后81维, 然后fit_transform, 返回x_src_tca和x_tar_tca两份降到30维后的数据, 请问之后模型是只对x_src_tca数据进行训练, 而用x_tar_tca来验证, 还是说两个降维数据都是要用来做训练的?

**Comment by jindongwang** [comment]
降维完成之后，原来的x_src和x_tar变成新的x_src_new和x_tar_new。之后，用x_src_new训练模型，就可以预测x_tar_new了。
