### ISSUE TITLE
ADDA Code

### ISSUE THREAD

**Issue by RayWangWR** [jindongwang/transferlearning#100]
Hi Jindong,

Thank you very much for your collection. In the Office31 section for /data/benchmark.md, do you know where the results of ADDA come from? I would really appreciate it if you can show me the code or the paper.

Thanks,
Rui

**Comment by jindongwang** [comment]
Long M, Cao Z, Wang J, et al. Conditional adversarial domain adaptation[C]//Advances in Neural Information Processing Systems. 2018: 1640-1650.
