### ISSUE TITLE
终生迁移学习

### ISSUE THREAD

**Issue by yyssmm** [jindongwang/transferlearning#101]
您好，
请问现在有没有关于终生迁移学习的文献啊？（Learning to Transfer，这篇除外，已经看过了）
谢谢！

**Comment by jindongwang** [comment]
Meta learning is life-long learning.

**Comment by yyssmm** [comment]
@jindongwang  Thank you very much! I am recently interested in domain adaptation, but i have been confused by what is the  domain , is there a clear definition？Thanks

**Comment by jindongwang** [comment]
A domain can be regarded as a set of data and its probability distributions from which it is generated. Formally, $D=\{X, P(X)\}$. You can refer to Pan and Yang's survey on transfer learning to see more formal definitions.
