### ISSUE TITLE
RevGrad

### ISSUE THREAD

**Issue by SonaPi** [jindongwang/transferlearning#102]
![1](https://user-images.githubusercontent.com/54723734/64423131-fe45ea00-d0ba-11e9-813c-45f1fc443d4f.png)
**Describe the bug**

I tried to run the older version of RevGrad on Colab but I got this error. I know it may be due to the version of Pytorch, but I already installed Pytorch 0.3.1. 
I commented the lines of 48 to 50 and code is executed. Is it wrong to comment these lines? Does it affect the results?

![1](https://user-images.githubusercontent.com/54723734/64423287-65639e80-d0bb-11e9-9c2c-2ebaf9862e40.png)

**Comment by jindongwang** [comment]
The older RevGrad is removed. These three lines will not change the final results.

**Comment by SonaPi** [comment]
Thank you very much for the reply. The older version is quite suitable for my project. Thank you very much.
