### ISSUE TITLE
数据集的深度特征

### ISSUE THREAD

**Issue by binhuixie** [jindongwang/transferlearning#107]
Office31、Office-Home和VisDA数据集从ResNet50中取出来的深度特征，样本的顺序是乱序的，有没有按照DeCAF和SURF那样顺序提取的特征呢？

**Comment by jindongwang** [comment]
提特征的时候没有考虑样本顺序，所以现在没法和原始的图像一一对应起来。当然，你可以修改我提特征的代码，强迫它们一一对应

**Comment by binhuixie** [comment]
可以方便给出体特征的代码吗？或者您在txt里提到的已经预训练好的model？

**Comment by binhuixie** [comment]
可以方便给出提特征的代码吗？或者您在txt中提到的已经预训练好的model？

**Comment by jindongwang** [comment]
https://github.com/jindongwang/transferlearning/tree/master/code/feature_extractor

**Comment by binhuixie** [comment]
您好，抱歉，再次打扰。 
code/feature_extractor文件下给出的"Finetuned ResNet-50 models For Office-31 dataset"的云盘链接(https://pan.baidu.com/s/1mRVDYOpeLz3siIId3tni6Q)里面应该包含best_resnet_webcam.pth 这个模型，链接里面放的是best_mnist_usps.pth

**Comment by binhuixie** [comment]
您好，抱歉，再次打扰。
code/feature_extractor文件下给出的"Finetuned ResNet-50 models For Office-31 dataset"的云盘链接 https://pan.baidu.com/s/1mRVDYOpeLz3siIId3tni6Q 里面应该包含best_resnet_webcam.pth 这个模型，链接里面放的是best_mnist_usps.pth

**Comment by jindongwang** [comment]
感谢指正！当时文件太多，可能放的时候放乱了。。。

**Comment by binhuixie** [comment]
您好，方便更新一下正确的model吗？

**Comment by jindongwang** [comment]
正确的model应该是没有了，我已经毕业，东西在原来服务器上都被清空了。你可以用提供的代码再训练一下。

**Comment by yangguangan** [comment]
您好，我想问一下，一般说SURF描述子的特征时64维，这个数据集提取的SURF特征为什么会是800维呢。想了解一下具体细节。

**Comment by jindongwang** [comment]
@yangguangan SURF特征是图像经典特征提取，你可以网上搜索得到相关的知识。相关的特征还有：SIFT、HOG。

**Comment by yangguangan** [comment]
> 



> 

感谢回复，我找过很多，自己也进行过提取，获得的特征描述子是一个 size为（m,64) 的特征矩阵，接下来的做法是什么呢？是不是把这个矩阵进行平铺展开吗？可如果是展开的话，怎么会得到800呢？就这一步，查过很多地方没有查到。

**Comment by jindongwang** [comment]
这个我就不懂了，我也不是专业做视觉的。。。

**Comment by yangguangan** [comment]
![image](https://user-images.githubusercontent.com/48777962/142807017-73a73340-1d67-41b9-b361-53303e24661f.png)
感谢回复，我刚回去看了原文，原来是作者在提取64维的描述子后，还利用K-means进行了一个800维的code book。难怪一开始怎么也想不到。怎么变成800的。谢谢您。

**Comment by yangguangan** [comment]
> 这个我就不懂了，我也不是专业做视觉的。。。

好的，感谢您的解答。谢谢
