### ISSUE TITLE
Issue on the MRAN

### ISSUE THREAD

**Issue by 459548764** [jindongwang/transferlearning#109]

**Comment by 459548764** [comment]
When I ran the MRAN.py i got the error at the line 69
model_dict[k] = pretrained_dict[k[k.find(".") + 1:]]
KeyError: 'bn1.num_batches_tracked'

**Comment by easezyc** [comment]
pytorch1.0
https://github.com/easezyc/deep-transfer-learning/tree/master/UDA/pytorch1.0/MRAN
