### ISSUE TITLE
怎样入门迁移学习？

### ISSUE THREAD

**Issue by ailipanpan** [jindongwang/transferlearning#11]
你好，我是刚刚入学研一的新生，老师指定的方向是迁移学习。看大哥在雷锋网，知乎上面发布很多迁移学习资料，大哥是厉害之人，相大哥请教一下零基础的小白怎么入门迁移学习？方便的话留下大哥的联系方式（QQ），在此谢过。

**Comment by jindongwang** [comment]
@ailipanpan 这个repo下的第一部分就是入门的，看看ppt什么的应该能学个大概
我的qq：425046241
