### ISSUE TITLE
添加建议

### ISSUE THREAD

**Issue by tytcc** [jindongwang/transferlearning#113]
希望作者可以补充一些transfer learning的会议和workshop，比如NIPS 每隔十年的workshop的等等。对新入门的新手来说可能可以减少搜索范围，只是建议，仅供参考。如有冒犯，十分抱歉。

**Comment by jindongwang** [comment]
@tytcc 感谢建议。
不过目前为止并没有一个会议是迁移学习的会议，所以无法添加。其实在AI、ML、DM、CV、NLP等众多会议上，迁移学习都已经被广泛地使用了。
另外，关于workshop的问题，我的想法是这样的：现在main conference的paper都多到看不过来了，哪里还有时间去看workshop呢？

**Comment by tytcc** [comment]
好的 感谢
