### ISSUE TITLE
Why can't the data of mat file be opened?

### ISSUE THREAD

**Issue by jizefeng0810** [jindongwang/transferlearning#114]
i download the *.mat from 'transferlearning/code/traditional/data/', but i don't read it in matlab or python.

**Comment by jindongwang** [comment]
@jizefeng0810 Can you tell me which .mat file you downloaded cannot be opened? Whick link?

**Comment by jizefeng0810** [comment]
I found that there was a problem with the file I downloaded. I can read it again after re-downloading.  Thanks Reply!




| |
纪泽锋
|
|
邮箱：jizefeng0810@163.com
|

签名由 网易邮箱大师 定制

On 10/21/2019 15:10, Jindong Wang wrote:

@jizefeng0810 Can you tell me which .mat file you downloaded cannot be opened? Whick link?
