### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by WUzhusihan** [jindongwang/transferlearning#115]
像是 MRAN 的主函数里面，也就是train部分，line94-line98这样的话，岂不是源域循环了一遍，目标域一直在第一个batch？可能是我自己没弄懂，希望能解答一下。

**Comment by WUzhusihan** [comment]
是MRAN的主函数里面里面，忘了说

**Comment by jindongwang** [comment]
@easezyc

**Comment by easezyc** [comment]
94-98行的for循环实际上每次只跑了一次就break，你的疑问应该是多次源领域循环，目标领域取的都是第一个batch，实际上dataloader是一个迭代器（iterable），只会从头取到尾，这次没循环完会接着上一次的跑，具体的你可以查看iterable的用法。另外我已经试验证明了，如图我打出每一轮取得目标领域的标签，可以看到每一次迭代都不一样。这样的代码风格确实不够好看，后续改正，感谢指出问题。
![微信图片_20191022120004](https://user-images.githubusercontent.com/20279673/67258558-dd4b2400-f4c3-11e9-8d2e-06cd28ece4dc.png)

**Comment by WUzhusihan** [comment]
@easezyc OK，已经看到你更新代码了，没错最好了。
