### ISSUE TITLE
A Problem

### ISSUE THREAD

**Issue by handsomeboy666** [jindongwang/transferlearning#117]
作者您好：
关于TCA代码的第61，62行我有一点疑问。按照原文中给出的公式，应该是计算a的逆矩阵乘上b之后再做特征分解，而你这里用的是a和b拼接之后做特征分解，请问这两种操作是等价的吗

**Comment by jindongwang** [comment]
代码没有问题，主要根据JDA的推导，因为其更高效简洁，并没有根据TCA文章进行。
