### ISSUE TITLE
DANN维度不匹配的错误

### ISSUE THREAD

**Issue by qq490516306** [jindongwang/transferlearning#118]
作者您好！我下载了DANN的代码来学习，下载了 Office+Caltech original images的数据集，在编译上，出现了output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]的错误，然后将数据处理中的transforms.Grayscale()灰度处理注释掉，结果编译出又出现错误。想问下您，这是出现了啥问题，我用的是最新版的Anaconda(python3.7)以及pytorch1.3

**Comment by jindongwang** [comment]
The requirements for this code is pytorch 0.4 (which is shown on the readme page), maybe you can try this version. If there's still problem, you can let me know.

**Comment by qq490516306** [comment]
我改用了pytorch0.4的版本，结果import torchvision都报错了

**Comment by qq490516306** [comment]
我改用了pytorch0.4的版本，结果import torchvision都报错了

**Comment by qq490516306** [comment]
我改用了pytorch0.4的版本，结果import torchvision都报错了

**Comment by jindongwang** [comment]
Did you change the version of torchvision according to your pytorch version?

**Comment by qq490516306** [comment]
您有空亲自测试一遍嘛，想知道您那边的运行情况，麻烦了！！我直接重新下载了pytorch版本，并没有再做其它的操作

**Comment by qq490516306** [comment]
我下的是DANN的那个demo,并不是DANN（RevGrad）的那个，DANN的好像是说要用pytorch0.3.0,这个是只能在linux上跑吗

**Comment by jindongwang** [comment]
现在这个repo里只有DANN(RevGrad)了，你可以重新看一下。原来的DANN我删除了，那个不太行了。

**Comment by qq490516306** [comment]
感觉DANN很好入门，想学习下MMD怎么实现以及应用的，不太行了，是指不好移植到新的pytorch版本了嘛

**Comment by jindongwang** [comment]
那个是别人写的，bug很多，我又重新写了一个，这个是没问题的。你确保你是下载的最新代码就行。在pytorch 1.0也能用。

**Comment by jindongwang** [comment]
分享什么呢？它的代码是开源的

**Comment by Supe2015** [comment]
> 对呀，我也是看代码看了好几天，各种编译上的错误，解决了一个还有一个，搞不完的，才来请教您的。我看了您一篇最新的论文，Conditional Adversarial Domain Adaptation的网络，可以分享一下嘛
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jindong Wang"<notifications@github.com&gt;; 发送时间: 2019年10月24日(星期四) 晚上9:24 收件人: "jindongwang/transferlearning"<transferlearning@noreply.github.com&gt;; 抄送: "最初的星"<490516306@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [jindongwang/transferlearning] DANN维度不匹配的错误 (#118) 那个是别人写的，bug很多，我又重新写了一个，这个是没问题的。你确保你是下载的最新代码就行。在pytorch 1.0也能用。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你可以把错误信息贴出来看看

**Comment by Supe2015** [comment]
@qq490516306 
你可以把错误信息贴出来看看

**Comment by jindongwang** [comment]
@qq490516306 你的问题解决了吗？

**Comment by qq490516306** [comment]
还没有呢，DANN（RevGrad）里的百度云数据集链接好像失效了，谷歌的又访问不了，我用了别的mnist-_m的数据集，好像也无法运行，不知道是不是数据集不对

**Comment by jindongwang** [comment]
我们下载数据集是可以正常使用的。百度把链接删了，也没什么办法。你试一下这个链接：链接: https://pan.baidu.com/s/1U2Je6WjFVkt24BGYZI6zxw 提取码: suqp 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by mochaojie** [comment]
RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]我运行的是DANN（RevGrad）的代码，还是显示这个错误。

**Comment by mochaojie** [comment]
不好意思，忘记改torchvision的版本了，现在跑通了

**Comment by mochaojie** [comment]
我还想问一下这两个数据集的区别在哪里，源域的数据集看不了

**Comment by qq490516306** [comment]
torchvision的版本怎么改，要重新下载吗，他不是pytorch自带的吗

**Comment by mochaojie** [comment]
我的pytorch是1.0，对应的torchvision是0.2，不是自带的吧，我都是分开下的。------------------ 原始邮件 ------------------
发件人: "qq490516306"<notifications@github.com>
发送时间: 2019年11月1日(星期五) 晚上10:14
收件人: "jindongwang/transferlearning"<transferlearning@noreply.github.com>;
抄送: "mochaojie"<810375129@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jindongwang/transferlearning] DANN维度不匹配的错误 (#118)



torchvision的版本怎么改，要重新下载吗，他不是pytorch自带的吗
 
&mdash;

**Comment by mochaojie** [comment]
重新下呗，不是自带的，至少在anaconda中这两个是分开的，有些下载器方式可能是把这两个打包下载了。你重新分开下试试吧



---原始邮件---
发件人: "qq490516306"<notifications@github.com&gt;
发送时间: 2019年11月1日(星期五) 晚上10:14
收件人: "jindongwang/transferlearning"<transferlearning@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"mochaojie"<810375129@qq.com&gt;;
主题: Re: [jindongwang/transferlearning] DANN维度不匹配的错误 (#118)



torchvision的版本怎么改，要重新下载吗，他不是pytorch自带的吗

**Comment by qq490516306** [comment]
我吧pytorch下载好以后，就有torchvision了，所以没管，你的torchvision是下载了pytorch以后，再更新版本的吗

**Comment by mochaojie** [comment]
准确的说，我下的pytorch中没有torchvision，我也不知道你是怎么下的。------------------ 原始邮件 ------------------
发件人: "qq490516306"<notifications@github.com>
发送时间: 2019年11月2日(星期六) 中午11:35
收件人: "jindongwang/transferlearning"<transferlearning@noreply.github.com>;
抄送: "mochaojie"<810375129@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jindongwang/transferlearning] DANN维度不匹配的错误 (#118)



我吧pytorch下载好以后，就有torchvision了，所以没管，你的torchvision是下载了pytorch以后，再更新版本的吗
 
&mdash;

**Comment by qq490516306** [comment]
官网下载pytoch是这样子的，有带0.4.1的版本啊，pip3 install torch==1.3.0+cpu torchvision==0.4.1+cpu -f https://download.pytorch.org/whl/torch_stable.html，为啥我用的这个还是跑不通，难道要改到0.2的版本吗

**Comment by qq490516306** [comment]
你的python是什么版本的，不会3.6和3.7的都不一样吧

**Comment by qq490516306** [comment]
可以了，不过跑的好慢啊，感觉要好几个小时

**Comment by mochaojie** [comment]
------------------ 原始邮件 ------------------
发件人: "qq490516306"<notifications@github.com>
发送时间: 2019年11月2日(星期六) 晚上8:37
收件人: "jindongwang/transferlearning"<transferlearning@noreply.github.com>;
抄送: "mochaojie"<810375129@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jindongwang/transferlearning] DANN维度不匹配的错误 (#118)



可以了，不过跑的好慢啊，感觉要好几个小时
 
&mdash;

**Comment by mochaojie** [comment]
你大几啊------------------ 原始邮件 ------------------
发件人: "qq490516306"<notifications@github.com>
发送时间: 2019年11月2日(星期六) 晚上8:37
收件人: "jindongwang/transferlearning"<transferlearning@noreply.github.com>;
抄送: "mochaojie"<810375129@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jindongwang/transferlearning] DANN维度不匹配的错误 (#118)



可以了，不过跑的好慢啊，感觉要好几个小时
 
&mdash;

**Comment by ydu0116** [comment]
您好！想问一下是现在这个版本的DaNN.py (Feb. 20, 2019) 不能再运行了吗？ 我也遇到了相同的报错。谢谢！
