### ISSUE TITLE
how do you make .mat file about data?

### ISSUE THREAD

**Issue by jizefeng0810** [jindongwang/transferlearning#119]
your repository have some .mat file in  'transferlearning/code/traditional/data/'.
Could you provide us with the code to create .mat?
I don't know what meannings about .mat file and i want to use my data set.

**Comment by jindongwang** [comment]
Most of the .mat files are with readme file, which clearly explains what they are. If you want to use your own datasets, that's even simpler: all you need to to is download one of my demo code and dataset and try to run them, then you can replace it with your own datasets according to the code.

**Comment by jizefeng0810** [comment]
I can't find that your demo code about datasets to create .mat file. Could you give me the link? I try to find it but i'm fail.

**Comment by jindongwang** [comment]
https://github.com/jindongwang/transferlearning/tree/master/code/traditional/BDA

**Comment by jizefeng0810** [comment]
I only saw the download .mat file, but did not see the generated .mat file. What I am looking for is the code that the dataset generates .mat file.




| |
纪泽锋
|
|
邮箱：jizefeng0810@163.com
|

签名由 网易邮箱大师 定制

On 10/24/2019 20:49, Jindong Wang wrote:

https://github.com/jindongwang/transferlearning/tree/master/code/traditional/BDA

**Comment by jindongwang** [comment]
Hello, the .mat file is just matlab generated data file. You can generate your own dataset using matlab...

**Comment by jizefeng0810** [comment]
Okay, thanks for your answer.




| |
纪泽锋
|
|
邮箱：jizefeng0810@163.com
|

签名由 网易邮箱大师 定制

On 10/24/2019 20:57, Jindong Wang wrote:

Hello, the .mat file is just matlab generated data file. You can generate your own dataset using matlab...
