### ISSUE TITLE
如何计算A-distance

### ISSUE THREAD

**Issue by taylover-pei** [jindongwang/transferlearning#120]
您好，我想咨询一下关于proxy A-distance的问题，有没有什么更详细的解释？

并且，有无其他计算proxy A-distance的方法，我看您代码中的是使用svm进行计算的。

十分感谢！

**Comment by jindongwang** [comment]
你指的更详细的解释是什么呢？A-distance的理论和计算方法已经在相关的paper（Analysis of representations for domain adaptation）中介绍过了。其就是用一个简单的线性分类器来计算分类误差。SVM是一种通用的线性分类器。你当然也可以用一个对抗网络来进行计算。
