### ISSUE TITLE
transferlearning/code/traditional/GFK/GFK.m代码问题

### ISSUE THREAD

**Issue by mmgongnpu** [jindongwang/transferlearning#121]
请教一个问题，在transferlearning/code/traditional/GFK/GFK.m代码中第57~60行，如下
    B1 = 0.5.*diag(1+sin(2*theta)./2./max(theta,eps));
    B2 = 0.5.*diag((-1+cos(2*theta))./2./max(theta,eps));
    B3 = B2;
    B4 = 0.5.*diag(1-sin(2*theta)./2./max(theta,eps));
公式中为什么会有系数0.5？我对照了文章《Geodesic Flow Kernel for Unsupervised Domain Adaptation》中公式(6)，并没有这个系数。盼回复，谢谢！

**Comment by jindongwang** [comment]
这个0.5是作者自己的实现方式，我们没有改。你不妨试一下去掉了会不会对结果有影响？

**Comment by mmgongnpu** [comment]
> 这个0.5是作者自己的实现方式，我们没有改。你不妨试一下去掉了会不会对结果有影响？

好的，非常感谢您的答疑。
还有个问题请教下您，在transferlearning/code/traditional/GFK/GFK.py中第58行，为求解广义奇异值分解（gsvd），调用了bob.math.gsvd函数。我在安装bob.math库的时候，发现其依赖的python库跟tensorflow/keras依赖库版本不兼容，因此只有单独创建虚拟环境进行安装调用。这就造成了一个问题，如果想在tensorflow/keras中调用GFK算法就没法实现了。而我google之后发现，除了bob外，并未有能够求解gsvd的python库/函数，请问您那边了解到一些可以解决gsvd的python库/函数吗？谢谢！

**Comment by jindongwang** [comment]
我当时也找了很久没找到，所以才依赖了bob库。你可以创建一个虚拟环境(virtualenv)，并不影响你当前的东西。

**Comment by mmgongnpu** [comment]
> 我当时也找了很久没找到，所以才依赖了bob库。你可以创建一个虚拟环境(virtualenv)，并不影响你当前的东西。

好的，非常感谢！

**Comment by Prince-Lee-PathAI** [comment]
> > 这个0.5是作者自己的实现方式，我们没有改。你不妨试一下去掉了会不会对结果有影响？
> 
> 好的，非常感谢您的答疑。 还有个问题请教下您，在transferlearning/code/traditional/GFK/GFK.py中第58行，为求解广义奇异值分解（gsvd），调用了bob.math.gsvd函数。我在安装bob.math库的时候，发现其依赖的python库跟tensorflow/keras依赖库版本不兼容，因此只有单独创建虚拟环境进行安装调用。这就造成了一个问题，如果想在tensorflow/keras中调用GFK算法就没法实现了。而我google之后发现，除了bob外，并未有能够求解gsvd的python库/函数，请问您那边了解到一些可以解决gsvd的python库/函数吗？谢谢！

在GFK里面，我观察了一下Ps总是列正交选出来的，所以gsvd可以退化成求商奇异值分解，可以简单用torch/tf等手搓一下，我实现了一下精度还可以
