### ISSUE TITLE
想请教一下GFK的使用

### ISSUE THREAD

**Issue by Pandoraboxs** [jindongwang/transferlearning#122]
请问一下老师，GFK的python程序在运行时需要先安装的bob.learn和bob.math是怎么安装的呢？那个链接点开显示page not found

**Comment by jindongwang** [comment]
可能官方更新了链接。你试一下这个最新的：https://www.idiap.ch/software/bob/docs/bob/docs/stable/bob/bob/doc/install.html

**Comment by Mrzhangxiaohua** [comment]
> 请问一下老师，GFK的python程序在运行时需要先安装的bob.learn和bob.math是怎么安装的呢？那个链接点开显示page not found

您好，这个看官方安装教程即可，另外我们可以交流，q724183028,我对这儿也有问题，可以沟通

**Comment by jindongwang** [comment]
bob的安装可以看这里：https://www.codetd.com/article/2576834

**Comment by Mrzhangxiaohua** [comment]
> bob的安装可以看这里：https://www.codetd.com/article/2576834

对了，提醒一下，bob目前为止是没有Windows版本的，只又linux，当时我捣鼓了一下午，才发现是没有win的，避免踩坑

**Comment by jindongwang** [comment]
其实目前来说python代码中我并没有找到可以完美替代matlab中的PCA和bob中的gsvd函数的代码，所以只能在python代码中使用bob。bob确实不好安装。所以建议大家有条件的话还是用matlab版本的。
当然，如果有同学能找到python中完美替代matlab的PCA和bob中的gsvd函数，请贡献出来。

**Comment by Mrzhangxiaohua** [comment]
> 其实目前来说python代码中我并没有找到可以完美替代matlab中的PCA和bob中的gsvd函数的代码，所以只能在python代码中使用bob。bob确实不好安装。所以建议大家有条件的话还是用matlab版本的。
> 当然，如果有同学能找到python中完美替代matlab的PCA和bob中的gsvd函数，请贡献出来。

我昨天尝试了一下，有两点不懂，
1. 这个GFk输入是Xs和Xt，输出应该是变换后的公共子空间的新Xs和Xt，这个输出的维度在哪修改
2.输入的两个域维度不同是否可以直接变换

**Comment by jindongwang** [comment]
@Mrzhangxiaohua 请仔细看代码，里面有相应的参数。维度不同是不能用GFK的，请注意使用条件。
