### ISSUE TITLE
transferlearning/code/deep/DAAN/ train.py line 68 no bottle_neck parameters in optimizer

### ISSUE THREAD

**Issue by wjs97ml** [jindongwang/transferlearning#123]
bakbone network has a bottle_neck layer for Resnet 50, but DAAN train.py 68 line no bottle_neck parameters in optimizer, is there something wrong?

**Comment by jindongwang** [comment]
你可以看一下optimizer的使用，我们只是显式指定了其他层参数，没指定的都是按照lr=xxx来进行默认的，并没有遗漏。

**Comment by Supe2015** [comment]
@wjs97ml 
You are right, we should also set the lr for the bottlenect module. Our original code is right and this is a mistake when we rewrite our code according to MDD(https://github.com/thuml/MDD). We have fixed it, thanks.

**Comment by wjs97ml** [comment]
> 你可以看一下optimizer的使用，我们只是显式指定了其他层参数，没指定的都是按照lr=xxx来进行默认的，并没有遗漏。
抱歉，我的表述可能误导了你，我说的bottleneck层指DAANNet中的self.bottleneck = nn.Linear(2048, 256).

**Comment by wjs97ml** [comment]
> @wjs97ml
> You are right, we should also set the lr for the bottlenect module. Our original code is right and this is a mistake when we rewrite our code according to MDD(https://github.com/thuml/MDD). We have fixed it, thanks.

谢谢你们的开源代码。
我最近仔细对照你们发表的论文，查看代码，optimizer中优化的参数不应该也包含那些判别器网络的权重吗？类似这个代码库中的DANN算法，领域判别器网络权重是在训练中更新的，你这个代码优化器中没有包含判别器的权重，是不需要更新判别器权重吗？

**Comment by wjs97ml** [comment]
> 你可以看一下optimizer的使用，我们只是显式指定了其他层参数，没指定的都是按照lr=xxx来进行默认的，并没有遗漏。

抱歉，我的表述可能误导了你，我说的bottleneck层指DAANNet中的self.bottleneck = nn.Linear(2048, 256).

**Comment by Supe2015** [comment]
@wjs97ml 
谢谢提醒，是的，判别器确实需要在optimizer里赋予学习率，是可学习的，当时重写时疏忽了，我这边改完会更新一下。
