### ISSUE TITLE
有个关于TCA理论推导过程疑问，想请教一下作者（或许是个漏洞）

### ISSUE THREAD

**Issue by pfb2008999** [jindongwang/transferlearning#125]
最后一步，类似于核Fisher判别分析，可得W的解：（KLK+uI）`‘KHK  是m个特征向量，其中m≤n1+n2−1。  
一个疑问是：核Fisher判别分析中的优化函数用的W的装置，这里用的却是W的逆(-1)，为啥？证明过程如何继续？谢谢啦

**Comment by jindongwang** [comment]
请指明疑问出处、相关的文章或者代码片段

**Comment by pfb2008999** [comment]
作者好，是在《迁移学习简明手册》V1.1第25页第四段：（KLK+uI）`‘KHK   （TCA算法文献是：Pan, Sinno Jialin, et al. "Domain adaptation via transfer component analysis." IEEE Transactions on Neural Networks 22.2 (2010): 199-210.）
疑问是：核Fisher判别分析中的优化函数用的W的转置形式（W.T*R*W）可得最优解W为m个主导特征值的特征向量；而我推导下这里的TCA算法实际用的是W的逆（W.I*R*W）形式，那还能用核Fisher判别求解吗？谢谢啦

**Comment by jindongwang** [comment]
TCA可以直接用拉格朗日法求解，也可以用LDA那种形式。原作者用的是第一种，我比较倾向于第二种。

**Comment by pfb2008999** [comment]
作者好，第二种求解有相关文献吗？

**Comment by jindongwang** [comment]
Joint geometrical and statistical alignment for visual domain adaptation, cvpr-17
