### ISSUE TITLE
DANN

### ISSUE THREAD

**Issue by redhat12345** [jindongwang/transferlearning#127]
Hi,

I am getting the error. 

Traceback (most recent call last):
  File "train.py", line 190, in <module>
    train(epoch, model, train_loader, unsuptrain_loader)
  File "train.py", line 81, in train
    {'params': model.dcis.parameters()},
  File "/home/mohammad/pytorch_0.4_python3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'DAANNet' object has no attribute 'dcis'

**Comment by jindongwang** [comment]
Hello, according to your error log, you have pytorch 0.4, while DAAN supports pytorch 1.0 (which is indicated in its readme file). You may want to change the version to see if there are still errors.

**Comment by pippakiwi** [comment]
I also meet this error(with pytorch1.0).
change "from model import DAAN"  to "import DAAN" in "train.py" can solve this problem.
There two files named "DAAN" in this project. The correct one defines "dcis" networks to align local distribution.
Hope to help you.

**Comment by pippakiwi** [comment]
@jindongwang  
![AG5GMT5IP95}GSGLS0 K IP](https://user-images.githubusercontent.com/43927048/68934924-960a3780-07d2-11ea-98fe-9dea4214693b.png)
I cloned this project yesterday. And I submit a issue (#128) to point out this error. Maybe user "superhui"  has corrected this error.~

**Comment by jindongwang** [comment]
I see
