### ISSUE TITLE
想请教一下作者关于无监督的Task Transfer的问题？

### ISSUE THREAD

**Issue by A-suozhang** [jindongwang/transferlearning#129]
首先，非常感谢您的整理！对我们初接触这个领域的初学者带来了不小的帮助。对这方面的工作有一些疑问，目前是否有task trasmfer结合Semi-Supervised的场景，利用很多未标注的数据完成任务的迁移。比如从Imagenet迁移到CUB200，当前有Label的数据较少，是否可以通过引入大量Unlabel的数据联合训练（类似于经典的Semi-Supervised Learning问题，4000个标签训Cifar）以提高Performance。感觉这样的Idea应该有人想到，但是目前做文献调研的时候没有太找到，望予以解惑！

**Comment by jindongwang** [comment]
引入更多的训练数据帮助你 目标任务，这不是一个具体的方法，只是一种思想。具体你可以看看unsupervised learning领域的知识，搜索一下。

**Comment by A-suozhang** [comment]
> 引入更多的训练数据帮助你 目标任务，这不是一个具体的方法，只是一种思想。具体你可以看看unsupervised learning领域的知识，搜索一下。

非常感谢！从您给的Reading List参阅了相关文章，有很大收获，再次感谢您的整理！
