### ISSUE TITLE
适配层数？

### ISSUE THREAD

**Issue by zhangyyyoung** [jindongwang/transferlearning#133]
代码中是不是只用了最后一层特征算MMD呀？我看论文说的是多层（3）？

**Comment by qq490516306** [comment]
你有跑那个DAN的代码吗，为啥数据标签都是0啊，准确率都是100%

**Comment by zhangyyyoung** [comment]
数据集的问题，你改一改，直接解压就是一个类
改成这个样子






&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qq490516306"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午2:35
收件人:&nbsp;"jindongwang/transferlearning"<transferlearning@noreply.github.com&gt;;
抄送:&nbsp;"张艺杨"<1335479934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jindongwang/transferlearning] 适配层数？ (#133)




你有跑那个DAN的代码吗，为啥数据标签都是0啊，准确率都是100%

**Comment by qq490516306** [comment]
哪样子啊- -

**Comment by zhangyyyoung** [comment]
原来不是Amazon里面是一个文件夹（好像是image？），那个文件夹里面放的不同类的图片，你把那些文件夹直接放在amazon下面，其他两个也是这么处理。。。
不然会被认为只有image那一个类



------------------------------------------------------------------------------------------
张艺杨
清华大学自动化系
Yiyang&nbsp;Zhang
Department of Automation,Tsinghua University




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qq632943759"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午2:40
收件人:&nbsp;"jindongwang/transferlearning"<transferlearning@noreply.github.com&gt;;
抄送:&nbsp;"张艺杨"<1335479934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jindongwang/transferlearning] 适配层数？ (#133)




哪样子啊- -

**Comment by qq490516306** [comment]
酱紫- -啊

**Comment by qq490516306** [comment]
酱紫- -啊

**Comment by qq490516306** [comment]
那个代码里的MMD都是一层，论文是3层

**Comment by zhangyyyoung** [comment]
恩是呀&nbsp;感觉不能用啊 不是官方的东西的话……
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qq632943759"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午2:45
收件人:&nbsp;"jindongwang/transferlearning"<transferlearning@noreply.github.com&gt;;
抄送:&nbsp;"张艺杨"<1335479934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jindongwang/transferlearning] 适配层数？ (#133)




那个代码里的MMD都是一层，论文是3层

**Comment by qq490516306** [comment]
好像那篇论文的源码在论文后面有给github的链接

**Comment by jindongwang** [comment]
#55

**Comment by zhangyyyoung** [comment]
原作者也是适配一层的话我就可以放心只写一层当baseline了，谢谢王博士呀~
