### ISSUE TITLE
Add some code

### ISSUE THREAD

**Issue by Dr-Zhou** [jindongwang/transferlearning#134]
Could you add some code for tSNE in the repository? This may give us a better show. Thank you.

**Comment by jindongwang** [comment]
Good advice. tSNE is popular for visualizing features and comparing different methods. I'll find some time to add it. Of course you are welcome to do it. I'll leave this issue open untile it's been solved.

**Comment by Dr-Zhou** [comment]
Thank you very much。

**Comment by jindongwang** [comment]
@Dr-Zhou Do you think this new aded [code](https://github.com/jindongwang/transferlearning/blob/master/code/utils/feature_vis.py) solve this issue?
