### ISSUE TITLE
Pretrained ResNet50 model download links problem

### ISSUE THREAD

**Issue by openyuanmu** [jindongwang/transferlearning#136]
1. baiduYun link of "Finetuned ResNet-50 models For Office-31 dataset" contains: the model on dslr, amazon and best_mnist_usps.pth, instead of the model on webcam;
2. Mega links are extracted features, instead of models.

Could you please fix them?
Thanks.

**Comment by jindongwang** [comment]
Sorry, the models are lost since I left them on the server from my Ph.D. lab, while I'm already graduated. If you want to use the model, you can use code for the finetune and feature extractor to train one. It's easy. If you have any problems regarding the code, you can let me know.
