### ISSUE TITLE
ValueError in deep/DaNN/main

### ISSUE THREAD

**Issue by MillenniumFalcon1097** [jindongwang/transferlearning#139]
I'm using python3.6 with pytorch 1.2.0 and torchvision 0.4.0. However, when I run main.py I meet the problem shown as:
File "main.py", line 102, in <module>
    model=train(model=model,optimizer=optimizer,epoch=e,data_src=data_src,data_tar=data_tar)
  File "main.py", line 43, in train
    loss_c=criterion(y_src,target)
ValueError: Expected input batch_size (192) to match target batch_size (64).
How can I fix this bug? Thx for your reply.

**Comment by sivanWu0222** [comment]
I have fixed this bug in my repository [https://github.com/sivanWu0222/transferlearning] and i have pulled requests about this problem in [https://github.com/jindongwang/transferlearning/pull/140?w=1]. Just visit one of the previous two websites, you could get the correct code.
@jindongwang 
- First solution:
> open data_loader.py
> use '#' to comment  transforms.Normalize(mean=(0,0,0),std=(1,1,1))

- Second solution:
> open data_loader.py
> modify transforms.Normalize(mean=(0,0,0),std=(1,1,1)) to transforms.Normalize(mean=(0,),std=(1,))

**Comment by jindongwang** [comment]
@sivanWu0222 Thanks!
