### ISSUE TITLE
你好，关于DAAN的实现有一些疑问

### ISSUE THREAD

**Issue by zstbackcourt** [jindongwang/transferlearning#142]
在model/DAAN.py的65 line，经过GRL得到的s_reverse_feature和t_reverse_feature为什么还要分别乘上对应的图像分类的分类概率fs = ps * s_reverse_feature和ft = pt * t_reverse_feature，这里的实现似乎和论文原文不太一样，这样实现有什么具体的意义么？谢谢

**Comment by jindongwang** [comment]
@Supe2015

**Comment by Supe2015** [comment]
@zstbackcourt 这里是做local特征适配，相当于用一种注意力机制对每个类别适配，而global是对全局做适配。
