### ISSUE TITLE
Cannot download data sets

### ISSUE THREAD

**Issue by LA-AI** [jindongwang/transferlearning#144]
Would you please tell me how can I download the Amazon reviews data set from your provided link on https://pan.baidu.com/?
Unfortunately, I do not have a Baidu account and I am out of China. 
Would you please provide a MEGA link for this data set too? Thank you so much in advance.

**Comment by jindongwang** [comment]
https://mega.nz/#F!RS43DADD!4pWwFA0CBJP1oLhAR23bTA
Thanks for the feedback! I would update this link soon!

**Comment by LA-AI** [comment]
Thank you so very much indeed!
