### ISSUE TITLE
关于DAAN loss的疑问

### ISSUE THREAD

**Issue by zstbackcourt** [jindongwang/transferlearning#145]
关于DAAN的loss有一点小的问题，soft_loss是分类器的loss是应该越小越好，那么join_loss是global和local discriminator的loss，这个loss的变化趋势应该如何？是越小越好，还是应该和GAN的discriminator loss一样？谢谢

**Comment by zstbackcourt** [comment]
@jindongwang

**Comment by jindongwang** [comment]
这个loss和之前DANN的意思差不多，只不过它是由2部分构成，我们的目标还是要让这个loss整体越来越小。

**Comment by zstbackcourt** [comment]
@jindongwang 所以您的意思是分类器loss(soft_loss)和那个daan的global、local loss都是要越小越好是么？

**Comment by jindongwang** [comment]
是的

**Comment by zstbackcourt** [comment]
谢谢
