### ISSUE TITLE
iterator for the target dataset

### ISSUE THREAD

**Issue by fbiying87** [jindongwang/transferlearning#146]
Thanks so much for sharing these awesome projects regarding transfer learning. I learned a lot by going through your projects. 

I have only a short question regarding the value batch_j in the transferlearning/code/deep/DaNN/main.py for example. It always stays 0. Should it be increasing somehow?

I am quite new to the topic domain adaptation. Therefore I have some other questions regarding the update rule for the mmd loss. My problem is that my source dataset is far larger than the target dataset. Sometimes, I only use 20% of the target dataset to train the network. So the iteration for the target set will be far finished before the source dataset iterator ends. If I only iterate through the number of target dataset, then I am only visiting part of the source dataset. How can I understand the update rule for the mmd_loss on each batch? Is it valid to update mmd_loss on each batch or do I need to update it on the entire source and target dataset in a single step?

Thanks for your help. 

Best regards!

**Comment by jindongwang** [comment]
Hello, the DaNN code is too old. If you want to learn deep transfer networks such as DaNN, I recommend you see the code of DDC_DCORAL, which is basically the same as DaNN except the backbone networks. I'm planning to merge the code of DaNN to DDC_DCORAL.
