### ISSUE TITLE
How to use the transfer-learning to the RNN model?

### ISSUE THREAD

**Issue by YangY-Z** [jindongwang/transferlearning#147]
As we all know, the transfer-learning has been used in the CNN-based model successfully, but how to use the methods to the RNN-based model? If I have a model that was trained on a time series dataset, can I use the transfer-learning to tranfer the model to a special task? I hope the author can answer my question, thanks!

**Comment by jindongwang** [comment]
Yes you can. Some models such as ConvLSTM can also be used for transfer. You can search related articles on Google scholar.

**Comment by YangY-Z** [comment]
Thank you for your answer! But I have another question. The transfer learning can be divided into four categories: Sample-based, model-based, feature-baseda and relationship-based transfer. But I want to known which category does the domain adaptation fall into? I am anticipating your reply thanks!

**Comment by schwxd** [comment]
Domain adaptation is a particular case of Transfer learning. In DA, the target task and the source task is the same, so the target task shares the the class labels with the source task. The four categories you mentioned are different implementation methods.
