### ISSUE TITLE
DAAN训练中是否出现过global loss不断增大最后NAN的情况？

### ISSUE THREAD

**Issue by zstbackcourt** [jindongwang/transferlearning#148]
请问你们在训练的过程中是否出现过global loss不断增大最后NAN的情况，可能导致这个问题的原因可能是什么？谢谢 @Supe2015

**Comment by jindongwang** [comment]
@Supe2015

**Comment by Supe2015** [comment]
@zstbackcourt 
你是什么数据集？你可以git pull，然后调调学习率不要太大
