### ISSUE TITLE
关于GFK算法中d的确定

### ISSUE THREAD

**Issue by leshansanren** [jindongwang/transferlearning#15]
王老师你好！我在应用GFK算法时，利用SDM方法确定d的个数，我的S是30x28的矩阵，T是30x28的矩阵，则S+T应该为60x28维的矩阵（不知道对不对？），再利用SDM求解两个domain与S+T的空间的夹角时，利用pca对三个数据集进行降维以后，不知道该怎么进行下一步求解sin（αd）和sin（βd）？我试过先求余弦值，再根据公式转换，但是求解数据长度不一致的余弦值应该怎么求？还有就是在求解夹角的时候是应该求pca以后的S和T与S+T的第1,2，…，d个向量的夹角，还是应该分别求d=1,2,3，…时的d维矩阵的夹角？

**Comment by jindongwang** [comment]
看附件，可以直接用


发件人： leshansanren<mailto:notifications@github.com>
发送时间： 2018-03-03 15:06:16
收件人：  jindongwang/transferlearning<mailto:transferlearning@noreply.github.com>
抄送：  Subscribed<mailto:subscribed@noreply.github.com>
主题： [jindongwang/transferlearning] 关于GFK算法中d的确定 (#15)

王老师你好！我在应用GFK算法时，利用SDM方法确定d的个数，我的S是30x28的矩阵，T是30x28的矩阵，则S+T应该为60x28维的矩阵（不知道对不对？），再利用SDM求解两个domain与S+T的空间的夹角时，利用pca对三个数据集进行降维以后，不知道该怎么进行下一步求解sin（αd）和sin（βd）？我试过先求余弦值，再根据公式转换，但是求解数据长度不一致的余弦值应该怎么求？还有就是在求解夹角的时候是应该求pca以后的S和T与S+T的第1,2，…，d个向量的夹角，还是应该分别求d=1,2,3，…时的d维矩阵的夹角？

**Comment by leshansanren** [comment]
王老师，你是在国外吗？非常抱歉！这么晚还打扰您！您说的附件是？是MyGFK.m这个文件还是其他什么文件？我在使用您的MyGFK.m文件的时候的确可以直接应用，但还是无法直接确定d的取值，然而d的取值对我的识别结果是有影响的，我不能随意设置一个d值来进行识别。。。我是初学者，有很多问题都不太明白，希望您的答复能更详细一些，给您添麻烦了，再次感到万分抱歉！

**Comment by jindongwang** [comment]
@leshansanren 不好意思，我直接回复的邮箱，给你传了写好的计算d的.m文件，但是Github没有识别出来。
你不需要自己实现SDM，subsapce alignment的作者已经写好了，在这里你可以下载：https://www.jianguoyun.com/p/DdI417oQjKnsBRiI8kQ

**Comment by leshansanren** [comment]
没关系，给您添麻烦了！再次感谢您的帮助，谢谢！
