### ISSUE TITLE
A problem of TCA.m

### ISSUE THREAD

**Issue by BranWang9285** [jindongwang/transferlearning#150]
请问这两句代码的作用是什么
X = X*diag(sparse(1./sqrt(sum(X.^2))));
Z = Z*diag(sparse(1./sqrt(sum(Z.^2))));
与python版本的似乎有点不一样

**Comment by jindongwang** [comment]
简单的归一化，可以删掉，没什么大影响。

**Comment by BranWang9285** [comment]
感谢大神的回复，万分荣幸




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jindong Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月10日(星期五) 上午10:23
收件人:&nbsp;"jindongwang/transferlearning"<transferlearning@noreply.github.com&gt;;
抄送:&nbsp;"特,小丑"<464795767@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jindongwang/transferlearning] A problem of TCA.m (#150)




简单的归一化，可以删掉，没什么大影响。
