### ISSUE TITLE
Dann和DDC_DeepCoral

### ISSUE THREAD

**Issue by AIPENG2017** [jindongwang/transferlearning#151]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.
my software is python 3.6.10,pytest-5.3.2,py-1.8.1

**Describe the bug**
The Bug is that No tests were found and Empty suite. Replace the name 'test'  with the others is not a solution
**To Reproduce**
Where is this bug happen?
pycharm2019.3.1
**Screenshots**

**Comment by AIPENG2017** [comment]
您好， 代码运行不了，将代码中的test替换掉也不管用，一直提示No tests were found and empty suite

**Comment by jindongwang** [comment]
这是pycharm的设定问题，自动认为test的字样是测试用例。你可以直接命令行里运行

________________________________
发件人: AIPENG2017 <notifications@github.com>
发送时间: Friday, January 10, 2020 9:30:49 PM
收件人: jindongwang/transferlearning <transferlearning@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [jindongwang/transferlearning] Dann和DDC_DeepCoral (#151)


您好， 代码运行不了，将代码中的test替换掉也不管用，一直提示No tests were found and empty suite

―
