### ISSUE TITLE
关于MMD

### ISSUE THREAD

**Issue by yyssmm** [jindongwang/transferlearning#152]
王老师您好：
首先感谢您的开源贡献，让大家受益匪浅。我i最近看了一篇文章，被里面的一句话困扰了很久。论文的原话是 “MMD loss is also proposed to map instances from the source domain and target domain into a new data space, but it requires that the source and target domain have identical classes”。这里我有个困惑，MMD （Wasserstein Distance 类似） 是衡量两个分布之间的距离，应用的时候我们没用到两个域的数据标签，那为什么要求两个域的类别数一致呢。难道是因为他们只能用于条件分布一致，仅仅边缘分布不同情况下的域迁移吗？能请您帮忙解释一下这个问题吗？谢谢

**Comment by jindongwang** [comment]
MMD的计算本来就和label无关。你的理解正确。
你提到的这句话的理解，要结合相应的paper来看，不可断章取义。
