### ISSUE TITLE
关于TCA

### ISSUE THREAD

**Issue by LouBABY** [jindongwang/transferlearning#153]
王老师您好，我想请问您一下，您开源的TCA python代码中衡量分布差异使用的是核均值匹配吗？还是最大均值差异呢？麻烦您能指点一下，谢谢！

**Comment by jindongwang** [comment]
最大均值差异

**Comment by LouBABY** [comment]
谢谢王老师的回复，真的很感谢！不好意思，我想再请问一下，我按照您迁移学习简明手册上的公式对照着看程序，感觉好像有点对不上，然后请问您给的数据集是时域信号吗，我用您的数据程序跑下来精度能达到0.96，但是用自己的数据，调参以后精度还是很低，希望您能再次指点一下，万分感谢！

**Comment by jindongwang** [comment]
最新的TCA代码都统一用的office数据集，你可以再更新一下github上的代码。

**Comment by LouBABY** [comment]
万分感谢王老师的指点！我继续再研究学习一下。
