### ISSUE TITLE
TCA得到变换矩阵后，对新样本的分类如何做？

### ISSUE THREAD

**Issue by wchstorm1** [jindongwang/transferlearning#155]
王老师您好，非常感谢在迁移学习方面知识的普及工作。您的工作带我走进了迁移学习的大门。最近看了TCA的论文，有问题想问下。matlab代码输出有三个，X_src_new、X_tar_new和A。我利用X_src_new训练了新的分类器，可以对X_tar_new重新分类。但是如果我有一个新样本x要识别（既不在X_src中，也不在X_tar中），那么我该如何获取变换后的新特征？因为矩阵维数的A不一样，无法直接相乘。

难道要攒够一定量的新样本，重新执行TCA算法，再得到新的特征和矩阵A么？求指点。

**Comment by jindongwang** [comment]
是的，TCA不能用于在线算法，每次需要重新计算新的变换矩阵。当然你也可以认为这个变换矩阵是有代表性的，直接用它来变换新样本也是可以的。

**Comment by wchstorm1** [comment]
好的，明白了，非常感谢回复！
