### ISSUE TITLE
DAN和DDC_DeepCoral中的MMD区别

### ISSUE THREAD

**Issue by AIPENG2017** [jindongwang/transferlearning#157]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.
DAN用的是多核MMD，核数量kernel_num=5，而DDC_DeepCoral是单核MMD，为什么kernel_num也是5呢？另外MK-MMD学习的权重Beta，对应代码的那个参数呢？
**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by jindongwang** [comment]
MK-MMD的原代码就是这样写的。事实证明MK-MMD并没有什么特别用处，直接用线性kernel，或者随便用一个rbf效果差不多
