### ISSUE TITLE
关于DANN(RevGrad)

### ISSUE THREAD

**Issue by yyssmm** [jindongwang/transferlearning#158]
王老师您好：
最近看到您更新了DANN(RevGrad)的代码，新代码的main.py 中在求总的loss 的时候，您是这么写的
err = err_s_label + args.gamma * err_domain， 新增加的 args.gamma具体有什么作用呢？谢谢

**Comment by jindongwang** [comment]
就是一个权重呀，可以调的参数

**Comment by yyssmm** [comment]
@jindongwang  谢谢王老师的解释！我最近在将梯度反转这样的方法用到自己的研究工作中，但是对于err = err_s_label + args.gamma * err_domain里面的args.gamma，还有梯度反转时乘的参数lamda，他们各自代表的含义和作用不是很清楚，导致在调节参数的时候不知道该怎么平衡这两个权重的值。能不能请王老师帮忙解释一下他们各自的作用和区别，或者是该如何设置他们的值啊？谢谢王老师！

**Comment by jindongwang** [comment]
没有什么经验，就是几个超参数，你自己调就是了。
