### ISSUE TITLE
The NaN issues in EasyTL/CORAL_map.m

### ISSUE THREAD

**Issue by KodeWorker** [jindongwang/transferlearning#160]
Hi Mr. Wang,

While running demo_amazon_review.m, we come across some NaN issues in CORAL_map.m
<pre><code>function [Xs_new] = CORAL_map(Xs,Xt)
    cov_src = cov(Xs) + eye(size(Xs,2));
    cov_tar = cov(Xt) + eye(size(Xt,2));
    A_coral = cov_src^(-1/2) * cov_tar^(1/2);
    Xs_new = Xs * A_coral;
end
</code></pre>

1. The NaN values in Xs or Xt will cause covariance matrix contains NaN
2. The negative covariance in cov_src or cov_tar will lead to NaN values in A_coral

any suggestions would help :)

BR,
KW

**Comment by jindongwang** [comment]
Then you need to handle the NaN value in your inputs. Maybe try some preprocessing skills?

**Comment by KodeWorker** [comment]
These problems happened when we try to implement EasyTL in Python.
1. We found out that NaN is introduced due to the differences between scipy.stats.zscore and MATLAB zscore.
The column with all 0s will return NaN while MATLAB zscore return 0s.
We simply replace NaN with 0, and the result remain the same.

2. The other problem is just my misunderstanding of M^(-1/2) notation in MATLAB.
M^(-1/2) = (M^(-1))^(1/2) = sqrtm(inv(M))
This is not element-wise operation such as numpy.power(M, -1/2)

**Comment by jindongwang** [comment]
@KodeWorker Glad to hear that you are using python to implement EasyTL! If your version works, please send it to Git pull! Thanks!

**Comment by KodeWorker** [comment]
@jindongwang 
We implemented pyEasyTL in this [repo](https://github.com/KodeWorker/pyEasyTL).
This is very primitive version and the results of Amazon Review Experiment are shown below:

Method|EasyTL(c)|EasyTL
--------|--------|--------
B→D | 78.4 | 79.8
B→E | 77.5 | 79.7
B→K | 79.2 | 80.9
D→B | 79.5 | 79.9
D→E | 77.4 | 80.8
D→K | 80.4 | 82.0
E→B | 73.0 | 75.0
E→D | 73.1 | 75.3
E→K | 84.6 | 84.9
K→B | 75.1 | 76.5
K→D | 73.8 | 76.3
K→E | 82.0 | 82.5
AVG | 77.8 | 79.5

These are still some progress to make.
I'll send pull request once the "not implemented yet!" part are done.

**Comment by jindongwang** [comment]
Ok
