### ISSUE TITLE
About VLSC dataset

### ISSUE THREAD

**Issue by luffy-yu** [jindongwang/transferlearning#161]
Where to download the original images of the VLSC dataset?

I figure out some URLs, might wrong, through my endeavor.
 
[VOC2007](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/)
[LabelMe](http://www.ais.uni-bonn.de/download/datasets.html)
[SUN09](http://groups.csail.mit.edu/vision/Hcontext/data/sun09.tar)
[Caltech-101]( http://www.vision.caltech.edu/Image_Datasets/Caltech101/Caltech101.html)

BUT, why don't they contain the five classes('bird', 'car', 'chair', 'dog', 'person')?

**Comment by jindongwang** [comment]
The dataset is provided by the relative references. I don't know there original images. You can contact the author.

Dataset reference: Chen Fang, Ye Xu, and Daniel N Rockmore. 2013. Unbiased metric learning: On the utilization of multiple datasets and web images for softening bias. In Proceedings of the IEEE International Conference on Computer Vision. 1657–1664.
