### ISSUE TITLE
mnist_m  dataset was cancelled in yunPan

### ISSUE THREAD

**Issue by liumiao-p** [jindongwang/transferlearning#163]
mnist_m  dataset was cancelled in yunPan and I cannot open google drive. sad...How can I get mnist_m?

**Comment by jindongwang** [comment]
链接: https://pan.baidu.com/s/1tN4Df33sSTQiLqNFM-i7GA 提取码: 9hs9

**Comment by viki6666** [comment]
> mnist_m dataset was cancelled in yunPan and I cannot open google drive. sad...How can I get mnist_m?
请问你有存下这个数据集么？之前分享的连接过期了。如果方便能否分享一下，多谢！

**Comment by viki6666** [comment]
> mnist_m dataset was cancelled in yunPan and I cannot open google drive. sad...How can I get mnist_m?
请问你有存下这个数据集么？之前分享的连接过期了。如果方便能否分享一下，多谢！

**Comment by viki6666** [comment]
> mnist_m dataset was cancelled in yunPan and I cannot open google drive. sad...How can I get mnist_m?
请问你有存下这个数据集么？之前分享的连接过期了。如果方便能否分享一下，多谢！

**Comment by viki6666** [comment]
> 链接: https://pan.baidu.com/s/1tN4Df33sSTQiLqNFM-i7GA 提取码: 9hs9

您好，网盘链接过期了，能否再分享一份？麻烦您了！

**Comment by jindongwang** [comment]
链接: https://pan.baidu.com/s/1viW9eAypbTDwowGbZcdFyw 提取码: 3kui

**Comment by viki6666** [comment]
> 链接: https://pan.baidu.com/s/1viW9eAypbTDwowGbZcdFyw 提取码: 3kui

感谢！

**Comment by Leohoo27** [comment]
请问有office-home dataset的云盘链接么？谢谢。

**Comment by jindongwang** [comment]
@Leohoo27 那个数据集我放了官方链接的，你是上不了Google drive吗？

**Comment by Leohoo27** [comment]
> @Leohoo27 那个数据集我放了官方链接的，你是上不了Google drive吗？

@jindongwang 是的，数据集太大，用Google drive下载速度很慢。

**Comment by jindongwang** [comment]
https://mega.nz/#!cbgkFaQb!AexvHTVqgEQy99CGCkMiNyjVImA-Uql66t143TMYG8M
