### ISSUE TITLE
TCA的数据集问题和benchmark结果md的问题

### ISSUE THREAD

**Issue by VoiceBeer** [jindongwang/transferlearning#169]
前辈您好，感谢您的手册和贡献，受益匪浅。

我目前有两个问题：

1. TCA python的代码上写的是例如webcam.mat这种的文件，但是我看了dataset里的office相关的数据集，最接近的也就是webcam_SURF_L10.mat，但是对不上。请问这里应该怎么操作？

2. benchmark results中列tag比如A-W，A-D之类的是什么意思？

提前感谢您的回答，希望一切顺利😆

**Comment by VoiceBeer** [comment]
我刚看了下附录里对数据集的解释，第二个问题已经理解了

**Comment by jindongwang** [comment]
@VoiceBeer 你第一个问题里两个.mat是一样的，webcam就是surf特征。当然你可以用任何特征。

**Comment by VoiceBeer** [comment]
> @VoiceBeer 你第一个问题里两个.mat是一样的，webcam就是surf特征。当然你可以用任何特征。

谢谢前辈的回答，对应的readme写着可以直接运行py文件，但是会报错，我改了主函数里domains对应的名称后又回报错后面feas和label的错。我看了下mat文件的数据后也没看到label和feas之类的tag，是我方式不对吗？

**Comment by jindongwang** [comment]
可能mat文件里的标签不对了，以实际标签为准。

**Comment by VoiceBeer** [comment]
> 可能mat文件里的标签不对了，以实际标签为准。

行明白了，非常感谢前辈的回答！
