### ISSUE TITLE
为什么数据集ImageCLEF的domain p有591张图片，而pList中有600个标签呢?

### ISSUE THREAD

**Issue by kind-hearted-Tbag** [jindongwang/transferlearning#17]

**Comment by jindongwang** [comment]
我确认过了，domain p也有600张图片。可能是你下载的数据集有问题？

**Comment by kind-hearted-Tbag** [comment]
谢谢您的回复，我再次确认了下，确实只有591张，我是在您给的百度网盘链接上下得，我再重新下载一遍看一下。


------------------ 原始邮件 ------------------


发件人: "Jindong Wang"<notifications@github.com>;

发送时间: 2018年4月8日(星期天) 下午3:07

收件人: "jindongwang/transferlearning"<transferlearning@noreply.github.com>;

抄送: "虫洞"<2279767412@qq.com>; "Author"<author@noreply.github.com>; 

主题: Re: [jindongwang/transferlearning] 为什么数据集ImageCLEF的domain p有591张图片，而pList中有600个标签呢? (#17)




我确认过了，domain p也有600张图片。可能是你下载的数据集有问题？

**Comment by jindongwang** [comment]
@kind-hearted-Tbag 就那一个数据，我就是在那里确认的，没问题

**Comment by kind-hearted-Tbag** [comment]
我又下了一遍，里面有b,c,i,p四个domain  有4个list。  其中就只有p只有591张图片，其他三个是600张，难道那个b是p吗，论文中只有c,i,p三个domain。

**Comment by jindongwang** [comment]
@kind-hearted-Tbag 是我疏忽了！不好意思！
这个p domain确实只有591张图片，pList里有600个，是因为里面有重复的！比如2598.jpg，等等。
诡异的是相同的一张图片，类别还不一样。我问一下原作者！

**Comment by jindongwang** [comment]
@kind-hearted-Tbag 作者承认了是数据错误！

**Comment by jindongwang** [comment]
等作者更新
