### ISSUE TITLE
你好！ 请教下DDC_DeepCoral中训练数据的问题

### ISSUE THREAD

**Issue by acmff22** [jindongwang/transferlearning#170]
你好，代码中读取了全部的source和target数据，但是输入到网络里时只用了与target数量相同的source数据。如何使剩余的source也参与到训练中？尤其在source和target数量差距过大时，输入网络source的数量不足以训练分类的loss。
谢谢！

**Comment by jindongwang** [comment]
代码中用了迭代器，所以不存在“剩余的source不参加训练”这种情况。
如果两方差距过大，那不建议用迁移学习。可以先用data augmentation生成一些数据，再迁移。

**Comment by acmff22** [comment]
好的，谢谢！
