### ISSUE TITLE
想请教下JAN的问题

### ISSUE THREAD

**Issue by zjzzzz** [jindongwang/transferlearning#171]
王博您好，我最近在看DDC、DAN、JAN。我对于这三者损失函数的理解：DDC是对于一层加了MMD距离；而DAN是对多层加了MMD距离，然后把这些距离相加作为约束项；JAN是对多层做MMD距离，然后是把MMD距离相乘作为约束项，其实JAN并没有对label进行什么约束。不知道我对于JAN的理解是否正确，感觉怪怪的，主要是为什么每层MMD距离相乘作为约束项会比每层MMD距离相加效果要好？还有个问题是为什么每层MMD距离相乘就是的适配联合概率密度？（虽然有数学推导，但是不知道王博您有没有通俗点的角度）

**Comment by jindongwang** [comment]
JAN我已经忘了。。。我复习一下再回复你

**Comment by zjzzzz** [comment]
万分感谢


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Jindong Wang <notifications@github.com&gt;
发送时间: 2020年4月17日 21:16
收件人: jindongwang/transferlearning <transferlearning@noreply.github.com&gt;
抄送: zjzzzz <470143904@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[jindongwang/transferlearning] 想请教下JAN的问题 (#171)





 
JAN我已经忘了。。。我复习一下再回复你

**Comment by jindongwang** [comment]
@zjzzzz JAN是利用了下面这个kernel embedding的性质，来近似地用若干feature的embedding乘积，表达joint distribution:
![image](https://user-images.githubusercontent.com/6158206/79750283-44e30e80-8343-11ea-9bd4-7449be1f0a9a.png)
这个性质最早是图中引文第一条，Song Le老师的paper里写过的，你可以去看看。

**Comment by q996676479** [comment]
楼主你看代码了吗，为什么我发现代码里DDC和DAN都是对单层（分类器前的一层）进行适配的，只是DAN用的是MK-MMD

**Comment by jindongwang** [comment]
@q996676479 这个问题之前也有别人问过。DAN龙老师的代码pytorch版本就是一层的，他们caffe的代码是多层的。你可以去他们的github: thuml下看看。

**Comment by q996676479** [comment]
> @q996676479 这个问题之前也有别人问过。DAN龙老师的代码pytorch版本就是一层的，他们caffe的代码是多层的。你可以去他们的github: thuml下看看。



> @q996676479 这个问题之前也有别人问过。DAN龙老师的代码pytorch版本就是一层的，他们caffe的代码是多层的。你可以去他们的github: thuml下看看。
感谢！
