### ISSUE TITLE
DaNN的main.py中target的batch问题

### ISSUE THREAD

**Issue by ngx2333** [jindongwang/transferlearning#173]
DaNN的main.py的train中，在从dataset_src和dataset_tar取batch时，dataset_tar使用batch_j作为索引，但是**batch_j并没有更新**。
详见DaNN的main.py的train函数,主要是30-38行。

**Comment by jindongwang** [comment]
@ngx2333 感谢指正！确实是当时重写的时候犯了错误，batch_j应该是要自增的，已改正。
