### ISSUE TITLE
eval模式下结果远差于train模式

### ISSUE THREAD

**Issue by acmff22** [jindongwang/transferlearning#176]
利用迁移学习进行关键点检测，在前向传播中参考DEEP CORAL分别将source data与target data输入模型。训练阶段关键点预测的loss降到很低，但是在测试时，输入相同的数据，结果远差于训练时,网上查阅一些资料，说是重用了网络中的BN层，我输出了训练和测试阶段BN层的均值和方差，发现两个阶段下BN层的均值和方差不同导致了这种差异。您是否碰到过类似的问题，是如何解决的？

**Comment by jindongwang** [comment]
可以试试TransNorm：https://papers.nips.cc/paper/8470-transferable-normalization-towards-improving-transferability-of-deep-neural-networks
