### ISSUE TITLE
关于DeepCORAL的Coral.py

### ISSUE THREAD

**Issue by yfeiyu** [jindongwang/transferlearning#179]
你好，我最近拜读库中DeepCORAL方法的源码时，发现Coral.py文件中第17行求loss的代码与原来文献中的描述不符。原文献中的coral loss中求的是frobenius norm的平方，而代码段中求的是frobenius norm。我建议去掉“.sqrt()”，我想询问你对此的看法与意见。
原文献中的部分：
![image](https://user-images.githubusercontent.com/43987085/83934305-986dc680-a7e2-11ea-835f-96207e1eda75.png)
Coral.py中的代码段：
![image](https://user-images.githubusercontent.com/43987085/83934201-6e67d480-a7e1-11ea-937b-e1b59c212912.png)

代码链接： https://github.com/jindongwang/transferlearning/blob/master/code/deep/DDC_DeepCoral/Coral.py

**Comment by jindongwang** [comment]
实际应用中发现sqrt可能收敛比原版的快，这个可以根据你的应用效果来看。
