### ISSUE TITLE
数据集载入过程后得到的label 的张量都为0

### ISSUE THREAD

**Issue by Eggwardhan** [jindongwang/transferlearning#182]
<img width="722" alt="截屏2020-06-13 15 22 29" src="https://user-images.githubusercontent.com/32223217/84562823-d1311100-ad89-11ea-9caf-0ef47421cbc1.png">
>for (data,label) in dataloaders['src']:
  print(label)
想问下为什么载入数据集后打印出来的label张量都为0，那训练过程是怎么判断标签是多少的呢

**Comment by tytcc** [comment]
应该是数据的文件夹的格式没有按照要求的吧，一个文件夹下只有一类，这个应该是都认为是一类了。

**Comment by tytcc** [comment]
@Eggwardhan  应该是数据的文件夹的格式没有按照要求的吧，一个文件夹下只有一类，这个应该是都认为是一类了。

**Comment by jindongwang** [comment]
Yes. @tytcc is right.
