### ISSUE TITLE
关于DAN在Office-31数据集上实验的问题

### ISSUE THREAD

**Issue by Dayro-9** [jindongwang/transferlearning#183]
王博，您好，谢谢您的分享
我是一名统计学专业的研一学生，正在学习迁移学习，在运行DAN代码时，产生了一些疑问，想向您请教。我在Google Colab上运行了DAN的代码，进行A->D的迁移任务的第一轮迭代时，loss,soft_loss和mmd_loss都有变化，但是精确率就达到了100%。之后进行其他几个任务，也出现了同样的情况，部分实验结果如下图所示，请问这是什么原因？
最后，感谢您的阅读
![结果1](https://user-images.githubusercontent.com/59091691/85261868-6f665a80-b49f-11ea-86e5-2bd5b5a155e9.png)
![结果2](https://user-images.githubusercontent.com/59091691/85261871-71c8b480-b49f-11ea-8ffd-cd054dcbb471.png)

**Comment by jindongwang** [comment]
Office-31数据集路径传的有问题，domain外面还有一层images文件夹。参考 #182

**Comment by Dayro-9** [comment]
> Office-31数据集路径传的有问题，domain外面还有一层images文件夹。参考 #182
谢谢您的回答，帮助我解决了问题
