### ISSUE TITLE
关于算法最终性能的取值

### ISSUE THREAD

**Issue by Carbord** [jindongwang/transferlearning#184]
您好，由于我是迁移学习刚入门的新手，有个简单的问题想咨询下，比如类似DSAN代码这样的，每训练一个epoch,就test一下，得到相关的performance，然后想问的是在这种设置下，最终报告的精度是要取在所有epoch中最佳的吗？因为想把迁移学习方法用在其他一些任务上，然后感觉如果是训练若干epoch来取最佳，好像有点用测试集来引导训练的样子。希望得到您的回复，谢谢~

**Comment by jindongwang** [comment]
应该是在验证集上的精度最优的时候对应的测试集的性能。
但是大多数domain adaptation方法没有验证集（测试集本身就是验证集）。所以你只能把测试集当成验证集来用。或者在source domain上分出一些验证集来。
前一种的话，我们一般不怎么调参数，保证不是针对测试集调的就可以。一般统一参数。

**Comment by Carbord** [comment]
> 应该是在验证集上的精度最优的时候对应的测试集的性能。
> 但是大多数domain adaptation方法没有验证集（测试集本身就是验证集）。所以你只能把测试集当成验证集来用。或者在source domain上分出一些验证集来。
> 前一种的话，我们一般不怎么调参数，保证不是针对测试集调的就可以。一般统一参数。

明白了，谢谢
