### ISSUE TITLE
GFK使用SVM预测，以及ROD实现的一些问题

### ISSUE THREAD

**Issue by sdaheng** [jindongwang/transferlearning#185]
王老师您好，我有两个问题想请教您一下。第一个是关于对GFK使用SVM进行预测，第二个是关于论文中ROD实现上的一些问题。

1. 我用了python版本的GFK跑了一下我的数据集，数据集是一些Wi-Fi信号的信号强度值（RSS），范围都在-100～-40之间。

在1NN下准确率大概有0.4～0.6之间。我现在想换成SVM试一下。

SVM使用的是skleran的svm.SVC()。下面是我的一些代码

```
        clf_svm = svm.SVC(decision_function_shape='ovo', probability=True, kernel='precomputed')

        clf_svm.fit(np.dot(Xs_new, np.transpose(Xs_new)), Ys.ravel())

        y_pred = clf_svm.predict(np.dot(G, np.transpose(Xt_new)))

        acc = np.mean(y_pred == Yt.ravel)
```

我的问题是，我不太清楚该怎么用这个G，Xs_new, Xt_new。
看了一些别人是怎么用precomputed的核使用svm，但他们都是直接对数据进行点积运算，求了个线性核，例如X是数据，核=X·X^T。
那这里也是这样用吗？还是直接用G，或者用G乘些什么。

2. 我最开始使用matlab跑的数据集，所以在matlab上根据原论文作者提供的补充材料里的推导实现了一下ROD的算法。下面是我实现的算法

```
function rod = ROD(X_src, X_tar)
    Ps = pca(X_src);
    Pt = pca(X_tar);
    
    [U, gamma, V] = svd(Ps' .* Pt);
    
    si = Ps * U;
    ti = Pt * V;
    
%     squareSigmaS = si' * X_src' * X_src * si;
%     squareSigmaT = ti' * X_tar' * X_tar * ti;
%     
%     squareSigmaS = 1 / size(si, 1) .* squareSigmaS;
%     squareSigmaT = 1 / size(ti, 1) .* squareSigmaT;
    
    squareSigmaS = cov(X_src * si);
    squareSigmaT = cov(X_tar * ti);
    
    theta = real(acos(gamma));
    
    d = getGFKDim(X_src, X_tar);
    
    tmp = theta .* (0.5 .* squareSigmaS ./ squareSigmaT + 0.5 .* squareSigmaT ./ squareSigmaS - eye(size(squareSigmaS)));
    
    if d > 0
        rod = real(1 / d * sum(tmp(1:d, 1:d), 1));
    else
        rod = 0;
    end
end
```

我对计算出来的ROD值使用了scale方式进行归一化，即normalizedROD=normalize(rod, 'scale')。
最终用mean(mean(normalizedROD))进行比较的。

我的问题是：
我不太清楚代码实现的对不对，还希望您能帮我看一下。
因为我在运行的时候会出现ROD值最小的一组数据用1NN预测的结果并不是最好的，而是次小的那一组。
这让我不知道是ROD实现的问题还是我使用的问题，还是KNN的问题。。。

**Comment by jindongwang** [comment]
是对G开根号然后乘以你的原数据。你可以参考这个repo下我的MEDA是怎么用G的。基本就是这样的线性变换。
这个ROD就是你这样实现的，不过实际中其实效果并不好。我们还是采用认为给定的相似度来算。没有任何一种度量能完美衡量相似问题。

**Comment by sdaheng** [comment]
哦哦 好的 谢谢王老师
