### ISSUE TITLE
Questions about enumerating dataloader in DANN code

### ISSUE THREAD

**Issue by k0ngyiji** [jindongwang/transferlearning#189]
Hi, thank you for your amazing code!

Transfer learning need to load source and target dataloader together, but len(source_loader) and len(target_loader) are always different.

I find that many paper's code loading data like this,this way seems ignore part of data_loader that has larget length:
![image](https://user-images.githubusercontent.com/68325219/90302662-4d56ea80-deda-11ea-9022-e2e5e1a2a132.png)

And DANN loads data by enumerating source_loader in the outside loop.But I don't think the inside loop can enumerate target_loader completely. If len(target_loader) > len(source_loader), should enumerating target_loader in the outside loop?
![image](https://user-images.githubusercontent.com/68325219/90302748-11705500-dedb-11ea-9e13-56ae57b46b0e.png)

Are they both right?

**Comment by jindongwang** [comment]
A good point. 
Actually, both are good. In fact, there is no 'golden standard' for loading data in two domains. You can have a third writing style as (only the main concept):

iter_src, iter_tar = iter(src_loader), iter(tar_loader)
(x_src, y_src), (x_tar, _) = iter_src.next(), iter_tar.next()
# Some try-except to re-iter these two loaders...

It doesn't matter that the two domains have different lens. By iterating (shuffle) for several epochs, we believe that all the data in two domains can be involved.

**Comment by k0ngyiji** [comment]
That makes sense.
This response helps me a lot, thanks!!!
