### ISSUE TITLE
about SURF or Decaf6 datasets

### ISSUE THREAD

**Issue by Nneeiill** [jindongwang/transferlearning#190]
Hi,
I'm wondering how to get the SURF dataset or Decaf6 dataset? Actually, I tried to do it on Matlab, but what I got was totally different from the dataset your uploaded as Caltech10_SURF_L10.mat. Could you give me some hints? Thanks

**Comment by jindongwang** [comment]
These datasets are downloaded from the web. There is no such links available. I just collected them.

发件人: Nneeiill <notifications@github.com>
发送时间: 2020年8月26日 17:52
收件人: jindongwang/transferlearning <transferlearning@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [jindongwang/transferlearning] about SURF or Decaf6 datasets (#190)


Hi,
I'm wondering how to get the SURF dataset or Decaf6 dataset? Actually, I tried to do it on Matlab, but what I got was totally different from the dataset your uploaded as Caltech10_SURF_L10.mat. Could you give me some hints? Thanks

**Comment by Nneeiill** [comment]
thanks for your reply
