### ISSUE TITLE
domain label

### ISSUE THREAD

**Issue by InstantWindy** [jindongwang/transferlearning#192]
Hi.  When traing source dataset and target dataset, the source domain label should be set 0,but you set 1 in ([line64)](https://github.com/jindongwang/transferlearning/blob/68875fa904a7c38285011f19485ea4d1d2579df0/code/deep/DANN(RevGrad)/model.py#L64)

**Comment by jindongwang** [comment]
I think that you can either use 0 for source and 1 for target, or vice versa.

**Comment by InstantWindy** [comment]
So it doesn't matter which value is 1？ When training my data, The value of err_domain has always been 1.3863 and does not drop. 
Is there a problem with my network structure？Thanks.

**Comment by jindongwang** [comment]
I think it doesn't matter. You can try to switch your optimizer to Adam and try again.

**Comment by jindongwang** [comment]
#191
