### ISSUE TITLE
GFK问题

### ISSUE THREAD

**Issue by sdaheng** [jindongwang/transferlearning#193]
王老师你好，在用GFK的时候遇到了一个问题。
用GFK迁移后新的源域与目标域，使用KNN进行分类，与不使用GFK直接使用KNN分类的准确率没什么变化。
这会是一些什么问题导致这样的结果呢？

**Comment by sdaheng** [comment]
因为源域目标域太相似？

**Comment by jindongwang** [comment]
可能你需要调一下GFK的参数（维度d）试一下

**Comment by sdaheng** [comment]
还是没啥差别
原来的特征维度是391，d设置成195，150， 130，100以及用getGFKDim都没什么区别
下面这个是各个域数据的直方图，用zscore归一化了。
![CrossTimeHistogram](https://user-images.githubusercontent.com/1405754/92544977-c3eccb00-f281-11ea-9a01-9eea8d3a0df8.png)
是不是因为太像了，所以迁移的没什么效果？

**Comment by jindongwang** [comment]
可能是吧，也可能是gfk算法不适合你的问题，你可以换个新的方法试试。

**Comment by jindongwang** [comment]
比如我们的MEDA
