### ISSUE TITLE
关于精度的问题

### ISSUE THREAD

**Issue by HWNHJJ** [jindongwang/transferlearning#197]
您好，这是我运行的结果，请问精度只有二三十是我这边的操作失误吗

1.0
0.363256784969
0.210169491525
0.254777070064

0.354407836153
1.0
0.2
0.305732484076

0.260017809439
0.263048016701
1.0
0.675159235669

0.275155832591
0.277661795407
0.620338983051
1.0

四个域如下
domains = ['Caltech10_SURF_L10.mat', 'amazon_SURF_L10.mat', 'webcam_SURF_L10.mat', 'dslr_SURF_L10.mat']

**Comment by jindongwang** [comment]
运行哪个方法？

**Comment by HWNHJJ** [comment]
您好，是GFK，运行的是python版本

**Comment by jindongwang** [comment]
Python版本在readme里说过不再维护了，因为要依赖于一个很难装上的第三方库。所以你用matlab吧。

**Comment by HWNHJJ** [comment]
> Python版本在readme里说过不再维护了，因为要依赖于一个很难装上的第三方库。所以你用matlab吧。
好滴好滴，谢谢王博士。
