### ISSUE TITLE
关于准确率的一些疑问

### ISSUE THREAD

**Issue by HWNHJJ** [jindongwang/transferlearning#198]
在DSNA中，仅训练一个epoch,就能在目标域就能达到100%的准确率是为什么呢
amazon set: Average loss: 0.0000, Accuracy: 2817/2817 (100.00%)
source: webcam to target: amazon max correct: 2817 max accuracy 100.00%

**Comment by jindongwang** [comment]
#182

**Comment by HWNHJJ** [comment]
> #182

好的，谢谢王博士
