### ISSUE TITLE
TCA里get_L()超内存了

### ISSUE THREAD

**Issue by yfiua** [jindongwang/transferlearning#2]
维度高了容易超内存，其实就是几个简单的变换，没必要用full矩阵

**Comment by jindongwang** [comment]
感谢提醒！可能是我测试的数据比较少，没有注意到。Python版本我稍后再更新吧，目前基本不维护了，主要转向了Matlab。Matlab比Python要快很多。

**Comment by yfiua** [comment]
客气啊 我最近也在看迁移学习，刚刚打算抄你点代码呢，以后多交流
