### ISSUE TITLE
建议楼主仔细看看文章实验细节，尤其是office-caltech等库

### ISSUE THREAD

**Issue by jian-liang** [jindongwang/transferlearning#20]
office-caltech数据库的协议比较多，有的是full source  data有的是sampling source data,千万不要胡乱比较

**Comment by jindongwang** [comment]
1. 并没有胡乱比较。我找的时候，都是基于full-training的，因为这块用的最多
2. 大多数结果都有出处，真用的时候，肯定是要看出处的

**Comment by jian-liang** [comment]
https://github.com/jindongwang/transferlearning/blob/master/doc/benchmark.md  这个里面decaf出处这个文章是有问题的，里面一些对比方法好多是基于sampling source的，还是不要乱传播这些有问题的实验结果比较好。
