### ISSUE TITLE
I'm a rookie of Transfer Learning, could you give me some suggest.

### ISSUE THREAD

**Issue by timpc0526** [jindongwang/transferlearning#201]
Hello,

 I'm a rookie of Transfer Learning, I want to learn more but I don't have any idea which paper I should read?
Can you recommend papers for me?

Thx

**Comment by jindongwang** [comment]
Hi, there are so many papers in this area. I think you can refer to the papers in the code page of this repo (https://github.com/jindongwang/transferlearning/tree/master/code), maybe start with TCA, CORAL, DDC, MEDA, BDA, EasyTL, SCA,  DANN, DSN.

**Comment by Bobtaotao** [comment]
您好，这不是应该是alexnet么，为什么程序使用得是resnet

**Comment by jindongwang** [comment]
@Bobtaotao Alexnet, VGG, ResNet... are all backbone networks that you can change them freely.

**Comment by Bobtaotao** [comment]
不好意思，我没表述清楚，我看的是您的DAN的程序，看到论文中使用的是alexnet，但是看到您的DAN程序使用的是resnet

**Comment by Bobtaotao** [comment]
您好，不好意思我没表述清楚，我看的是您的DAN的程序，DAN论文中使用的是Alexnet，但是看到您程序中使用的resnet

**Comment by jindongwang** [comment]
我已经说过了呀，你愿意用啥都可以，就是个骨干网络

________________________________
发件人: 涛 <notifications@github.com>
发送时间: Monday, October 26, 2020 8:42:38 PM
收件人: jindongwang/transferlearning <transferlearning@noreply.github.com>
抄送: Jindong Wang <jindongwang@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [jindongwang/transferlearning] I'm a rookie of Transfer Learning, could you give me some suggest. (#201)


您好，不好意思我没表述清楚，我看的是您的DAN的程序，DAN论文中使用的是Alexnet，但是看到您程序中使用的resnet

―

**Comment by Bobtaotao** [comment]
好的，谢谢您

**Comment by Syw-cug** [comment]
Hello, I would like to ask when will the L2M code be open source

**Comment by Syw-cug** [comment]
Hello, I would like to ask when will the L2M code be open source？

**Comment by jindongwang** [comment]
@Syw-cug Thanks for your interest in this work. After finalizing some details, we plan to submit L2M to a future conference (maybe CVPR). Since this work is mostly done by a former master student in my PhD lab who is now in Alibaba (996), I must take more time to finish it. When everything is ready, I will publish the code and sincerely let you know.

**Comment by Syw-cug** [comment]
@jindongwang OK, thank you very much for your reply.

**Comment by zbw66** [comment]
in Fine-tune using AlexNet and ResNeT .  I  got some problems:FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'Your dataset folder\\webcam' (my foldset is same with your foldset)  .   Looking forward to your reply

**Comment by zbw66** [comment]
the complete error message:
Traceback (most recent call last):
  File "D:/PyCharm 2020.1.3/Pytorch/finetune_office31.py", line 150, in <module>
    dataloaders['tar'] = data_loader.load_data(root_dir, domain['tar'], BATCH_SIZE['tar'], 'tar')
  File "D:\PyCharm 2020.1.3\Pytorch\data_loader.py", line 21, in load_data
    data = datasets.ImageFolder(root=os.path.join(root_path, dir), transform=transform_dict[phase])
  File "C:\ProgramData\Miniconda3\envs\PyCharm 2020.1.3\lib\site-packages\torchvision\datasets\folder.py", line 229, in __init__
    is_valid_file=is_valid_file)
  File "C:\ProgramData\Miniconda3\envs\PyCharm 2020.1.3\lib\site-packages\torchvision\datasets\folder.py", line 108, in __init__
    classes, class_to_idx = self._find_classes(self.root)
  File "C:\ProgramData\Miniconda3\envs\PyCharm 2020.1.3\lib\site-packages\torchvision\datasets\folder.py", line 137, in _find_classes
    classes = [d.name for d in os.scandir(dir) if d.is_dir()]
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'Your dataset folder\\webcam'

**Comment by raying777** [comment]
@zbw66 change this "Your dataset folder" to your folder in "parser.add_argument('--data'........)"

**Comment by zbw66** [comment]
> @zbw 66将此“数据集文件夹”更改为“parser.add_参数(‘--data’.)”中的文件夹。

Bingo  ths HAHAHA

**Comment by zbw66** [comment]
@raying777  Bingo THX HAHAHA

**Comment by Syw-cug** [comment]
Hello, I have some doubts about the training process of domain adaptive network. When I train a domain adaptive network (the target domain dataset has labels), I find that the test accuracy of each epoch in the target domain dataset fluctuates greatly. When we apply the domain adaptive network to a dataset without labels, when should we save our model, or how to find the epoch with the highest accuracy. Looking forward to your reply.

**Comment by jindongwang** [comment]
@Syw-cug You should save the model with highest test accuracy.
