### ISSUE TITLE
关于TCA的问题

### ISSUE THREAD

**Issue by BluOo210** [jindongwang/transferlearning#203]
您好，我最近刚刚开始接触迁移学习，想尝试用python跑一下TCA的代码，报错
Xs, Ys, Xt, Yt = src_domain['feas'], src_domain['label'], tar_domain['feas'], tar_domain['label']
KeyError: 'feas'

请问这个具体是什么原因呢？

**Comment by jindongwang** [comment]
这个问题你可以看一下load进来的matlab文件有哪些字段。可能是后来的字段匹配不上了，不再叫feas，而是叫feat之类的，你打出来能看到
