### ISSUE TITLE
MNIST+USPS数据集的label问题

### ISSUE THREAD

**Issue by onlyonewater** [jindongwang/transferlearning#206]
我下载了MNIST+USPS的数据集，发现MNIST的label是从1-10的。
![image](https://user-images.githubusercontent.com/41667733/103481129-aedd0e80-4e13-11eb-845c-07d8d08f423d.png)

**Comment by jindongwang** [comment]
你应该是想问为什么没有0类，反而有10类吧？
这个数据是matlab格式，matlab分类器默认是从1开始，所以相应的每个label都加了1。

**Comment by onlyonewater** [comment]
@jindongwang ,非常感谢您的回复，我明白了，多谢啦
