### ISSUE TITLE
关于ADDA复现的问题

### ISSUE THREAD

**Issue by onlyonewater** [jindongwang/transferlearning#207]
Hi, 王博，你好，想问一下，您有复现过ADDA的代码吗？我复现了一下，发现mnist迁移到usps后，最好的结果是84.5，离文章中报告的89.4还差接近5个点，从usps迁移到mnist后，最好的结果是63.4，离文章中报告的90，还差很多很多，想问一下，您可以达到文章中报告的精度吗？

**Comment by jindongwang** [comment]
@onlyonewater 我没有复现过ADDA，因为当时看了github上有很多ADDA浮现的repo了: https://github.com/search?q=adda

**Comment by onlyonewater** [comment]
嗯，我也看到了，但是综合了一下这些repo，发现还是达不到文章中所说的精度，而且这些repo本身就很很多issue没有回答

**Comment by jindongwang** [comment]
都是比较老的工作了，所以可能作者也基本联系不上了

**Comment by onlyonewater** [comment]
行吧
