### ISSUE TITLE
Some Link doesn't work

### ISSUE THREAD

**Issue by davidpqc1231** [jindongwang/transferlearning#209]
大佬您好，ImageCLEF的image数据的BaiduYun链接被吞了，能麻烦您更新一下吗？拜托了！！

**Comment by jindongwang** [comment]
你说的是哪个地方的链接呀，能不能指出具体位置方便我稍后修复？如果你着急用的话，可以在下面这个链接下载imageclef的数据：
https://transferlearningdrive.blob.core.windows.net/teamdrive/dataset/image_CLEF.zip

**Comment by davidpqc1231** [comment]
谢谢大佬，万分感谢!!!!

ImageCLEF
This is a dataset from ImageCLEF 2014 challenge.

Download the ImageCLEF dataset #这个地方链接用不了了，显示不存在

Download Image-CLEF ResNet-50 pretrained features | Download from MEGA
