### ISSUE TITLE
关于DaNN的benchmark

### ISSUE THREAD

**Issue by vincentgc** [jindongwang/transferlearning#21]
DaNN原文实验是在office10上做的，所以benchmark的数据应该是office10的，不应该在office31里（或许应该标注一下？）

**Comment by jindongwang** [comment]
这个结果是从CORAL文章里抄来的

**Comment by vincentgc** [comment]
@jindongwang 我刚看了下原文，数据确实是原文的数据，但是实验是在office10上做的，不是office31。

**Comment by jindongwang** [comment]
目前在Office10上没有写DaNN，可以加上。
我现在写的是CORAL文章里用DaNN在Office31实验的结果。

**Comment by vincentgc** [comment]
@jindongwang 我感觉coral就是图省事直接把DaNN的结果抄上去了 不然在31上跑也不可能和在10上跑结出来一样的结果……coral里关于DaNN的结果和DDC里的就不一样，我个人觉得ddc里那个比较靠谱，像是在office31上跑出来的。

**Comment by jindongwang** [comment]
这个就不清楚了呀，我只是按照原文抄。。话说DDC的AlexNet结果我用pytorch都复现不出来。。。
