### ISSUE TITLE
Domain size imbalance problem

### ISSUE THREAD

**Issue by k0ngyiji** [jindongwang/transferlearning#210]
Happy New Year !

In DAN, Long et al.  point out that the difference in domain sizes causes domain shift, and recent years this problem seems not be well handled.  I think this problem may be related to the class-imbalance problem.  Is class-imbalance problem part of  domain size imbalance problem? or the opposite? or they are completely different problems?

**Comment by jindongwang** [comment]
Generally speaking, class imbalance refers to the different class proportions of each class in two domains.  I'm not sure whether it has anything to do with the domain size. You can refer to my previous work ``balanced distribution adaptation'' for how to handle this problem.

**Comment by k0ngyiji** [comment]
That's helpful, thank you for your advice !
