### ISSUE TITLE
关于DAN中平衡loss的系数

### ISSUE THREAD

**Issue by sowilox** [jindongwang/transferlearning#211]
王博您好，最近刚开始学习迁移学习，您的这个仓库对我帮助很大。
有一个不解的小问题，您在DAN的代码中用 lambd = (2 / (1 + math.exp(-10 * i / iteration)) - 1)这个系数去平衡两个loss，请问为什么要采用这个式子呢？

**Comment by jindongwang** [comment]
这个没有为什么，就是一个动态调整系数的trick...最初是在DANN的文章里提出来的

**Comment by sowilox** [comment]
那行，那我再去翻翻DANN的文章，谢谢您抽空回复。
