### ISSUE TITLE
为什么我的数据用meda分类不收敛，东哥知道一般是哪出问题了吗？

### ISSUE THREAD

**Issue by pyg-csc** [jindongwang/transferlearning#214]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by jindongwang** [comment]
这个问题无法回答，信息太少。可以调调参试试。

**Comment by pyg-csc** [comment]
东哥你好，不收敛的问题我已经查明原因。我的数据为雷达型号数据，不收敛的原因是该数据加的噪声过大，导致精确度在相差较大的值之间反复波动。后来叠加了小的噪声后，数据输入meda后取得了收敛的结果。感谢东哥的关心！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jindong ***@***.***&gt;; 
发送时间: 2021年5月11日(星期二) 晚上9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jindongwang/transferlearning] 为什么我的数据用meda分类不收敛，东哥知道一般是哪出问题了吗？ (#214)





 
@pyg-csc 你的问题解决了吗？

**Comment by jindongwang** [comment]
很高兴看到MEDA对你的实验有帮助！
