### ISSUE TITLE
Some questions about running errors and data set creation

### ISSUE THREAD

**Issue by sunshining-bit** [jindongwang/transferlearning#217]
**Describe the bug**
  File "G:\Anaconda3\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: Service Unavailable

**To Reproduce**
Where is this bug happen?
On the way to run main.py, after the steps of 
  File "G:\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
Then this problem happens.

And I also want to know how the downloaded MNIST_M compressed package should be placed in the program directory after decompression. Is it to create a dataset folder first, then create a new folder named "mkdir dataset" to place the automatically downloaded MNIST dataset, and then copy the decompressed MNIST_M dataset directly into the "dataset" folder?

**Comment by jindongwang** [comment]
You should download the dataset on your own and the place it in the folder. It's simple.

**Comment by sunshining-bit** [comment]
Thank you for replying to me. Actually, I have already downloaded the data package, but this problem still occurs:


raise HTTPError(req.full_url, code, msg, hdrs, fp)


HTTPError: Service Unavailable



The picture below is the stacking location of the data file I downloaded. Is there any error?
Among them, the mnist folder is automatically generated.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jindongwang/transferlearning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月29日(星期一) 晚上6:19
***@***.***&gt;;
抄送:&nbsp;"○冰o激ゞ凌 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jindongwang/transferlearning] Some questions about running errors and data set creation (#217)





 
You should download the dataset on your own and the place it in the folder. It's simple.

**Comment by jindongwang** [comment]
I think it's because of the network setting in your own computer. `main.py` does not involve any download, except for the MNIST download in `data_loader.py`: https://github.com/jindongwang/transferlearning/blob/master/code/deep/DANN(RevGrad)/data_loader.py#L19
Try search this: https://www.google.com.hk/search?q=python%20http%20servce%20unavailable

**Comment by sunshining-bit** [comment]
谢谢东哥。
I will try it first.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jindongwang/transferlearning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 上午9:35
***@***.***&gt;;
抄送:&nbsp;"○冰o激ゞ凌 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [jindongwang/transferlearning] Some questions about running errors and data set creation (#217)





 
I think it's because of the network setting in your own computer. main.py does not involve any download, except for the MNIST download in data_loader.py: https://github.com/jindongwang/transferlearning/blob/master/code/deep/DANN(RevGrad)/data_loader.py#L19
 Try search this: https://www.google.com.hk/search?q=python%20http%20servce%20unavailable
