### ISSUE TITLE
Permutations used for reported features

### ISSUE THREAD

**Issue by serbanstan** [jindongwang/transferlearning#222]
Hello!

Are the permutations used in the feature reporting from /data/ also available? For example, for office-31, webcam_amazon and dslr_amazon have misaligned labels.

If not, are data augmentation techniques used when training the resnet50 encoders? Asking specifically for the office datasets. 

Thank you!

**Comment by jindongwang** [comment]
Hi @serbanstan , the data for generating ResNet-50 features are shuffled. And unfortunately, I can't provide you with the original alignments. You can run the feature extractor code in this repo to generate your own features. Just remember no permutations or other things involved.
