### ISSUE TITLE
东哥，想问下有多GPU版本的计算MMD Loss程序吗

### ISSUE THREAD

**Issue by ghost** [jindongwang/transferlearning#223]
我的任务占GPU比较多，单卡跑起来，计算MMD Loss就会显存爆炸，多卡并行又是将数据沿着Batch维度切分到不同GPU上计算，比如我用四卡，batch size为8这样，多卡并行的话，算出来的是四个实际上batch size为2的MMD Loss。想问下东哥知不知道在多GPU并行的情况下如何计算MMD Loss？

**Comment by jindongwang** [comment]
这是一个好问题。容我想一下做一些实验再回复你。

**Comment by jindongwang** [comment]
多GPU的MMD计算，只能是分割到不同的显卡上计算，然后再取平均。这个是没法避免的。我们在https://github.com/jindongwang/transferlearning/tree/master/code/ASR/CMatch 项目上也用了8个GPU来计算MMD，实际效果并没受到影响。因为本身mini-batch MMD计算就是在逼近这个分布，所以只能是分开来算。

**Comment by jindongwang** [comment]
@grdtsinghua 你的问题解决了吗？

**Comment by B-Soul** [comment]
嗯嗯好的 多谢东哥 那我就分割到不同显卡上去算吧
