### ISSUE TITLE
traditional方法的main测试接口

### ISSUE THREAD

**Issue by Sir-Death** [jindongwang/transferlearning#225]
你好，在traditional的代码中的很多方法只提供了一个类，并没有相关的main入口，我该如何使用这些方法，谢谢

**Comment by jindongwang** [comment]
我看了一下，这些方法没有提供main函数：
![image](https://user-images.githubusercontent.com/6158206/116514228-51f2f000-a8fd-11eb-83c7-f14b4bdd018d.png)

使用方法与文件夹中的方法大体一样，并且类中也写着参数的含义，所以对于python文件，你可以参考TCA BDA等方法的设定；对于matlab文件，你可以参考MEDA方法。大体上都是一样的。
另外还需要注意的就是，在使用这些方法之前最好先稍微了解一下方法是怎么做的，这样你才能有针对性地传参数。
后续有时间会把其他方法补全测试。

**Comment by Sir-Death** [comment]
好的，非常感谢，想先了解一下经典的方法再看新的
