### ISSUE TITLE
I'm confused that if the source and target are different in number, How to change the code to adapt this changes?

### ISSUE THREAD

**Issue by wanghui-cloud** [jindongwang/transferlearning#229]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by zzzzkkkk90** [comment]
您好，我也有同样的问题，如果源域和目标域的特征维度不一致，比如源域20维，目标域40维，这种情况下代码不能运行。这个问题该怎么解决呢？谢谢！

**Comment by jindongwang** [comment]
Domain adaptation定义就是这样的。你可以降维成一样的来使用。
