### ISSUE TITLE
Unable to reappear Accuracy of CORAL on Office+Caltech(Surf) dataset

### ISSUE THREAD

**Issue by Zheng-ZhiHao** [jindongwang/transferlearning#233]
As the table shown, CORAL can perform well on Office+Caltech(Surf) dataset and achieve about 48.8% average accuracy.

![图片](https://user-images.githubusercontent.com/60505198/119793423-287fb100-bf09-11eb-8c45-2b8a31696158.png)

However, after running CORAL.py under file folder 'code/traditional' repeatedly. The result was terrible, especially under cases 'c-w'/'c-d'/'c-a' , compared to the benchmark shown above

![图片](https://user-images.githubusercontent.com/60505198/119795596-33d3dc00-bf0b-11eb-85d4-3240e83a970d.png)

I only edited a little part of the code.

![图片](https://user-images.githubusercontent.com/60505198/119795919-7eedef00-bf0b-11eb-8104-8943eff27aba.png)

Are there any trick when reappearing it? Or I misunderstood the meaning of that table of benchmark?

**Comment by jindongwang** [comment]
Hi @Zheng-ZhiHao, the results of CORAL are copied from the CORAL paper (Return of Frustratingly Easy Domain Adaptation, table 3). I also can't reproduce his results using Python. You can try the CORAL_SVM.m matlab code.

**Comment by Zheng-ZhiHao** [comment]
Thanks for your patience, Dr. Wang




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jindong ***@***.***&gt;; 
发送时间: 2021年6月1日(星期二) 上午10:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jindongwang/transferlearning] Unable to reappear Accuracy of CORAL on Office+Caltech(Surf) dataset (#233)





 
Hi @Zheng-ZhiHao, the results of CORAL are copied from the CORAL paper (Return of Frustratingly Easy Domain Adaptation, table 3). I also can't reproduce his results using Python. You can try the CORAL_SVM.m matlab code.

**Comment by jindongwang** [comment]
@Zheng-ZhiHao Problem solved?

**Comment by Zheng-ZhiHao** [comment]
> 
> 
> @Zheng-ZhiHao Problem solved?

Yes, thanks for your guidance.

**Comment by jindongwang** [comment]
What's the conclusion?
