### ISSUE TITLE
关于TSNE可视化的一些问题

### ISSUE THREAD

**Issue by Sir-Death** [jindongwang/transferlearning#239]
您好，我想问一下，如果画TSNE可视化的图，是利用经过分类器前的那个特征还是经过分类器后的那个特征，再利用tsne降维可视化，我看了您utils里feature_vis的代码，但对于这个数据的处理还不是很清楚，请问有其他论文里的可视化代码可以分享吗，非常感谢

**Comment by jindongwang** [comment]
用的是经过分类器前的特征进行的。

**Comment by Sir-Death** [comment]
我用office_caltech surf特征，在matlab代码中得到经过分类器前的特征，但可视化出来的结果不像其他论文里的可视化图类分隔的很清晰，而是都混在一起，请问这跟surf特征有关系吗，还是我其他地方操作有错误

**Comment by jindongwang** [comment]
surf特征可能不太行，所以整体效果比较差了
