### ISSUE TITLE
您好，我在调DAAN程序时

### ISSUE THREAD

**Issue by taobob001** [jindongwang/transferlearning#242]
您好，我在调DAAN程序时，改了epoch，精确率是逐渐递增，最后稳定在100%，您有遇到过这种错误么？

**Comment by jindongwang** [comment]
把你的log贴出来看看吧。如果换所有任务都是100的话，可能是你的图片文件夹错了，里面还有一层images文件夹，检查一下

**Comment by jindongwang** [comment]
@taobob001 请问你的问题解决了吗？

**Comment by taobob001** [comment]
您好，问题解决了但是又出现新的错误，log不能显示

**Comment by taobob001** [comment]
您好，问题解决了，但是又出现新的错误，log日志不能记录显示

**Comment by taobob001** [comment]
您好，问题解决了，但是又出现新的错误，log日志不能记录显示
