### ISSUE TITLE
在复现的过程中，数据集用的是office-home，max_epoch调整为100，每次epoch所用的时间会不断增加最后崩溃，![image-20210712163828574](C:\Users\27537\AppData\Roaming\Typora\typora-user-images\image-20210712163828574.png)貌似跑不过20轮就崩了，想问问什么原因😂

### ISSUE THREAD

**Issue by PPJ001** [jindongwang/transferlearning#247]

**Comment by PPJ001** [comment]
在复现的过程中，数据集用的是office-home，max_epoch调整为100，每次epoch所用的时间会不断增加最后崩溃，貌似跑不过20轮就崩了，想问问什么原因😂
![image-20210712163828574](https://user-images.githubusercontent.com/43403840/125259239-b4bb2b80-e331-11eb-86b9-8b9d7ab6857f.png)

**Comment by jindongwang** [comment]
请问你复现的是哪个任务、哪个算法？用默认的参数会有报错吗？然后，你的pytorch和torchvision是多少？

**Comment by PPJ001** [comment]
pytorch：1.8.1+cu102
torchvision：0.9.1+cu102
复现的任务是：DG + office-home
算法用的是：MLDG
当时直接跑的时候会出现这个错误：**ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm)**；然后我将Dataloader中的num_workers设置为0了程序就可以正常跑起来了。

**Comment by jindongwang** [comment]
能跑起来就可以，可能是机器配置问题，num_workers也偶尔会报错。

**Comment by PPJ001** [comment]
但是epoch跑不到20就会崩掉，显卡是2080Ti是性能不够吗😂

**Comment by jindongwang** [comment]
@lw0517 来看一下

**Comment by lw0517** [comment]
请问你目标域设定的是哪一个？office-home的Real World有改成Real_World吗？

目前我们在服务器上无法复现你的问题，我们在3090中对代码进行了测试。
![image](https://user-images.githubusercontent.com/31000480/125274553-a9bbc780-e340-11eb-8717-6c178740f074.png)
![image](https://user-images.githubusercontent.com/31000480/125274591-b2140280-e340-11eb-8c71-2076123978fc.png)
每个epoch稳定在100s左右。
![image](https://user-images.githubusercontent.com/31000480/125274635-bcce9780-e340-11eb-8e8c-ad4e74378ee5.png)
显卡使用稳定在3GB左右。
![image](https://user-images.githubusercontent.com/31000480/125274716-cfe16780-e340-11eb-8741-85043e9fd1b2.png)
![image](https://user-images.githubusercontent.com/31000480/125274736-d53eb200-e340-11eb-94e8-4bfe08aa4129.png)
这个是我们刚刚测试时的环境。

**Comment by houwenxin** [comment]
> 请问你目标域设定的是哪一个？office-home的Real World有改成Real_World吗？
> 
> 目前我们在服务器上无法复现你的问题，我们在3090中对代码进行了测试。
> ![image](https://user-images.githubusercontent.com/31000480/125274553-a9bbc780-e340-11eb-8717-6c178740f074.png)
> ![image](https://user-images.githubusercontent.com/31000480/125274591-b2140280-e340-11eb-8c71-2076123978fc.png)
> 每个epoch稳定在100s左右。
> ![image](https://user-images.githubusercontent.com/31000480/125274635-bcce9780-e340-11eb-8e8c-ad4e74378ee5.png)
> 显卡使用稳定在3GB左右。
> ![image](https://user-images.githubusercontent.com/31000480/125274716-cfe16780-e340-11eb-8741-85043e9fd1b2.png)
> ![image](https://user-images.githubusercontent.com/31000480/125274736-d53eb200-e340-11eb-94e8-4bfe08aa4129.png)
> 这个是我们刚刚测试时的环境。


我觉得题主可能是把这个total cost time比较容易理解为一个epoch训练的时间了。。。这里的确比较容易误解

**Comment by PPJ001** [comment]
office-home的Real World改成了Real_World。好像是理解错了😂   请问一下在哪里查看目标域设定成了什么？我再尝试尝试

**Comment by PPJ001** [comment]
epoch稳定在200s左右，显卡使用也是在3G左右，但是运行是在服务器的docker中

**Comment by lw0517** [comment]
![image](https://user-images.githubusercontent.com/31000480/125281063-5f3e4900-e348-11eb-908e-ee32e1c3894c.png)
这里的test_envs对应的就是你选择的目标域，我们目前无法复现你的问题，抱歉

**Comment by PPJ001** [comment]
十分感谢了！我自己再尝试尝试

**Comment by PPJ001** [comment]
test_envs是从0开始的吧。这个对应的结果是不是就是红色圈出来的这个呢？
![Uploading result.JPG…]()

**Comment by lw0517** [comment]
![image](https://user-images.githubusercontent.com/31000480/125284366-f35ddf80-e34b-11eb-9f5f-d08ebdf3f0e6.png)
0对应的是Art，也就是A。2对应的是Product也就是P。上面我们测试的脚本对应的就是P

**Comment by PPJ001** [comment]
好的非常感谢！解答太棒了！
