### ISSUE TITLE
关于低版本的问题

### ISSUE THREAD

**Issue by PPJ001** [jindongwang/transferlearning#249]
如果服务器的版本比较低，
torch版本：1.7.1+cu101
torchvision版本：0.8.2+cu101
会有什么问题吗？

**Comment by jindongwang** [comment]
@PPJ001 不清楚，你可以自己试一下。我们写的版本号只是自己用的，原则上应该不要特别老的版本，都能用的。

**Comment by PPJ001** [comment]
好的谢谢老师！换了一台服务器代码已经跑通了。
