### ISSUE TITLE
添加几篇新的论文

### ISSUE THREAD

**Issue by GISRS** [jindongwang/transferlearning#25]
深度学习用在语义分割上面的
FCNs in the Wild: Pixel-level Adversarial and Constraint-based Adaptation
Curriculum domain adaptation for semantic segmentation of urban scenes
No More Discrimination: Cross City Adaptation of Road Scene Segmenters
Learning to Adapt Structured Output Space for Semantic Segmentation
Fully  Convolutional Adaptation Networks for Semantic Segmentation
这些方法好多都是去年ICCV visDA 分割任务排名靠前的方法。
还有王老师能不能利用您的影响力建一个迁移学习的群组？。。感觉现在做这个越来越多。。大家都没一个讨论的地方。 麻烦了

**Comment by jindongwang** [comment]
@GISRS Good! 
Can you update on the readme.md using pull request?
