### ISSUE TITLE
关于deep_transfer_tutorial.ipynb运行时出现的问题

### ISSUE THREAD

**Issue by CYDping** [jindongwang/transferlearning#250]
王老师，我在运行到--load the data using the above function to test it --时，下面那个代码块总是会报错找不到文件。
（0）这是我的文件夹放置，如图：
![q2](https://user-images.githubusercontent.com/86303578/126497498-149de686-3572-44c2-bc4a-371723550ac0.png)

（1）当按照源程序时，程序如下图：
![q1](https://user-images.githubusercontent.com/86303578/126498076-72b4eb5c-96f5-49aa-84ac-5c63883afff5.png)
![q3](https://user-images.githubusercontent.com/86303578/126498143-456ab16d-6d9c-4342-98a6-3e57e8071012.png)
（2）当对文件夹路径尝试修改，如图：
![q4](https://user-images.githubusercontent.com/86303578/126498304-cd5a2332-f4fe-46a2-8949-6bd3d85c1aa0.png)
![q5](https://user-images.githubusercontent.com/86303578/126498308-63e3af3c-a2aa-4282-8174-cd04bc9d1f02.png)

最后都报错找不到类文件，请问这种情况怎么解决呀？

**Comment by jindongwang** [comment]
@CYDping 这个应该比较简单的问题，我也没法帮你调试，你是直接用的你本地的数据集，还是运行了上面的数据集下载？如果直接运行这个脚本应该是不会有问题的；如果是你自己的数据，那可能是windows下的路径有bug，你可以试试把\\换成/，等等。这个和windows有关，你多试一下。

**Comment by jindongwang** [comment]
@CYDping 请问你的问题解决了吗？

**Comment by CYDping** [comment]
没有...因为可能是anaconda安装有问题，所以jupter修改目录不成功，文件目录就总是找不到。ps:不知道为什么手机邮箱一周前的回复在github上没有显示...
