### ISSUE TITLE
请问我想对已经训练好的模型进行迁移学习，可以直接使用里面的DA库吗

### ISSUE THREAD

**Issue by zzyycc7** [jindongwang/transferlearning#251]

**Comment by houwenxin** [comment]
你好，自定义模型的话，在backbones.py里模仿已有模型定义自己的backbone并加入get_backbone函数，然后在config文件里设置自己的backbone即可

**Comment by zzyycc7** [comment]
谢谢指导，刚入门迁移学习，我先学着用用
