### ISSUE TITLE
训练时，test acc总是为0

### ISSUE THREAD

**Issue by zzyycc7** [jindongwang/transferlearning#252]
我想用LFW数据库作为源域，自己的人脸库作为目标域，使用迁移学习训练一个人脸识别模型,但是test acc一直是0.

**Comment by jindongwang** [comment]
@zzyycc7 不迁移时精度多少？

**Comment by zzyycc7** [comment]
不迁移训练到了80%多

**Comment by jindongwang** [comment]
你用的是什么算法、有调参数吗？请提供细节

**Comment by zzyycc7** [comment]
迁移学习DA库的算法都试过，训练的时候acc总是0。不使用迁移学习训练的时候是用的arcface。没有调过参数

**Comment by jindongwang** [comment]
说明这些方法可能不适合你的问题吧，或者你用的时候有问题，你可以试试调一下参数看看，按理说不应该这么差的，至少也和没迁移一样才对。

**Comment by houwenxin** [comment]
你好，不迁移指的是transfer_loss_weight设置为0吗？如果不是的话，建议检查一下输入输出有没有问题，尤其是数据集的路径，一般是不会为0的

**Comment by zzyycc7** [comment]
你好，我试过其他数据集。office31是可以正常做迁移学习的，test_acc也是正常的。我想会不会是因为源域和目标域的标签不对等导致的？请问源域和目标域的标签需要完全一致吗？

**Comment by houwenxin** [comment]
> 请问源域和目标域的标签需要完全一致吗？

标签需要是一致的，如果标签不对应就可以解释acc为什么是0了。。。

**Comment by Suhapelo** [comment]
> > 请问源域和目标域的标签需要完全一致吗？
> 
> 标签需要是一致的，如果标签不对应就可以解释acc为什么是0了。。。

请问目标域的label可以是源域label的子集吗？（类别数少于源域）

**Comment by luhaifeng19947** [comment]
我已经收到您的邮件，会尽快处理。

**Comment by wlh-coconut** [comment]
你好，这是贺雯丽的自动回复，您的信息已经收到。祝身体健康，万事如意！                                                      贺雯丽
