### ISSUE TITLE
What's the default parameters of source-only?

### ISSUE THREAD

**Issue by yfzhang114** [jindongwang/transferlearning#261]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by jindongwang** [comment]
@yfzhang114 The default parameter of source-only will be using the DAN config, and set its transfer-loss weight to 0. That's all.

**Comment by yfzhang114** [comment]
> @yfzhang114 The default parameter of source-only will be using the DAN config, and set its transfer-loss weight to 0. That's all.

Thanks!
