### ISSUE TITLE
GroupDRO使用示例

### ISSUE THREAD

**Issue by zwx8981** [jindongwang/transferlearning#263]
感谢你们的贡献，目前的DeepDG中似乎没有包含GroupDRO的使用script，GroupDRO的超参设置跟其他方法似乎不太一样，能否提供一个简单的例子呢，谢谢！

**Comment by jindongwang** [comment]
已更新代码，你的问题已得到解答：https://github.com/jindongwang/transferlearning/blob/master/code/DeepDG/scripts/run.sh#L18

**Comment by zwx8981** [comment]
太感谢了
