### ISSUE TITLE
About the DG training epoch.

### ISSUE THREAD

**Issue by WHUzhusihan96** [jindongwang/transferlearning#267]
Thanks for you sharing.

The training epoch you set in the scripts is 3 for those tasks. Is it too low to get the final results?
What is the appropriate training epoch setting?

**Comment by jindongwang** [comment]
@lw0517

**Comment by lw0517** [comment]
The script is a example. 150 epochs are enough to get the final results.

**Comment by WHUzhusihan96** [comment]
OK ,thanks
