### ISSUE TITLE
Why is the calculated value of proxy_a_distance a fixed value?

### ISSUE THREAD

**Issue by yangcong356** [jindongwang/transferlearning#268]
When I use the code in proxy_a_distance.py to calculate the features extracted from the last layer of the network, the output result is always 0.660332541567696.

![image](https://user-images.githubusercontent.com/39213788/134112101-36f2cf94-cf02-4d4b-93e4-5115f2ae069f.png)

**Comment by jindongwang** [comment]
If your features are fixed, then the results will be the same.

**Comment by yangcong356** [comment]
> If your features are fixed, then the results will be the same.

When I use the original data of the target domain and the source domain to calculate, the distance of A-distance is also 0.6603.
![image](https://user-images.githubusercontent.com/39213788/134274613-78767377-63d1-4fd4-9192-d1973188dfbe.png)

**Comment by jindongwang** [comment]
This A-distance code uses grid search to search the best C in SVM classifier, thus you can get the best results. If the value stays the same, maybe your features are not getting much better.
You can try a simplified version of A-distance in here which uses a fixed C value, then you can get different results: https://github.com/jindongwang/transferlearning/blob/master/code/traditional/BDA/BDA.py#L36

**Comment by yangcong356** [comment]
> This A-distance code uses grid search to search the best C in SVM classifier, thus you can get the best results. If the value stays the same, maybe your features are not getting much better.
> You can try a simplified version of A-distance in here which uses a fixed C value, then you can get different results: https://github.com/jindongwang/transferlearning/blob/master/code/traditional/BDA/BDA.py#L36

Thank you for your help! I will try again.
