### ISSUE TITLE
询问EasyTL跑office-caltech数据集为什么结果很差

### ISSUE THREAD

**Issue by mr6737** [jindongwang/transferlearning#270]
王老师您好，我跑了您提供的python版本的EasyTL代码。用的demo_office_caltech.py  导入的您提供的office-caltech数据集，但不知为何跑出来的结果十分差，求解答！
结果如下：
EasyTL(c) Acc: 23.1 % || EasyTL Acc: 16.3 %
EasyTL(c) AVG Acc: 14.0 %
EasyTL AVG Acc: 14.6 %

下载的数据集名称分别为：
amazon_surf_10.mat
caltech_surf_10.mat
dslr_surf_10.mat
webcam_surf_10.mat

我仅改动了数据集导入路径，并根据格式把fts改为feas，把labels改为label，其余未动：
if __name__ == "__main__":
    
    # datadir = r"D:\Datasets\EasyTL\surf"
    datadir = r"D:\pyEasyTL\data\surf"
    #str_domain = [ 'Caltech10', 'amazon', 'webcam', 'dslr' ]
    str_domain = ['caltech', 'amazon', 'webcam', 'dslr']
    list_acc = []
    
    for i in range(len(str_domain)):
        for j in range(len(str_domain)):
            if i == j:
                continue
            
            print("{} - {}".format(str_domain[i], str_domain[j]))
            
            #mat1 = scipy.io.loadmat(datadir + "/{}_SURF_L10.mat".format(str_domain[i]))
            mat1 = scipy.io.loadmat(datadir + "/{}_surf_10.mat".format(str_domain[i]))
            #Xs = mat1["fts"]
            Xs = mat1["feas"]
            #Ys = mat1["labels"]
            Ys = mat1["label"]
            
            mat2 = scipy.io.loadmat(datadir + "/{}_surf_10.mat".format(str_domain[j]))
            Xt = mat2["feas"]
            Yt = mat2["label"]

**Comment by jindongwang** [comment]
这个问题没人遇到过，代码肯定是没问题的，之前有人还根据我们的matlab实现了python版本的代码，所以是一定能复现的。我猜测可能是输入的mat文件不太对，你是从哪里下载到的这些文件呢？

**Comment by mr6737** [comment]
> 这个问题没人遇到过，代码肯定是没问题的，之前有人还根据我们的matlab实现了python版本的代码，所以是一定能复现的。我猜测可能是输入的mat文件不太对，你是从哪里下载到的这些文件呢？

**Comment by mr6737** [comment]
pyEasyTL  code 也是在您仓库找的: https://github.com/jindongwang/transferlearning/tree/master/code/traditional/pyEasyTL

**Comment by mr6737** [comment]
好的 谢谢王老师解答！

**Comment by isCopyman** [comment]
> ，因此intra_align只能选择raw或者coral ma

老哥，你成功复现python版本的easyTL了吗
