### ISSUE TITLE
为什么跑出来的实验结果和所述的差距有点大

### ISSUE THREAD

**Issue by PPJ001** [jindongwang/transferlearning#271]
[王老师您好，我在复现DG中的RSC算法的时候发现无论如何也达不到所述的效果。我每个实验都跑了600epoch，每次都是挑选其中最好的结果最终结果为A：55.09%，C：42.43%，P：69.7%，R：72.62%。和所述的结果差距有点大，不知道是哪个地方出了问题😂。（如果是超参数设置的问题，老师可以公布一下超参数的设置吗？）

**Comment by jindongwang** [comment]
@lw0517

**Comment by lw0517** [comment]
可以试一下：
1.更新一下代码；
2.调整一下超参数：学习率lr=0.005；
'rsc_f_drop_factor','rsc_b_drop_factor'对于不同任务分别为:
A:0.3,0.1
C:0.1,0.1
P:0.3,0.1
R:0.1,0.1

**Comment by PPJ001** [comment]
其余方法的一些超参数也能提供一下吗？  我都尝试一下，谢谢老师😀

**Comment by lw0517** [comment]
学习率0.005或者0.001
DANN:
0.1,1,0.5,0.1
CORAL:
0.1,0.5,1,1
Mixup:
0.1,0.1,0.2,0.2

**Comment by wangyanhui666** [comment]
> 学习率0.005或者0.001 DANN: 0.1,1,0.5,0.1 CORAL: 0.1,0.5,1,1 Mixup: 0.1,0.1,0.2,0.2

请问DANN: 0.1,1,0.5,0.1
里面的数字分别对应哪些超参呢？

**Comment by lw0517** [comment]
DANN只有一个参数alpha，对应4个任务
