### ISSUE TITLE
王老师，运行adarnn代码出现错误

### ISSUE THREAD

**Issue by czkn** [jindongwang/transferlearning#279]
train_weather.py 465 <module>
main_transfer(args)

train_weather.py 376 main_transfer
pprint(loss, loss1)

UnboundLocalError:
local variable 'loss' referenced before assignment

**Comment by jindongwang** [comment]
请问你是直接运行的我们给的readme吗？那个我试了很多次不会出错。如果你自己修改了文件，那发生错误也正常

**Comment by czkn** [comment]
是的，老师，直接运行命令的，没有修改（数据集也下载了）
`python train_weather.py --model_name 'AdaRNN' --station 'Dongsi' --pre_epoch 40 --dw 0.5`

**Comment by jindongwang** [comment]
那不太可能出问题，你要检查一下你的torch环境是不是与readme里相同。

**Comment by czkn** [comment]
知道问题了，谢谢王老师！！！
