### ISSUE TITLE
question about CORAL_SVM.m

### ISSUE THREAD

**Issue by cliang18** [jindongwang/transferlearning#28]
Hi Jindong,

I really love your repo about the transfer learning! Just a question about the implement about CORAL method.

In CORAL_SVM line 22, I think Sim_Trn = trainset * M *  trainset' is used to compute the pre-computed kernel for the use of libsvm train. However, I think the transformed training data should be (trainset * M), thus the kernel should be (trainset*M) * (trainset*M)'. 

Am I missing anything?

**Comment by jindongwang** [comment]
@cliang18 Thank you for your comments! I will check it later!

**Comment by jindongwang** [comment]
@cliang18 Sorry for the late reply. I'm busy with job looking these days! The transformation in Line 22 is right. It is consistent with the original CORAL proof in the paper (section 3.1). Please refer to it.
