### ISSUE TITLE
`code/DeepDA/loss_funcs/adv.py `L#27: super class init error; super()调用错误

### ISSUE THREAD

**Issue by cantabile-kwok** [jindongwang/transferlearning#281]
In `code/DeepDA/loss_funcs/adv.py `L#27, there is 
```
super(AdversarialLoss, self).__init__(gamma=gamma, max_iter=max_iter, **kwargs)
```
But this class is now a subclass of nn.Module, which does not have such arguments of `__init__`.

I noticed that several days ago a commit has changed the parent class from LambdaSheduler to nn.Module, so the `super` call should be changed too. I got an `unexpected argument "gamma" ` when I ran the code.

**Comment by houwenxin** [comment]
Sorry for the inconvenience, it is my fault. I will fix it. Thank you for pointing this out.
