### ISSUE TITLE
Office-Home Datasets

### ISSUE THREAD

**Issue by wb1997-cell** [jindongwang/transferlearning#289]
Hope to have office-home data set that can be downloaded in China

**Comment by jindongwang** [comment]
Of course. Use this link: https://transferlearningdrive.blob.core.windows.net/teamdrive/dataset/OfficeHome.zip

**Comment by jindongwang** [comment]
ps: try to change xxx/OfficeHome.zip for xxx/Office31.zip or other datasets.

**Comment by wb1997-cell** [comment]
thanks
