### ISSUE TITLE
AdaRNN,为什么隐藏层的权重在pre-trainning后不再更新了？

### ISSUE THREAD

**Issue by XUANWENYANG** [jindongwang/transferlearning#293]
王老师：
我跑代码用以下参数
python train_weather.py --model_name 'AdaRNN' --station 'Tiantan' --pre_epoch 20 --dw 0.1 --data_mode 'tdc'

我发现代码中weight在pre-trainning后不再变化。
问题是在论文中所提到的boosting-base importance evaluation不起作用。
在代码中，ind表示RNN单元权值是否更新，一直为False.发现新的距离dist_new永远小于旧的距离dist_old。原因在于旧距离加上了epsilon.(epsilon =1e-5，新距离一般在1e-7至1e-8。)
并且运行的结果也没有论文中所述，是否有超参需要调整。
 MSE: train 0.000656, valid 0.000332, test 0.000972
 L1:  train 0.016684, valid 0.013255, test 0.020104
 RMSE: train 0.024590, valid 0.018004, test 0.027586

**Comment by jindongwang** [comment]
这个是我们去年跑的时候留下来的一个表示权重变化的文件：https://www.jianguoyun.com/p/DZ80SbIQjKnsBRi19KIE ，文件里面显示权重在pre-train之后是在变化的。
@yuntaodu 有时间可以帮忙看一下

**Comment by yuntaodu** [comment]
你好，对于第一个问题，感谢你的提醒，epsilon = 1e-5 这个值是针对于adv loss选取的(数量级为1)，对于cosine loss是有点大，我已经修改代码设置为epsilon为一个小的值(epsilon =1e-12)，权重就会正常更新。对于第二个问题，用这组参数测试是可以取得和论文里相近的结果，结果差异大推测原因大概率是运行环境的问题，注意一下python, cuda, pytorch和 torchvision的版本要对应。

**Comment by XUANWENYANG** [comment]
好的，非常感谢回答
