### ISSUE TITLE
领域自适应中的分布不同问题疑惑

### ISSUE THREAD

**Issue by hxynjk** [jindongwang/transferlearning#296]
您好！最近开始学习领域自适应相关知识，可以问一下领域自适应中一直假设不同域之间的概率分布不同，也就是源域的联合概率分布Ps(x,y）≠目标域的联合概率分布Pt(x,y)，那么是不是Ps和Pt是要满足至少是同一类分布，比如正态分布或者卡方分布那，如果一个是正态分布一个是卡方分布那领域自适应算法是否还适用那？同时，还想问一下这与联邦学习中的non-iid问题有什么区别或者联系那？谢谢作答

**Comment by jindongwang** [comment]
这个分布的概念比较广泛，并不一定要同类分布。 只要是不同但近似的分布都可以用的。联邦学习的non-iid可以用domain adaptation来解决。
