### ISSUE TITLE
王老师您好，有幸阅读你的书籍。用win10,运行deepDA中的DANN复现自己的数据集时出现找不到main.py。（已下载git运行）

### ISSUE THREAD

**Issue by ZLY980228** [jindongwang/transferlearning#297]
王老师您好，有幸购买了您的迁移学习书籍。在学习了一段时间后，想用自己的数据集练练手，在运行dann.sh时，一直提示找不到main.py文件。于是我在main.py中做了如下照片的修改，主要对数据集路径进行修改，这时候是可以在pycharm上跑自己的数据集的，但是当使用git对.sh文件进行运行时就出现了下面照片的问题：提示一直找不到main.py的位置，想咨询一下您这个问题具体是什么问题呢？麻烦老师了。
![DANN sh文件的修改](https://user-images.githubusercontent.com/94044316/147660231-7b882c0f-2b97-46dd-bfd7-ac934bffed42.png)
![DANN yaml文件的修改](https://user-images.githubusercontent.com/94044316/147660258-b31fbefd-b119-4384-a645-c80c28626ab8.png)
![对main py进行了如下修改后代码可以运行](https://user-images.githubusercontent.com/94044316/147660260-0eb9fdbf-b366-4995-81bb-8f50ee44f344.png)
![文件存放位置 (2)](https://user-images.githubusercontent.com/94044316/147660262-3ecd2a7a-1cab-4835-93ed-9b95888bd8e3.png)
![文件存放位置](https://user-images.githubusercontent.com/94044316/147660264-c258f714-3d39-42db-ad38-425bf9664261.png)
![用git运行 sh时就不到1秒钟的时间闪出了这样的画面，提示找不到main py这个代码](https://user-images.githubusercontent.com/94044316/147660964-d3eb9b66-5e87-48e3-98cf-1a12d48a488b.png)
![在pycharm中运行 sh文件时，一直停在这个界面，但是打开终端发现一直是在运行的](https://user-images.githubusercontent.com/94044316/147660969-374aca8b-8a03-4a37-8509-27c4abced77d.png)

**Comment by ZLY980228** [comment]
王老师，照片的名字是对应的我遇到的问题的阐述，辛苦老师

**Comment by jindongwang** [comment]
这个属于基本的路径问题，你不需要在代码里写全部路径，只需要写相对路径，然后来运行sh。如果不能运行sh在windows上，也可以直接在pycharm里运行.py文件。这个问题非常基础，建议自己加以解决。

**Comment by jindongwang** [comment]
@ZLY980228 请问问题是否解决？

**Comment by hanjingyu101** [comment]
您好， 您这个问题解决了吗，我现在也遇到这个问题求助，谢谢
