### ISSUE TITLE
question about the DAN and DDC result

### ISSUE THREAD

**Issue by yuzehui1996** [jindongwang/transferlearning#30]
Hey, I have run the codes but the result acc is always 100%.Did I make any mistakes?I run the codes according to your readme.Thanks a lot!

**Comment by easezyc** [comment]
Yeah, the max acc is always 100% in task webcam to dslr, and the max acc in the task with most methods such as DDC is also 100%. Hence, here I record the acc of the last epoch.

**Comment by yuzehui1996** [comment]
but when I change the src and target, the max acc is always 100%. And during the training , all the epochs show the acc is 100%.Why?

**Comment by easezyc** [comment]
I don't know the reason... Might be the environment? I have run the code in several machines, and all of them are ok.

**Comment by yuzehui1996** [comment]
And during the training epochs, the soft loss (classification loss) is always 0. Is there any questions about the calculating the soft loss? I mean the log_softloss function in the DDC.py train(). Thanks  a lot!

**Comment by easezyc** [comment]
I have run the code again, and I still don't find any mistakes with it.

**Comment by freemanng** [comment]
@yuzehui1996   When you download the office-31 dataset, Take the example webcam dataset. The images are at the root  webcam/images/. 
For running of the above codes, you'd better place the images at the root webcam/.  Otherwise, you'd make the following changes in DDC.py: 
source_name = "amazon" 
target_name = "webcam"
--> source_name = "amazon/images"
target_name = "webcam/images"

**Comment by yuzehui1996** [comment]
Thanks!I have run the codes successfully.But I have tried to remove the mmd loss from the final loss, and it get the higher acc than the loss contain mmd loss. I was confused with for quite a long time. Do you have any explanation?

**Comment by yuzehui1996** [comment]
Thanks a lot! And I am trying to remove 10 classes from the target domain and the num of classes are reduce to 21 classes. The num of the source domain class is 31. And I didn't change any more.With the mmd , I got the acc result is nearly to 0%. I feel quite confused about the result.

**Comment by easezyc** [comment]
I don't know. This is a partial transfer proble, and you could ask the author of Partial Transfer Learning with Selective Adversarial for the detail.

**Comment by yuzehui1996** [comment]
Thanks any way!
