### ISSUE TITLE
adarnn 中lightgbm是怎么使用的

### ISSUE THREAD

**Issue by mambasmile** [jindongwang/transferlearning#306]
王老师：

对Tiantan数据集；
训练数据集时间范围2013-3-1 0:0~2016-6-30 23:0
验证数据集时间范围2016-7-2 0:0~2016-10-30 23:0
测试数据集时间范围2016-11-2 0:0~2017-2-28 23:0

是直接在训练数据集上训练lightgbm，然后在测试集上验证么

**Comment by jindongwang** [comment]
是的

**Comment by mambasmile** [comment]
使用lightgbm模型，采用的默认参数，使用上述训练集训练模型，然后在测试集上评估，得到
RMSE = 0.0219
MAE = 0.01368 
这个指标与论文中的有很大区别，若按照这个指标会比transformer还要好
请问在使用lightgbm时，模型的各个参数是怎么设置的？

**Comment by jindongwang** [comment]
我记得当时并没有去调LightGBM的参数。 @yuntaodu 可能记得比较多的细节，可以来回答一下这个问题。

**Comment by yuntaodu** [comment]
你好，感谢你的提醒，
1）我当时采用的LightGBM参数和默认参数不同的地方包括以下三个参数： 'learning_rate': 5e-3, "num_leaves": 50, "n_estimators": 500。可能是由于n_estimators这个参数设置的比较小，当测试n_estimators的值设置较大时，结果会更好一些。
2）我用默认参数和当时的参数重新测试了一下结果，默认参数的结果更好一些，在某些任务上会比Transformer好一些，但会比adarnn的结果差一些。
                                  | Dongsi              | Tiantan              | Nongzhanguan   | Dingling
                                  | MSE     | MAE    | MSE     | MAE    |MSE      | MAE       | MSE    | MAE
lightgbm默认参数     | 0.0403 | 0.0234 | **0.0223** | **0.0140**  | 0.0281 | 0.0191   | 0.0346 | **0.0156**
lightgbm现在的参数 | 0.0587 | 0.0390 | 0.0412  | 0.0289 | 0.0436 | 0.0319   | 0.0322 | 0.0210
Transformer               | **0.0339** | **0.022**   | 0.0233 | 0.0164  | **0.0226** | **0.0181**   | **0.0263** | 0.0163
