### ISSUE TITLE
adarnn的air quality的x是6个特征，那么预测的y为什么是1个，这是回归，预测的y对应原始数据的哪个字段？

### ISSUE THREAD

**Issue by nlpofwhat** [jindongwang/transferlearning#307]
adarnn的air quality的x是6个特征，那么预测的y为什么是1个，这是回归，预测的y对应原始数据的哪个字段？

**Comment by jindongwang** [comment]
我们做的是输入多个维度（6个特征是一天多个时间的空气指数例如AQI，臭氧等，具体可以看数据集介绍），输出为第6天的平均PM2.5的值
