### ISSUE TITLE
 运行DAAN时出现'DAANLoss' object has no attribute 'lamb'，请问是什么问题？

### ISSUE THREAD

**Issue by LeungKalan** [jindongwang/transferlearning#308]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by jindongwang** [comment]
请问使用的是最新代码吗？最新代码应该没有这个问题了

**Comment by LeungKalan** [comment]
> 请问使用的是最新代码吗？最新代码应该没有这个问题了

DAAN是最新的吧，没发现有旧的代码

**Comment by GuokaiLiu** [comment]
Same issue in the latest code:

Replace:
`class DAANLoss(AdversarialLoss)`
with 
`class DAANLoss(AdversarialLoss, LambdaSheduler)`
in 
`~/code/DeepDA/loss_funcs/daan.py`

This works for me : )

**Comment by jindongwang** [comment]
@GuokaiLiu 应该是bug，我之后看一下

**Comment by jindongwang** [comment]
@LeungKalan 错误已修正。 @GuokaiLiu 感谢指正！

**Comment by GuokaiLiu** [comment]
谢谢王老师的分享，学习收获了很多 ： ）
