### ISSUE TITLE
如果我想使用其他类型的数据集，比如.mat或者.csv，我需要怎样去修改代码呢，谢谢

### ISSUE THREAD

**Issue by 123sunxun** [jindongwang/transferlearning#309]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by jindongwang** [comment]
- Load .mat: https://github.com/jindongwang/transferlearning/blob/master/code/traditional/TCA/TCA.py#L186
- Load .csv: np.loadtxt()

这是python基础操作。
