### ISSUE TITLE
关于DaNN的几个问题

### ISSUE THREAD

**Issue by 5663015** [jindongwang/transferlearning#31]
1、在原始论文论文，Algorithm 1中，计算完MMD的梯度后，更新的参数是U1，即输入层到隐藏层的参数。在main.py的第49、50行，更新的是所有的参数？
2、main.py中第34行设batch_j=0，这个变量只在第37行时使用了。这个变量一直是0吗？在计算MMD时，应用用上所有的目标域数据吧？
非常感谢解答！

**Comment by jindongwang** [comment]
@5663015 请稍等，最近在找工作，过两天我检查一下，抱歉！

**Comment by 5663015** [comment]
@jindongwang 谢谢，麻烦您了。方便加一下联系方式嘛

**Comment by jindongwang** [comment]
@5663015 jd92.wang，上面有我的中文简历里面有电话，是微信号
