### ISSUE TITLE
关于DeepDA/DANN算法的一些问题

### ISSUE THREAD

**Issue by zhonzxad** [jindongwang/transferlearning#314]
hi，我在Clone项目后代码运行有些问题。
1. 在DANN算法的实现部分，也就是`/code/DeepDA/loss_funcs/daan.py`第15，16行中，获取父类的lamb与step时按照代码是无法完成的。
```python
lamb = self.lamb()
self.step()
```
2. 按照我的运行环境（Pycharm，没有测试VS Code），应该是以下的方式才可以获取，是我的配置或者环境的问题嘛？
```python
lamb = self.lambda_scheduler.lamb()  
self.lambda_scheduler.step()
```

感谢你的博客《小王爱迁移》系列，在学习过程非常有帮助。

以上

**Comment by jindongwang** [comment]
之前是一个bug，忘记继承scheduler，现在已修改：https://github.com/jindongwang/transferlearning/blob/master/code/DeepDA/loss_funcs/daan.py#L3

**Comment by jindongwang** [comment]
#308

**Comment by zhonzxad** [comment]
ok，再次感谢相关工作。
