### ISSUE TITLE
有没有适合时间序列数据的迁移学习模型呢

### ISSUE THREAD

**Issue by Gumpliu404** [jindongwang/transferlearning#315]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by Gumpliu404** [comment]
王老师您好，我的研究方向数据集是时间序列数据，我想请问一下您这个库里面有没有适合时间序列数据的模型，我本来想先将一维数据转换成二维图片利用DeepDA进行分类，但是转换后用普通的ResNet分类器发现效果不好，所以咨询您有没有适合模型或者说只需要小规模修改就能用的模型。

**Comment by jindongwang** [comment]
把库里的resnet换成适合时间序列的基础模型，比如RNN/LSTM等就可以。我们的库是通用算法，不可能对所有数据都有效。真实使用你需要换基础模型和数据加载部分。
