### ISSUE TITLE
“Finetuned ResNet-50 models For Office-31 dataset” 有一个“best_mnist_usps.pth”

### ISSUE THREAD

**Issue by pxsongchn** [jindongwang/transferlearning#316]
**Describe the bug**
请问为什么“Finetuned ResNet-50 models For Office-31 dataset” 会有一个 “best_mnist_usps.pth”呢？貌似少了一个webcam域的预训练文件QAQ

**Screenshots**
![image](https://user-images.githubusercontent.com/47233927/159262502-2b354f02-85eb-4f35-8485-709bf92d35de.png)

**Comment by jindongwang** [comment]
model传错了，现在也找不到webcam的模型了。你可以用我提供的代码自己训练一下。毕竟这是三四年前的东西了。

**Comment by pxsongchn** [comment]
> model传错了，现在也找不到webcam的模型了。你可以用我提供的代码自己训练一下。毕竟这是三四年前的东西了。

好的谢谢！
