### ISSUE TITLE
王老师请问这是什么情况呢，模型没有训练吗

### ISSUE THREAD

**Issue by Gumpliu404** [jindongwang/transferlearning#317]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by Gumpliu404** [comment]
![cf493ad451fa0bad0ca4081e62db0b9](https://user-images.githubusercontent.com/90671629/159401989-cd45c68d-11d1-4f19-85cd-5f55a1ef7130.png)

**Comment by jindongwang** [comment]
你应该运行sh文件，肯定不会有问题的

**Comment by jindongwang** [comment]
@Gumpliu404 请问你的问题解决了吗？

**Comment by boluosnow** [comment]
王博士你好，我使用的数据label是2维，运行程序时出现“division by zero”，我推测是利用弱分类器预测出的伪标签中没有某一类label，这种情况您有什么建议吗

**Comment by jindongwang** [comment]
二维数据就不要用deepda了，没意义
