### ISSUE TITLE
about DA usage scenario

### ISSUE THREAD

**Issue by liangzimei** [jindongwang/transferlearning#32]
Hi, it‘’s my first time to try domain adaptation. Here is my scenario: i am doing a image classification task, there are already 100k training data with labels (called A), i also can obtain large data with no labels (called B) . Data A and B's domain shift are small. The plan i choose now is only using data A to train a model, and then predict samples from B directly. the results is also good. when i annotating more data from B, and use them and data A together to train, the results are better. It makes sense. However, to reduce the work of annotating lots of images, my question is can i treat A as source data , B as target data to improve accuracy further (i.e., adding data B in training phase compared with current plan) .

**Comment by jindongwang** [comment]
Yes, that's more like what we are doing these days

**Comment by liangzimei** [comment]
@jindongwang what do you think of semi-supervised learning and domain adapation, which is more suitable?
