### ISSUE TITLE
关于AdaRNN的结果

### ISSUE THREAD

**Issue by Arcueid-Brunestud** [jindongwang/transferlearning#322]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by Arcueid-Brunestud** [comment]
您好，我又跑了一下AdaRNN，部分结果如下图，

![20220329-192301](https://user-images.githubusercontent.com/45426146/160600758-33afe1bc-73ce-420f-b9e0-9a4999eef6d1.png)

主要有两个问题：
（1）为什么验证（or 测试）集上的loss抖动很厉害，比如第40, 41, 42个epoch的loss分别为0.46, 0.013, 0.08？
（2）为什么感觉 transfer_loss (adv)并没有下降？

我的包可能和推荐的包略有不同，不知道您的结果是否有这种现象？

**Comment by jindongwang** [comment]
Loss会有一个下降的过程，然后就保持不变了，不会一直降；权重的话是调出来的，这个感觉有点玄学
