### ISSUE TITLE
您好，我看distance文件夹中有计算不同领域分布的A-distance，如何运用DeepDA中的一些模型来计算各自源域到目标域的A-distance大小呢？

### ISSUE THREAD

**Issue by zhen-yan** [jindongwang/transferlearning#323]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by jindongwang** [comment]
DeepDA训练完后对数据做inference，把分类器层前特征保存下来，然后用A-dist去计算。

**Comment by zhen-yan** [comment]
您好，我在应用proxy_a_distance时遇到了另外的问题:我看案例是用一些.mat文件，我尝试将自己的一些图片数据集保存为.mat格式进行输入，出现了问题如下：ValueError: setting an array element with a sequence.

其中导入mat文件计算a_distance的代码为：
![image](https://user-images.githubusercontent.com/81688197/161536228-25ba1ef5-1242-4aa0-8059-8e0381512644.png)

其中我的mat文件内容如下
![image](https://user-images.githubusercontent.com/81688197/161536450-34fc999c-6926-4c82-ac72-65102541d1ff.png)

**Comment by jindongwang** [comment]
这是你没处理输入的问题。这个distance函数接收的是两个m * n的矩阵，你需要处理一下把mat里面的数据整理成这样的格式。

**Comment by zhen-yan** [comment]
我尝试了换成mxn矩阵，还是报一样的错误。是因为我mat文件夹下是cell类型的数据吗，我尝试用str2num(cell2mat( ))命令转换成double数据发现输入必须为字符向量或字符串标量。我想问一下像三维的cell数据怎么转换成double数据呢？

**Comment by jindongwang** [comment]
亲，我提供的函数就是接收两个矩阵的，你需要把你的数据转换成相应的numpy二维格式。具体怎么转换应该你自己动手去实现。
________________________________
发件人: zhen-yan ***@***.***>
发送时间: Monday, April 4, 2022 8:43:48 PM
收件人: jindongwang/transferlearning ***@***.***>
抄送: Jindong Wang ***@***.***>; State change ***@***.***>
主题: Re: [jindongwang/transferlearning] 您好，我看distance文件夹中有计算不同领域分布的A-distance，如何运用DeepDA中的一些模型来计算各自源域到目标域的A-distance大小呢？ (Issue #323)


我尝试了换成mxn矩阵，还是报一样的错误。是因为我mat文件夹下是cell类型的数据吗，我尝试用str2num(cell2mat( ))命令转换成double数据发现输入必须为字符向量或字符串标量。我想问一下像三维的cell数据怎么转换成double数据呢？

―

**Comment by jindongwang** [comment]
另外，这个是matlab基础问题，cell明显就不是一个矩阵呀，你为什么要输入呢，输入一定会错的呀。如果你的数据是三维，你需要把他reshape成二维才可以的。
________________________________
发件人: Wang Jindong ***@***.***>
发送时间: Monday, April 4, 2022 8:46:18 PM
收件人: jindongwang/transferlearning ***@***.***>; jindongwang/transferlearning ***@***.***>
抄送: State change ***@***.***>
主题: Re: [jindongwang/transferlearning] 您好，我看distance文件夹中有计算不同领域分布的A-distance，如何运用DeepDA中的一些模型来计算各自源域到目标域的A-distance大小呢？ (Issue #323)

亲，我提供的函数就是接收两个矩阵的，你需要把你的数据转换成相应的numpy二维格式。具体怎么转换应该你自己动手去实现。
________________________________
发件人: zhen-yan ***@***.***>
发送时间: Monday, April 4, 2022 8:43:48 PM
收件人: jindongwang/transferlearning ***@***.***>
抄送: Jindong Wang ***@***.***>; State change ***@***.***>
主题: Re: [jindongwang/transferlearning] 您好，我看distance文件夹中有计算不同领域分布的A-distance，如何运用DeepDA中的一些模型来计算各自源域到目标域的A-distance大小呢？ (Issue #323)


我尝试了换成mxn矩阵，还是报一样的错误。是因为我mat文件夹下是cell类型的数据吗，我尝试用str2num(cell2mat( ))命令转换成double数据发现输入必须为字符向量或字符串标量。我想问一下像三维的cell数据怎么转换成double数据呢？

―
