### ISSUE TITLE
关于时序数据

### ISSUE THREAD

**Issue by Lyric-shao** [jindongwang/transferlearning#326]
王博士您好：
        因为对于ADARNN模型了解不够深入，想问两个问题：
1.您给出的天气预测案例中输入6维数组中包含作为要预测值的pm2.5，请问在实际训练过程中输入的pm2.5数据也作为训练数据吗，如果也作为训练数据，它相对于其他的输入数据例如pm10，臭氧的训练权重一样吗？
2.将ADARNN模型应用在与时间相关数据的预测上是否可行（在pm2.5不作为训练数据，只是参照值label_reg的情况下），例如预测从数据采样点到pm2.5达到100所需要的剩余时间，这种剩余时间的数据本身就和时间有强的线性相关性。例如训练集第100个采样点pm2.5达到了100，那么第一个采样点的剩余时间就是99，第二个采样点的剩余时间是98，第三个剩余时间是97......    这种强的时间相关性的数据是否有用ADARNN预测的可能呢

**Comment by jindongwang** [comment]
1. 我们做的是预测问题，就是根据前N天的天气去预测第N+1天的天气。所以输入数据会包含前N天的所有数据，这也是能理解的正常情况。因此会输入前N天的PM2.5数据。
2. AdaRNN是一个通用的方法，当然可以用在其他数据上，没什么问题。但可能需要调调模型之类的让它效果好。

**Comment by Lyric-shao** [comment]
好的，感谢您的解答
