### ISSUE TITLE
关于DeepDA库使用结构体数据进行迁移学习

### ISSUE THREAD

**Issue by ElsaReedz** [jindongwang/transferlearning#327]
王博您好，我希望在您开发的DeepDA工具包中使用结构体类型数据(.txt,.csv)作为输入进行迁移训练，请问需要如何修改load_data函数以及其他相关接口呢？

我的想法大概是实现一个功能如同torchvision.datasets.ImageFolder的函数替代之，但奈何才疏学浅，还请王博指点

**Comment by jindongwang** [comment]
修改利用自己的数据，应该以自己数据为主。平时你如何利用pytorch去加载，在deepda中替换即可。核心算法是不变的。

**Comment by ElsaReedz** [comment]
> 修改利用自己的数据，应该以自己数据为主。平时你如何利用pytorch去加载，在deepda中替换即可。核心算法是不变的。

王博您好，感谢您的解答，是这样的，我之前没怎么接触过迁移学习，但选题是用迁移学习方法做建筑能耗的预测，所以希望找一个可供参考的相关论文和代码实现来进一步学习，想请教您有没有相关方面的论文和repo推荐呢

**Comment by jindongwang** [comment]
加载数据用不到迁移学习的东西。你应该先不用迁移学习、用传统的深度方法来做你的问题，然后再把迁移算法加进去。
