### ISSUE TITLE
概念疑问：关于DeepCORAL应所属于DA还是DG的问题

### ISSUE THREAD

**Issue by djahdkjqbwfkb1213** [jindongwang/transferlearning#328]
感谢王博士以及团队的工作，本人初入迁移学习领域，运行该repo时注意到在DeepDA和DeepDG两个子项目下均实现了DeepCORAL，因此想请教一下其原因，谢谢！

**Comment by jindongwang** [comment]
很简单，coral方法是通用的，所以可以用来做da和dg。同理，mmd，dann都是这样的。具体可以看我综述：https://arxiv.org/abs/2103.03097
