### ISSUE TITLE
您好，跑transformer-adapt.py好像报错了

### ISSUE THREAD

**Issue by yangye19960922** [jindongwang/transferlearning#329]
代码中的chunk_mode默认是none，对应的也就是普通的transformer。然后我将其替换成chunk_mode = 'chunk'之后，报错如下:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/36871131/165322323-5d2a6d62-0b8a-4097-ba59-3375fb0dd0b5.png">
同样的，当chunk_mode = 'window'的时候，也会有如下的报错
<img width="441" alt="image" src="https://user-images.githubusercontent.com/36871131/165322636-dd6604aa-a1a2-4bfb-8ed0-c3e6ac312e2c.png">
请问一下，针对上述的情况大概需要怎么修改代码呢

**Comment by jindongwang** [comment]
我没有在本repo中找到`transformer-adapt.py`这个文件。

**Comment by yangye19960922** [comment]
不好意思，可能是我表述的不够清楚，是在ADARNN的项目下
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/36871131/165423520-b96e83ee-00de-45e6-a7c0-07d4a1c9c6bb.png">

**Comment by jindongwang** [comment]
@yuntaodu

**Comment by yuntaodu** [comment]
你好，transformer模型的代码是用的别人开源的框架，我只是用了默认设置来进行测试。这个错误原因看起来可能是参数设置的问题，我也不是很了解，可以咨询一下transformer的作者如何进行设置。transformer框架地址: https://github.com/maxjcohen/transformer，其中的TST文件和这里的TST文件对应。

**Comment by yangye19960922** [comment]
那其实用默认的attention跑也是可以的吧，因为这个py文件的核心内容是encoder之间权重的更新是吧

**Comment by jindongwang** [comment]
用什么attention都可以
