### ISSUE TITLE
关于adarnn迁移

### ISSUE THREAD

**Issue by Lyric-shao** [jindongwang/transferlearning#330]
王博士：
       您好！
       我想请教一下，因为readme里面说的例子是加载一个station的数据，请问target数据在哪里加载呢？
因为在train_weather.py中变量feature，label_reg以及损失函数loss都有下标_s和_t,应该是分别对应的sourse和target数据，但是data_process等加载数据的程序的station的赋值似乎只有一个‘Changping’，没有发现target的数据加载过程，麻烦王博士解答一下，非常感谢！

**Comment by Lyric-shao** [comment]
另外可以问下王博士adarnn模型的超参数的含义吗，我看到代码里面在注释部分提供多个推荐值的有pre_epoch，dw，想问下dw的含义以及其他在训练模型时有可能需要调整的超参数，谢谢王博士！

**Comment by jindongwang** [comment]
@yuntaodu

**Comment by yuntaodu** [comment]
你好，pre_epoch和dw是分别对应预训练轮数和损失函数的transfer权重系数。其他的参数如batchsize, 隐藏层个数num_layers， 隐藏层维度hidden_size等，也可依据不同任务自行修改。
