### ISSUE TITLE
新增paper "IJCAI-21 Test-time Fourier Style Calibration for Domain Generalization" 的conference弄错了 

### ISSUE THREAD

**Issue by xingchenzhao** [jindongwang/transferlearning#332]
你好，我是 “Test-time Fourier Style Calibration for Domain Generalization](https://arxiv.org/abs/2205.06427)”的作者，感谢添加这篇paper！这篇paper是IJCAI-22的，我上传arxiv不小心写成21了 抱歉！希望可以修改一下

**Comment by jindongwang** [comment]
Sure.
