### ISSUE TITLE
DAAN

### ISSUE THREAD

**Issue by frallisland** [jindongwang/transferlearning#334]
在 master/code/deep/DAAN/model/DAAN.py 文件中，模型类并未初始化 self.training 的值。

**Comment by jindongwang** [comment]
`DAAN`继承了pytorch中的`nn.Module`，而`self.training`属性为`nn.Module`所有。详情请见：https://discuss.pytorch.org/t/how-do-i-customize-my-modules-behavior-for-train-and-eval/52693/2。

**Comment by frallisland** [comment]
好的，明白了。
