### ISSUE TITLE
AdaTransformer中的adapt_encoding_weight函数好像有些问题

### ISSUE THREAD

**Issue by yangye19960922** [jindongwang/transferlearning#335]
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/36871131/171408318-1bf39253-d033-4b4b-9130-a12e69a46208.png">
作者您好，最近扒代码发现了一个疑惑
train_type置为last的时候，不会返回dist_mat值，请问是不是漏写了
因为我以last进行训练输出dist_mat的时候，是值都为0的tensor。

**Comment by jindongwang** [comment]
@yuntaodu 来看一下

**Comment by yuntaodu** [comment]
train_type设成last是我自己之前试过的一个方法，这个是只在最后一个hidden state算tranfer loss, 没有用全部的hidden state, 所以就用不到dist_mat。train_type设置成"all"对应的是我们的方法。我之后会修改代码，把train_type=last这部分(line 193 - 1line 195)删掉。

**Comment by yangye19960922** [comment]
感谢您的回复，我刚刚根据您代码重新跑了一下，仅仅对比last和all对于结果的影响
图1是last
<img width="550" alt="image" src="https://user-images.githubusercontent.com/36871131/171573093-f42b404b-783c-4131-b40f-75b10fb7f7a2.png">
图2是all
<img width="569" alt="image" src="https://user-images.githubusercontent.com/36871131/171574009-569ea7f3-a754-489e-9012-c0945a6644ba.png">

比较奇怪的是，last比all号，并且我在自己的数据集上也是last比all好的情况，这其实还蛮值得深入研究的。。。

**Comment by jindongwang** [comment]
这个结果很正常。因为我们得到的最终结果是在validation set上调参出来的。用同一组参数跑不同的方法，是不公平的。所以最好结果需要各自进行调参。

**Comment by yangye19960922** [comment]
我大概懂你的意思了，不过我个人感觉直接删除last会不会不太好，毕竟这种训练方式跑的速度更快，然后运行结果精度也是不赖的

**Comment by jindongwang** [comment]
都可以。AdaTransformer不是我们的重点。

**Comment by yangye19960922** [comment]
好的，谢谢您的回答。我还有一个小问题想咨询一下，adatransformer里面有一个pre_epoch参数，我理解的是预训练的参数？但是我看了一下整体代码没有用到这个参数。所以想问一下这个参数的意义在哪儿？感觉和adarnn的代码不太一样，adarnn里面是有明显的pre_train的
<img width="616" alt="image" src="https://user-images.githubusercontent.com/36871131/171627644-29f82331-2507-4a47-b094-eb209dac03ae.png">

**Comment by jindongwang** [comment]
如果没用到，就是没有用；再次重申，AdaTransformer只是一个小demo小实验，不是主要部分，仅供参考。
