### ISSUE TITLE
DeepDG中的MLDG方法在PACS上的效果很差，不清楚原因

### ISSUE THREAD

**Issue by Lin-7** [jindongwang/transferlearning#336]
您好，刚接触DG这个领域，想找MLDG的代码复现一下，但是使用这个仓库提供的MLDG实现和默认的参数在PACS上直接跑出的结果是valid acc:0.1942；target acc:0.1234，你们没有提供MLDG在PACS上的结果，我不知道是我执行代码出现了问题还是算法本身的实现有问题，请问能提供一下你们实验的结果让我参考一下吗？或者你们已经提供了结果但是被我忽略了？

**Comment by Lin-7** [comment]
使用的网络是Resnet-18

**Comment by jindongwang** [comment]
@lw0517

**Comment by Lin-7** [comment]
这是来自QQ邮箱的自动回复邮件。已收到您的邮件~

**Comment by lw0517** [comment]
我刚刚下载了当前版本代码，在3090，torch1.7.1下进行了初步验证，代码应该问题不大，主要应该是超参数的设置。我们没有在mldg上进行大规模调参，初步测试了下面的参数，结果勉强可以接受。如果你需要更好的结果，我们建议你细致的进行调参，甚至对于mldg中inner的优化器进行调整
python train.py --task img_dg --dataset PACS --test_envs 0 --algorithm MLDG --inner_lr 0.1 --mldg_beta 0.1 --lr 0.001 --net resnet18 --data_dir /home/lw/lw/data/ --output /home/lw/lw/data/train_output/test
![image](https://user-images.githubusercontent.com/31000480/172108802-c0390547-31b3-474a-967f-edae26b4d6a2.png)

**Comment by Lin-7** [comment]
了解了，确实是超参数的设置问题，非常感谢您的帮助和建议，感谢你们提供这个代码仓库！
