### ISSUE TITLE
自己运行DEEPDA中的DAAN准确率低

### ISSUE THREAD

**Issue by Dhuzi96** [jindongwang/transferlearning#337]
![image](https://user-images.githubusercontent.com/69839710/173478723-65257956-f5cd-42fe-94fd-380592da2d01.png)
我只改了这个地方，使代码可以直接在vscode中运行，发现office31中D-A的准确率只有55，会不会是我硬件的关系啊
硬件是4张24G显存的泰坦RTXGPU

**Comment by Dhuzi96** [comment]
刚刚又跑了下DANN，所以config那儿现在是DANN

**Comment by jindongwang** [comment]
你在vscode中运行时是直接点运行按钮，还是按照run.sh文件中的指令完整运行的？

**Comment by Dhuzi96** [comment]
> 你在vscode中运行时是直接点运行按钮，还是按照run.sh文件中的指令完整运行的？

是直接点运行按钮的

**Comment by jindongwang** [comment]
请尝试在命令行运行我们提供的sh文件：https://github.com/jindongwang/transferlearning/blob/master/code/DeepDA/DANN/DANN.sh

**Comment by Dhuzi96** [comment]
![image](https://user-images.githubusercontent.com/69839710/173713844-4d682eb3-c43c-477f-a64b-55e3bb3935d3.png)
现在是运行的sh文件，还是这样哎

**Comment by jindongwang** [comment]
那我不知道要怎么帮助你。你可以再确定一下环境是否有问题， 是不是按照我们的要求装的。如果什么都不改，肯定是能得到相应的结果。

**Comment by Dhuzi96** [comment]
好的，谢谢王老师啦！环境确实不太一样，用的pytorch这些工具的版本都高一些，不过不能复现好的效果其实也不太影响。总之您的工作对我来说帮助非常大，感谢！
