### ISSUE TITLE
CORAL Fit Bracket Enclosing Error

### ISSUE THREAD

**Issue by KevinHooah** [jindongwang/transferlearning#348]
The CORAL class's fit method has a Bracket Enclosing Mismatch bug.

Current code (as of 08/25/2022 PDT):
`Xs_new = np.real(np.linalg.multi_dot([Xs, scipy.linalg.fractional_matrix_power(cov_src, -0.5), scipy.linalg.fractional_matrix_power(cov_tar, 0.5))])`

The left parenthesizes and brackets order is: ( ( [

But the right enclosing part's order is: ) ] )

**Comment by jindongwang** [comment]
Thanks for the correction! I checked the merge history and found that this was committed in this link: https://github.com/jindongwang/transferlearning/commit/3fcb529bc4e1546d8db7173deacecf17028cd1a4

However, the previous link CORAL file should be like this: https://github.com/jindongwang/tlbook-code/blob/main/chap06_geometrical/coral.py

Let me correct it.

**Comment by jindongwang** [comment]
@KevinHooah Corrected.

**Comment by KevinHooah** [comment]
Looks great!
