### ISSUE TITLE
can not get the processed air-quality dataset from the link "https://box.nju.edu.cn/f/2239259e06dd4f4cbf64/?dl=1"

### ISSUE THREAD

**Issue by hongyonghan** [jindongwang/transferlearning#353]
I can not get the processed air-quality dataset from the link "https://box.nju.edu.cn/f/2239259e06dd4f4cbf64/?dl=1"

**Comment by ChaoGuosuper** [comment]
The link "https://box.nju.edu.cn/f/2239259e06dd4f4cbf64/?dl=1" ERR_CONNECTION_CLOSED

**Comment by jindongwang** [comment]
Dataset link is updated. Please refresh the readme file of AdaRNN.
