### ISSUE TITLE
获取更多的输出信息

### ISSUE THREAD

**Issue by Uncococo** [jindongwang/transferlearning#356]
您好！请问在DeepDG算法库中如何获取更多的输出信息，不仅仅是DGresult、精确度，能否输出像正确率、F1分数等信息，方便后续进行混淆矩阵计算。如果可以的话，应该如何修改程序？

**Comment by jindongwang** [comment]
这个很简单啊，你用sklearn就可以实现。在main函数里面修改，哪里需要就在哪里加上就行。
