### ISSUE TITLE
关于adarnn多步预测

### ISSUE THREAD

**Issue by Riptide3** [jindongwang/transferlearning#357]
王老师您好，请问adarnn论文中天气数据的多步预测结果具体是如何得到的？代码中并未看到相关实现，复现不出论文中的结果。

**Comment by jindongwang** [comment]
多步预测是通过将Groundtruth label设置为未来你要的步长实现的，训练的时候也是这样进行训练。
我们并没有放出所有的开源代码，只放出了训练一步的代码。

**Comment by Riptide3** [comment]
是说把`class_num`参数置为6，然后将label也相应的调整为后6个小时这样去训练吗？我尝试去做并没有得到很好的结果。

**Comment by jindongwang** [comment]
你的dataloader也要相应地输入6小时的数据去训练呀

**Comment by Riptide3** [comment]
输入是`batch * 24 * 6`，输出是`batch * 6`，我现在是这么做的

**Comment by jindongwang** [comment]
那应该问题不大，剩下就是数据处理了。毕竟2年前做的工作，我实在记不清楚这个细节了。如有疑问可以问一作，让他提供代码。一作的github是 yuntaodu

**Comment by Riptide3** [comment]
👌，谢谢王老师
