### ISSUE TITLE
MMD of large datasets

### ISSUE THREAD

**Issue by luopx** [jindongwang/transferlearning#358]
Hi! Thank you very much for this excellent project! I would like to use MMD(rbf kernel) to measure the similarity of two datasets. However, I found it hard to calculate MMD of large datasets because of insufficient memory. In my case, one dataset is 7207 rows × 79 columns and the other is 93070 rows × 79 columns; the memory is 64GB but insufficient. I failed to search for a solution to this problem, so sorry to bother you here. Looking forward to your reply!

**Comment by jindongwang** [comment]
To my best knowledge, there are no other methods to compute MMD for large matrices. Honestly speaking, the main problem is you have a small memory of only 64GB. For instance, in Microsoft, our debug machines often have a memory of 256GB...

An approximation would be using deep learning to compute the distances in a mini-batch style and then summarize or average the results.

**Comment by luopx** [comment]
Thank you for your reply! Could I use linear kernel instead of rbf kernel?

**Comment by luopx** [comment]
OK! Thank you very much!
