### ISSUE TITLE
关于 DANN Discriminator 算法输入的问题

### ISSUE THREAD

**Issue by lizhogn** [jindongwang/transferlearning#361]
您好，非常感谢您开源的平台，这里我有一个关于DANN的问题，希望能够得到解答。

相关代码如下，在DANN的forward过程中，我注意到每次输入的domain类别顺序都是相同的，以`batchsize=4`为例 ，每次输入的label都是`[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]`的形式，这种形式（没有shuffle）会影响判别器的判断吗？

```python
def update(self, minibatches, opt, sch):
    all_x = torch.cat([data[0].cuda().float() for data in minibatches])
    all_y = torch.cat([data[1].cuda().long() for data in minibatches])
    all_z = self.featurizer(all_x)

    disc_input = all_z
    disc_input = Adver_network.ReverseLayerF.apply(
        disc_input, self.args.alpha)
    disc_out = self.discriminator(disc_input)
    disc_labels = torch.cat([
        torch.full((data[0].shape[0], ), i,
                   dtype=torch.int64, device='cuda')
        for i, data in enumerate(minibatches)
    ])

    disc_loss = F.cross_entropy(disc_out, disc_labels)
    all_preds = self.classifier(all_z)
```

**Comment by jindongwang** [comment]
不会的，输入顺序不影响结果。
________________________________
发件人: lizhogn ***@***.***>
发送时间: Saturday, November 19, 2022 4:28:18 PM
收件人: jindongwang/transferlearning ***@***.***>
抄送: Subscribed ***@***.***>
主题: [jindongwang/transferlearning] 关于 DANN Discriminator 算法输入的问题 (Issue #361)


您好，非常感谢您开源的平台，这里我有一个关于DANN的问题，希望能够得到解答。

相关代码如下，在DANN的forward过程中，我注意到每次输入的domain类别顺序都是相同的，以batchsize=4为例 ，每次输入的label都是[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]的形式，这种形式（没有shuffle）会影响判别器的判断吗？

def update(self, minibatches, opt, sch):

    all_x = torch.cat([data[0].cuda().float() for data in minibatches])

    all_y = torch.cat([data[1].cuda().long() for data in minibatches])

    all_z = self.featurizer(all_x)



    disc_input = all_z

    disc_input = Adver_network.ReverseLayerF.apply(

        disc_input, self.args.alpha)

    disc_out = self.discriminator(disc_input)

    disc_labels = torch.cat([

        torch.full((data[0].shape[0], ), i,

                   dtype=torch.int64, device='cuda')

        for i, data in enumerate(minibatches)

    ])



    disc_loss = F.cross_entropy(disc_out, disc_labels)

    all_preds = self.classifier(all_z)

―

**Comment by lizhogn** [comment]
> 

好的，感谢您的解答
