### ISSUE TITLE
Hello, I know that SOT is a traditional method to solve DA problem, how to use it in deep learning?

### ISSUE THREAD

**Issue by maoshiyun** [jindongwang/transferlearning#370]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by lw0517** [comment]
You can refer to this article, https://openreview.net/pdf?id=q5ru7alcpfM.
