### ISSUE TITLE
When use DeepGA ANDMask find an error?

### ISSUE THREAD

**Issue by didi226** [jindongwang/transferlearning#373]
**Describe the bug**
When use DeepGA ANDMask find an error?

**To Reproduce**
Where is this bug happen?
  
env_grads = autograd.grad(
                env_loss, self.network.parameters(), retain_graph=True)
error:
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

allow_unused=True do not work well too.
**Screenshots**
![image](https://user-images.githubusercontent.com/58537545/221181132-3daec0e6-d9ff-4ef4-b2ac-51ea26951304.png)

**Comment by luhaifeng19947** [comment]
我已经收到您的邮件，会尽快处理。

**Comment by wlh-coconut** [comment]
你好，这是贺雯丽的自动回复，您的信息已经收到。祝身体健康，万事如意！                                                      贺雯丽

**Comment by jindongwang** [comment]
What is DeepGA? We do not have such code.
