### ISSUE TITLE
A question about mmd.py of MRAN

### ISSUE THREAD

**Issue by gloomy1999** [jindongwang/transferlearning#374]
Maybe in the cmmd function of mmd.py, threre should be "s_label = torch.zeros(32, args.nc).scatter_(1, s_label.data, 1)" rather than "s_label = torch.zeros(32, 31).scatter_(1, s_label.data, 1)"? Cause when I reproduced the code using datasets that have 32 classes, I got error like "RuntimeError: Invalid index in scatter". And when I change it and other relevant parts to "args.nc", it works.

**Comment by jindongwang** [comment]
seem right. let me fix this error later.
