### ISSUE TITLE
我想请教以下，在领域自适应中，源域和目标域数据量差距往往很大。在进行领域自适应计算时，是不是会舍弃掉部分数据不参与领域自适应，而以最短的数据作为取出的数据量呢

### ISSUE THREAD

**Issue by deeplearningkl** [jindongwang/transferlearning#375]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by jindongwang** [comment]
不是这样的。没有舍弃数据。具体操作你可以去看deepda的源码。

**Comment by jindongwang** [comment]
@deeplearningkl https://github.com/jindongwang/transferlearning/blob/master/code/DeepDA/data_loader.py
