### ISSUE TITLE
TCA算法中求解特征向量的问题

### ISSUE THREAD

**Issue by fqxrgf** [jindongwang/transferlearning#376]
王老师您好，有个问题在学习您的TCA的时候没有搞明白，在您TCA的代码中a = $(K L K+ \mu I)^{-1}$ ， b = $K H K$。我们如果想要求 $(K L K+ \mu I)^{-1}K H K$的特征向量，应该写成scipy.linalg.eig(b, a)。但是经过我的实验您的代码是正确的，如果调换位置会导致没有办法识别批次内的特征。而且我也验证了如果要求得的  $(K L K+ \mu I)^{-1}K H K$  特征值，确实应该写成scipy.linalg.eig(b, a)。我也参考了之前的issue，但是还是没有弄得太清楚。代码解决了 aV = bVw这个问题，但是公式看起来给出的是bV = aVw这个问题，所以不知道我在那里理解出了问题。

**Comment by jindongwang** [comment]
时间久远我记不清了。这个应该是python包的相关问题。

**Comment by fqxrgf** [comment]
我还想请教一下王老师，TCA有没有办法泛化到多个数据集上。比如输入三个矩阵输出三个矩阵？非常感谢！

**Comment by jindongwang** [comment]
这个目前没有实现。你可以扩展一下这个算法。但我觉得是不行的。
