### ISSUE TITLE
Digit-five dataset link

### ISSUE THREAD

**Issue by 1320harry** [jindongwang/transferlearning#378]
Hello ! Thank you for providing awesome codes. 

I found that the download link for dataset "digit-five" is not working. Could you please fix it?

Thank you.

**Comment by jindongwang** [comment]
Could you please tell me which page?

**Comment by jindongwang** [comment]
Sure. The new link is: https://wjdcloud.blob.core.windows.net/dataset/dg5.tar.gz. I will fix this in the readme.

**Comment by noparkee** [comment]
Thank you for solving it quickly!

**Comment by jindongwang** [comment]
try replacing the old link with the above http header for dg5?
