### ISSUE TITLE
DIFEX中的损失函数问题

### ISSUE THREAD

**Issue by ss3b3** [jindongwang/transferlearning#380]
王老师您好，在DIFEX的loss中有一项是internally-invariant（z_1）和mutually-invariant（z_2）之间的距离。这里的mutually-invariant features（z_2）是如何得到的呢？对于这里有点理解不清，这里的loss3中应该是计算二者的距离，z_1为all_z[:, :self.tfbd]，z_2为all_z[:, self.tfbd:]吗？二者都是由同一个网络得到的吗？

```
    def update(self, minibatches, opt, sch):
        all_x = torch.cat([data[0].cuda().float() for data in minibatches])
        all_y = torch.cat([data[1].cuda().long() for data in minibatches])
        with torch.no_grad():
            all_x1 = torch.angle(torch.fft.fftn(all_x, dim=(2, 3)))
            tfea = self.teab(self.teaf(all_x1)).detach()

        all_z = self.bottleneck(self.featurizer(all_x))
        loss1 = F.cross_entropy(self.classifier(all_z), all_y)

        loss2 = F.mse_loss(all_z[:, :self.tfbd], tfea)*self.args.alpha
        if self.args.disttype == '2-norm':
            loss3 = -F.mse_loss(all_z[:, :self.tfbd],
                                all_z[:, self.tfbd:])*self.args.beta
        elif self.args.disttype == 'norm-2-norm':
            loss3 = -F.mse_loss(all_z[:, :self.tfbd]/torch.norm(all_z[:, :self.tfbd], dim=1, keepdim=True),
                                all_z[:, self.tfbd:]/torch.norm(all_z[:, self.tfbd:], dim=1, keepdim=True))*self.args.beta
        elif self.args.disttype == 'norm-1-norm':
            loss3 = -F.l1_loss(all_z[:, :self.tfbd]/torch.norm(all_z[:, :self.tfbd], dim=1, keepdim=True),
                               all_z[:, self.tfbd:]/torch.norm(all_z[:, self.tfbd:], dim=1, keepdim=True))*self.args.beta
        elif self.args.disttype == 'cos':
            loss3 = torch.mean(F.cosine_similarity(
                all_z[:, :self.tfbd], all_z[:, self.tfbd:]))*self.args.beta
        loss4 = 0
        if len(minibatches) > 1:
            for i in range(len(minibatches)-1):
                for j in range(i+1, len(minibatches)):
                    loss4 += self.coral(all_z[i*self.args.batch_size:(i+1)*self.args.batch_size, self.tfbd:],
                                        all_z[j*self.args.batch_size:(j+1)*self.args.batch_size, self.tfbd:])
            loss4 = loss4*2/(len(minibatches) *
                             (len(minibatches)-1))*self.args.lam
        else:
            loss4 = self.coral(all_z[:self.args.batch_size//2, self.tfbd:],
                               all_z[self.args.batch_size//2:, self.tfbd:])
            loss4 = loss4*self.args.lam

        loss = loss1+loss2+loss3+loss4
        opt.zero_grad()
        loss.backward()
        opt.step()
        if sch:
            sch.step()
        return {'class': loss1.item(), 'dist': (loss2).item(), 'exp': (loss3).item(), 'align': loss4.item(), 'total': loss.item()}
```
我的理解是网络分成了两支，一直是通过蒸馏得到的student model，能够计算z_1，另外一支计算的z_2。z_1和z_2简单拼接得到的Invariant feature对吗？

**Comment by jindongwang** [comment]
@lw0517 来回答一下

**Comment by lw0517** [comment]
> 王老师您好，在DIFEX的loss中有一项是internally-invariant（z_1）和mutually-invariant（z_2）之间的距离。这里的mutually-invariant features（z_2）是如何得到的呢？对于这里有点理解不清，这里的loss3中应该是计算二者的距离，z_1为all_z[:, :self.tfbd]，z_2为all_z[:, self.tfbd:]吗？二者都是由同一个网络得到的吗？
> 
> ```
>     def update(self, minibatches, opt, sch):
>         all_x = torch.cat([data[0].cuda().float() for data in minibatches])
>         all_y = torch.cat([data[1].cuda().long() for data in minibatches])
>         with torch.no_grad():
>             all_x1 = torch.angle(torch.fft.fftn(all_x, dim=(2, 3)))
>             tfea = self.teab(self.teaf(all_x1)).detach()
> 
>         all_z = self.bottleneck(self.featurizer(all_x))
>         loss1 = F.cross_entropy(self.classifier(all_z), all_y)
> 
>         loss2 = F.mse_loss(all_z[:, :self.tfbd], tfea)*self.args.alpha
>         if self.args.disttype == '2-norm':
>             loss3 = -F.mse_loss(all_z[:, :self.tfbd],
>                                 all_z[:, self.tfbd:])*self.args.beta
>         elif self.args.disttype == 'norm-2-norm':
>             loss3 = -F.mse_loss(all_z[:, :self.tfbd]/torch.norm(all_z[:, :self.tfbd], dim=1, keepdim=True),
>                                 all_z[:, self.tfbd:]/torch.norm(all_z[:, self.tfbd:], dim=1, keepdim=True))*self.args.beta
>         elif self.args.disttype == 'norm-1-norm':
>             loss3 = -F.l1_loss(all_z[:, :self.tfbd]/torch.norm(all_z[:, :self.tfbd], dim=1, keepdim=True),
>                                all_z[:, self.tfbd:]/torch.norm(all_z[:, self.tfbd:], dim=1, keepdim=True))*self.args.beta
>         elif self.args.disttype == 'cos':
>             loss3 = torch.mean(F.cosine_similarity(
>                 all_z[:, :self.tfbd], all_z[:, self.tfbd:]))*self.args.beta
>         loss4 = 0
>         if len(minibatches) > 1:
>             for i in range(len(minibatches)-1):
>                 for j in range(i+1, len(minibatches)):
>                     loss4 += self.coral(all_z[i*self.args.batch_size:(i+1)*self.args.batch_size, self.tfbd:],
>                                         all_z[j*self.args.batch_size:(j+1)*self.args.batch_size, self.tfbd:])
>             loss4 = loss4*2/(len(minibatches) *
>                              (len(minibatches)-1))*self.args.lam
>         else:
>             loss4 = self.coral(all_z[:self.args.batch_size//2, self.tfbd:],
>                                all_z[self.args.batch_size//2:, self.tfbd:])
>             loss4 = loss4*self.args.lam
> 
>         loss = loss1+loss2+loss3+loss4
>         opt.zero_grad()
>         loss.backward()
>         opt.step()
>         if sch:
>             sch.step()
>         return {'class': loss1.item(), 'dist': (loss2).item(), 'exp': (loss3).item(), 'align': loss4.item(), 'total': loss.item()}
> ```
> 
> 我的理解是网络分成了两支，一直是通过蒸馏得到的student model，能够计算z_1，另外一支计算的z_2。z_1和z_2简单拼接得到的Invariant feature对吗？

mutually-invariant features是通过CORAL对齐获得。loss3中是计算二者的距离。二者都是由同一个网络得到的。对的，可以这样理解。其实就是前面backbone是公用的，最后分成了两支，服务于不同不变特征。

**Comment by ss3b3** [comment]
明白了，谢谢二位老师^_^
