### ISSUE TITLE
can NOT train on the specific GPU

### ISSUE THREAD

**Issue by ZZhangsm** [jindongwang/transferlearning#381]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**
When I use the option --gpu_id, the model is always training on gpu:0

**To Reproduce**
train.py Line 93 
os.environ['CUDA_VISIBLE_DEVICS'] = args.gpu_id
This line is not useful because of typo

**Screenshots**
os.environ["CUDA_VISIBLE_DEVICES"] = = args.gpu_id

**Comment by jindongwang** [comment]
Which folder, which file?

**Comment by ZZhangsm** [comment]
transferlearning/tree/master/code/DeepDG train.py  Line 93
A typo, 'CUDA_VISIBLE_DEVICS' to "CUDA_VISIBLE_DEVICES"

**Comment by jindongwang** [comment]
A big thank you! Update the code!
