### ISSUE TITLE
DIFEX里的可视化傅里叶变换

### ISSUE THREAD

**Issue by xiaopang114** [jindongwang/transferlearning#386]
您好！我在读了您这篇论文后有些启发，想试试该方法能不能迁移到我所研究的领域，因此我想请教您图1这两个样本的傅里叶变换图是如何画出来的？
![difex](https://user-images.githubusercontent.com/118112670/233011868-0fe2d2b3-b42d-43ce-b3e9-de34cd273c50.png)

**Comment by jindongwang** [comment]
@lw0517 有时间可以回答一下这个问题

**Comment by lw0517** [comment]
> 您好！我在读了您这篇论文后有些启发，想试试该方法能不能迁移到我所研究的领域，因此我想请教您图1这两个样本的傅里叶变换图是如何画出来的？ ![difex](https://user-images.githubusercontent.com/118112670/233011868-0fe2d2b3-b42d-43ce-b3e9-de34cd273c50.png)

直接做完傅里叶变幻之后，画对应的幅值和相值就可以了。
t1=np.angle(np.fft.fft(x1,360))
a1=np.abs(np.fft.fft(x1,360))
px1=np.real(np.fft.ifft(np.e**(1j*t1)))
z1=np.real(np.fft.ifft(a1*np.e**(1j*t1)))

**Comment by xiaopang114** [comment]
不好意思再请教一下，按照您的代码我的图像（256×256）得到的幅值图和相值图是256个曲线叠加，如下图所示，您论文中得到的是单一曲线，请问是如何得到的呢？
![1](https://user-images.githubusercontent.com/118112670/233326371-4a1e706c-c4e2-44e7-b87d-8e5fc2721a0e.png)

**Comment by lw0517** [comment]
对于时间序列使用的是一维FFT变换，对于图像使用的是二维FFT变换。我们当前库中提供的变换就是二维的FFT变换。上面回答中提供的是一维的变换。
