### ISSUE TITLE
DIFEX about loss3

### ISSUE THREAD

**Issue by xiaopang114** [jindongwang/transferlearning#389]
您好！论文中loss3表示的是最大化internally-invariant 和mutually-invariant特征的距离，根据代码loss3 = -F.mse_loss(all_z[:, :self.tfbd], all_z[:, self.tfbd:])*self.args.beta，其中self.tfbd=args.bottleneck//2，自定义args.bottleneck=256，请问为什么认为all_z的前半部分是域内不变特征，后半部分是跨域不变特征呢？期待您的解答！

**Comment by jindongwang** [comment]
这个没啥道理可讲；你也可以认为后半部分是域间、前半部分是域内。我们只是简单的认为两部分应该拼起来，至于哪个对应哪个，其实不重要。

**Comment by xiaopang114** [comment]
谢谢老师回复，所以老师您的意思是：通过网络提取出来的特征前后部分都可以认为是跨域特征，只是看自己设定。

**Comment by jindongwang** [comment]
是的

**Comment by xiaopang114** [comment]
好的！谢谢老师回复！
