### ISSUE TITLE
迁移学习DeepDA的代码复现

### ISSUE THREAD

**Issue by 2684957921** [jindongwang/transferlearning#390]
王老师您好！请问迁移学习配套代码DeepDA中运行main.py时出现报错（main.py: error: the following arguments are required: --data_dir, --src_domain, --tgt_domain）这个要怎麼解决，还有就是没有找到DeepDA中数据集的使用方法

**Comment by jindongwang** [comment]
问这个问题说明你不懂python。你应该运行sh文件或者传入对应的参数。
________________________________
发件人: ZZG ***@***.***>
发送时间: Tuesday, May 9, 2023 5:47:09 PM
收件人: jindongwang/transferlearning ***@***.***>
抄送: Subscribed ***@***.***>
主题: [jindongwang/transferlearning] 迁移学习DeepDA的代码复现 (Issue #390)


王老师您好！请问迁移学习配套代码DeepDA中运行main.py时出现报错（main.py: error: the following arguments are required: --data_dir, --src_domain, --tgt_domain）这个要怎N解决，还有就是没有找到DeepDA中数据集的使用方法

―

**Comment by chuzhongmly** [comment]
老师你好，我在复现DeepDA代码时，总是找不到准确的数据集，或者说放不到准确的位置，也详细拜读了data.md，没找到具体的 --data_dir  --src_domain --tgt_domain 三个文件夹参数的值，我尝试用OFFICE31文件下的amazon 和dslr文件带入，程序直接卡死，想请教一下数据集的具体文件格式，md文件中给的链接也下载了，格式都没明确的说明

**Comment by jindongwang** [comment]
说明你不太适合从DeepDA上手。建议先看https://github.com/jindongwang/tlbook-code.

**Comment by chuzhongmly** [comment]
老师，是这样的，我和一楼一样想复现这个代码，就是数据集的具体操作代码中没明确给出，我并不是从事迁移学习的研究，只是想使用它，并应用到自己的研究中。
就最主要的还是您所给的数据集链接，下载解压之后不能直接用于代码之中，想请教一下数据集的具体操作。

**Comment by jindongwang** [comment]
我上面给的code一样可以用的。解压后你要改路径的，我实在不知道怎么帮你，因为这是python基础操作。

**Comment by chuzhongmly** [comment]
![image](https://github.com/jindongwang/transferlearning/assets/50480948/3a0163a2-acb6-4dfc-80e6-c7e6e0823c42)
您理解错我的意思了，比如，上面是OFFICE31的子文件，这三个文件哪个是 --src_domain 和--tgt_domain，还有officehome_resnet50这个文件，解压子文件如下：
![image](https://github.com/jindongwang/transferlearning/assets/50480948/818d906c-6ed9-4384-9051-3b8d85089a02)
而--src_domain 和--tgt_domain明确是文件夹名称而不是文件名称，而dan.sh给出的执行语句的部分为--src_domain Real_World --tgt_domain Art ，就是根本没Art和Real_World 这两个名称的文件夹

**Comment by chuzhongmly** [comment]
其它数据集也有下载，没有dan.sh给的对应文件夹：
![image](https://github.com/jindongwang/transferlearning/assets/50480948/9ba52735-c034-4e5c-8fc2-83d7af02d5b8)

**Comment by jindongwang** [comment]
亲，你连数据集都搞不清楚：office31 officehome是2个不同的数据集，里面有不同的domain。真的建议你看我给你的tlbook-code的代码，那个就是给初学者写的，别再浪费时间了。

**Comment by chuzhongmly** [comment]
好的，我会看的，因为从没使用过这些数据集，多有叨扰
