### ISSUE TITLE
DANN最佳训练结果

### ISSUE THREAD

**Issue by yuninn** [jindongwang/transferlearning#393]
王老师 您好 我对deepDA的训练结果有一些疑惑：
我看训练中DANN这类代码最优准确率结果是源域训练得到目标域最好的识别结果 我可以使用最好的某轮训练结果当做我的算法最优结果吗 这样不是相对于泄漏了目标域的标签信息吗？还是只能训练比如30epoch 取第30epoch的训练结果再来评估识别率呢

**Comment by jindongwang** [comment]
模型评估的问题在迁移学习导论中有讲过，你可以去看。总的来说现在DA评估都是有问题的，会泄露。

**Comment by yuninn** [comment]
好的 谢谢老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jindongwang/transferlearning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月2日(星期五) 下午2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jindongwang/transferlearning] DANN最佳训练结果 (Issue #393)





 
模型评估的问题在迁移学习导论中有讲过，你可以去看。总的来说现在DA评估都是有问题的，会泄露。
