### ISSUE TITLE
方法选择

### ISSUE THREAD

**Issue by ppyourdaddy** [jindongwang/transferlearning#395]
请问为什么选择这几种方法进行测试呢？它们之间有什么内在的联系吗？

**Comment by luhaifeng19947** [comment]
我已经收到您的邮件，会尽快处理。

**Comment by ppyourdaddy** [comment]
我发现我没有讲明白我的问题，我想知道DeepDA这一部分中为什么选择BNM、DAAN等方法，谢谢

**Comment by jindongwang** [comment]
因为这些方法都可以共享deepda这个基础结构，只需要改方法自己的部分。还有很多其他方法没法使用这个结构。
