### ISSUE TITLE
域适应方法的测试集是目标域所有的图片吗

### ISSUE THREAD

**Issue by tangkail** [jindongwang/transferlearning#396]

**Comment by tangkail** [comment]
同时模型训练过程报错runtimeerror：unable to resize file(filename not specified) to the right size

**Comment by jindongwang** [comment]
@tangkail “域适应方法的测试集是目标域所有的图片吗”，这属于迁移学习基础问题，请参考《迁移学习导论》学习基础知识再来问。
报错请提供详细信息，哪个代码、哪一行报错。
