### ISSUE TITLE
options.dim不是可以随意设置吗，只要dim <= m。但试了一下，我的源数据是4000*485，目标数据是2000*485，

### ISSUE THREAD

**Issue by kind-hearted-Tbag** [jindongwang/transferlearning#4]
options.dim不是可以随意设置吗，只要dim <= m。但做了数次实验，我的源数据是4000*485，目标数据是2000*485。也就是说m=485.但是我这里设置dim为104<dim <=485,比如dim=485时，总在“knn_model = fitcknn(Zs',Y_src,'NumNeighbors',1);”报错。设置dim为dim <104，比如dim=100时,一切正常。  这在你的几个算法中都出现同样的问题，是基分类器KNN模型这儿有bug？还是前面有bug？还是我的数据太大（我自己觉得不大），还是程序不健壮？。。。         再次感谢感谢jingongwang关于mu问题的回复！

**Comment by jindongwang** [comment]
你用的matlab版本是什么？可否把错误信息贴上来？

**Comment by kind-hearted-Tbag** [comment]
首先，谢谢回复！

以JDA举例，其他方法类似，dim = 485时
[acc,acc_ite,A] = MyJDA(X_src,Y_src,X_tar,Y_tar,options)
错误使用 ExhaustiveSearcher (line 231)
ExhaustiveSearcher does not accept complex data for built-in distance.
出错 ClassificationKNN/createNSObj (line 368)
                this.NS = ExhaustiveSearcher(X, ...
出错 ClassificationKNN (line 811)
            this = createNSObj(this, this.PrivX);
出错 classreg.learning.FitTemplate/fit (line 243)
            obj = this.MakeFitObject(X,Y,W,this.ModelParams,fitArgs{:});
出错 ClassificationKNN.fit (line 841)
            this = fit(temp,X,Y);
出错 fitcknn (line 267)
this = ClassificationKNN.fit(X,Y,varargin{:});
出错 MyJDA (line 30)
        knn_model = fitcknn(Zs',Y_src,'NumNeighbors',1);

以JDA举例，其他方法类似，dim = 100时
[acc,acc_ite,A] = MyJDA(X_src,Y_src,X_tar,Y_tar,options)
JDA+NN=0.7724
JDA+NN=0.7724
JDA+NN=0.8291
JDA+NN=0.8470
JDA+NN=0.7537
.。。。
一切正常

我的数据如下


matlab版本为：matlab2014b。
谢谢！

**Comment by kind-hearted-Tbag** [comment]
我的数据如下：
![image](https://user-images.githubusercontent.com/24237829/32412950-00779998-c241-11e7-9e52-42916e660711.png)

**Comment by jindongwang** [comment]
错误信息说的是，fitcknn不接受复数。我猜想是经过一轮算法迭代，出现了complex data。你可以试着在前面加一个real()，看能不能把数据转化成实数。

**Comment by kind-hearted-Tbag** [comment]
我加了俩句，Zs = real(Zs)，Zt = real(Zt)。错误消失，但生成A矩阵变成了complex double类型。也不知道以后的处理继续用real（）函数这样暴力处理的方式，会不会产生想不到的消极效果。
谢谢Doctor Wang的回答！

**Comment by jindongwang** [comment]
Doctor这个称呼暂时不敢当！能解决问题就好，暂时还没有比较好的方法
