### ISSUE TITLE
PACS数据集

### ISSUE THREAD

**Issue by Y-J-Zhang** [jindongwang/transferlearning#411]
王老师您好，请问您还有PACS的数据备份么，markdown里的链接进不去，您在之前issue里提供的新连接也用不了了。能麻烦您再提供下数据集吗，非常感谢:)

**Comment by luhaifeng19947** [comment]
我已经收到您的邮件，会尽快处理。

**Comment by jindongwang** [comment]
@Y-J-Zhang 你可以从这个链接下载PACS数据集：https://wjdcloud.blob.core.windows.net/dataset/PACS.zip

另外你说的链接打不开的情况，能麻烦你具体说一下是哪个链接吗？我好改一下。

**Comment by Y-J-Zhang** [comment]
> @Y-J-Zhang 你可以从这个链接下载PACS数据集：https://wjdcloud.blob.core.windows.net/dataset/PACS.zip
> 
> 另外你说的链接打不开的情况，能麻烦你具体说一下是哪个链接吗？我好改一下。

多谢王老师，可以下载了。之前readme里链接我打不开。很抱歉这么晚才回复。
