### ISSUE TITLE
有个小疑问

### ISSUE THREAD

**Issue by huangwentao123** [jindongwang/transferlearning#414]
DA子问题下的方法 和 notebook 下deep_transfer_tutorial.ipynb 中的方法，都是使用torchvision 的预训练模型
我的理解，域适应不应该使用原始训练数据和目标域数据嘛？ 
如`resnet = models.resnet101(pretrained=True)`是使用imagenet数据集
示例代码使用了office31，是单纯做个示例？还是英文paper里评价算法结果是office
但关于da 的 source data 是否应该是model的训练数据集  向老师提问

**Comment by jindongwang** [comment]
用预训练模型基本上是做cv相关实验的标准操作，不用也没问题的，但用了结果更好。

**Comment by huangwentao123** [comment]
还想想问一下，source data 难道不应该是预训练模型的训练集吗？如果随意指定，并计算和target的分布距离，会不会导致结果不好呢？或者说用office31 也是paper实验的约定俗成

**Comment by jindongwang** [comment]
Office31是迁移学习和domain adaptation的基准数据集之一。有关更多基础知识和数据集，请参考迁移学习导论一书。
