### ISSUE TITLE
Deep DG

### ISSUE THREAD

**Issue by 213s** [jindongwang/transferlearning#415]
您好，我想知道代码中超参数是如何确定的呢？谢谢！

**Comment by jindongwang** [comment]
网格调参调出来的。

**Comment by 213s** [comment]
代码中有实现吗

**Comment by jindongwang** [comment]
网格调参不需要实现，这属于深度学习基础。

**Comment by 213s** [comment]
是不是深度学习包里自带的，调用就行是吧

**Comment by jindongwang** [comment]
你不如先学好深度学习，再来看这个repo吧，心急吃不了热豆腐。

**Comment by 213s** [comment]
那代码里是不是只有学习率需要自己设置，其它超参数都是网格调参实现的？

**Comment by 213s** [comment]
那有没有推荐深度学习的视频呢，谢谢大佬

**Comment by jindongwang** [comment]
https://github.com/allmachinelearning/MachineLearning

**Comment by dawin2015** [comment]
> https://github.com/allmachinelearning/MachineLearning

Prof. Wang 人好，还推荐学习资料，点赞 :)
