### ISSUE TITLE
MMD距离 backward问题

### ISSUE THREAD

**Issue by huangwentao123** [jindongwang/transferlearning#416]
个人理解，MMD距离应该是描述分布的“距离”，而不是分布中单个数据采样点的。
在深度学习里使用，就类似batch size的批处理，从分布中期望做到均匀采样。
但DeepDA下main.py 中line 132 似乎只是单纯个体数据间的距离 loss

这样不会受到采样点的影响吗？还是说任务base model 提取特征后，认为特征在特征空间就是均匀的

**Comment by jindongwang** [comment]
这个是实现和理想的差异：在深度学习里面只能这么实现。

**Comment by wlh-coconut** [comment]
你好，这是贺雯丽的自动回复，您的信息已经收到。祝身体健康，万事如意！                                                      贺雯丽

**Comment by luhaifeng19947** [comment]
我已经收到您的邮件，会尽快处理。
