### ISSUE TITLE
关于TransferNet中source_clf计算的疑问

### ISSUE THREAD

**Issue by dywaneWang** [jindongwang/transferlearning#418]
老师您好。我有一个疑问：如果有bottleneck，为什么不需要重新计算source_clf？我看文章[Tzeng et al., 2014]里面计算分类损失是在Adapt层之后。还是说有哪些地方我理解得不对？麻烦老师和各位大佬解答一下，谢谢。

**Comment by jindongwang** [comment]
因为有feature就不用重新算了，这是基础问题。
