### ISSUE TITLE
对比算法的复现缺少部分流程

### ISSUE THREAD

**Issue by 95264** [jindongwang/transferlearning#420]
对于diffx代码的复现，我们已经不存在任何疑问，代码的运行效果非常好，但我们尝试将您论文手稿中提到的其他对比算法进行应用时，遇到了一些困难。最为明显的是，缺少其中一种的调用示例。
![image](https://github.com/jindongwang/transferlearning/assets/152259509/e07517f6-38ea-42c1-bc9e-211506be5f71)

**Comment by jindongwang** [comment]
没有文章开源会把对比算法一起开源的。我们在DeepDG里面已提供了绝大多数对比方法的实现，可以参考：https://github.com/jindongwang/transferlearning/tree/master/code/DeepDG
