### ISSUE TITLE
程序显示没有loss_funcs模块

### ISSUE THREAD

**Issue by xugliang** [jindongwang/transferlearning#421]
![错误](https://github.com/jindongwang/transferlearning/assets/150440941/f7665304-f204-4252-8f9a-48b5572ef4b9)

请问DeepDA为什么会显示没有loss_funcs模块，是版本导致的吗？应该怎样改写呢？

**Comment by jindongwang** [comment]
这个应该是你pycharm的问题吧，你可以按照教程运行一下，能运行就没问题。
