### ISSUE TITLE
Our new test-time adaptation algorithm for segmentation 

### ISSUE THREAD

**Issue by lwpyh** [jindongwang/transferlearning#423]
Hi jindong,

Thank you for your great collection of transfer learning papers and tutorials. Our new AAAI 24 paper "Relax Image-Specific Prompt Requirement in SAM: A Single Generic Prompt for Segmenting Camouflaged Objects" has just released. It utilizes a training-free test-time adaptation approach to relax the instance-specific prompts requirment in SAM. Here is our project page: https://lwpyh.github.io/GenSAM/, and here is our paper page: https://arxiv.org/abs/2312.07374. Could you please consider add our paper in the list?

Best,

**Comment by jindongwang** [comment]
@lwpyh Thanks for the suggestion! Indeed, I suggest you make a PR of my repo to include your papers. If you don't know how to do it, then I can do it for you.

**Comment by lwpyh** [comment]
> @lwpyh Thanks for the suggestion! Indeed, I suggest you make a PR of my repo to include your papers. If you don't know how to do it, then I can do it for you.

Thank you, I have made a PR.

**Comment by jindongwang** [comment]
Thank you for your contribution.
