### ISSUE TITLE
关于transferlearning/code /DeepDA的模型代码读取

### ISSUE THREAD

**Issue by susan1314** [jindongwang/transferlearning#425]
王老师，您好。在transferlearning/code /DeepDA 文件夹下，我找DSAN、DANN都未看到模型和代码，对应transferlearning/code /DeepGA 是有模型和代码的。是因为DeepDA已经不维护了吗还是我没准确找到模型和代码？

**Comment by jindongwang** [comment]
DeepDA在维护呀，代码在DeepDA下其他文件夹里，你可以看看。

**Comment by susan1314** [comment]
> DeepDA在维护呀，代码在DeepDA下其他文件夹里，你可以看看。
谢谢王老师回复！
![12 26](https://github.com/jindongwang/transferlearning/assets/31062928/cb2852be-f338-4439-8b56-7bfcc3cb878b)
我还是未找到相应的代码文件，在DeepDA的其他文件夹里只有损失函数，但是DANN应该是对抗迁移神经网络，我想应该不能靠替换损失函数生成吧。此外，如果可以还想问问王老师（因为算法很多，不知道那种更适合我的问题）：
最近看迁移学习有领域泛化和领域适应这类种概念，请问能否适用于有监督学习？我现在的问题主要有两个：
前提：独立不重复的标签组合为一类样本。
1）某类样本数量少，如果直接训练会导致这类样本正确率不高，想通过迁移学习提升。
2）多标签学习中，测试集存在与训练集不同的标签组合，能不能通过迁移学习来适应这种未见标签组合。
因为不是图像数据，输入是一维的序列数据，输出是多标签组合。从描述上似乎很多算法都能适用，但是哪个更契合呢。

**Comment by jindongwang** [comment]
dann只是这个包的一个算法，主要代码都在main.py等其他py文件中，一共也没几个文件，你可以好好看看。我们有详细的readme告诉你怎么跑这个算法，不要上来就问。
其他问题我不负责回答，只回答代码库的问题。
