### ISSUE TITLE
code add

### ISSUE THREAD

**Issue by Zzzhangxd** [jindongwang/transferlearning#428]
# 王老师，您好！

- 请问可以提供DeepDA中特征可视化和混淆矩阵，A-distance等相关代码吗？

**Comment by jindongwang** [comment]
这个无法提供了，代码早就没了，可以自己写一下

**Comment by Zzzhangxd** [comment]
- 首先谢谢王老师的回复
- 我最近看到这个代码仓库里有几乎即插即用的输出混淆矩阵，t-SNE, A-distance的代码，如果有需要的同学可以参考一下https://github.com/val-iisc/SDAT/tree/main/common/utils/analysis
