### ISSUE TITLE
有关于在使用DG中DANN方法中遇到的问题

### ISSUE THREAD

**Issue by dwXzd** [jindongwang/transferlearning#429]
首先感谢您提供了如此便捷开源的代码，我在使用DG中的DANN训练PACS训练集时，我尝试注释掉DANN中的discriminator部分代码，使其成为一个简单的分类网络，但我发现去除discriminator后的DANN在训练PACS时出现了准确率很高，甚至效果比原本的DANN网络还要好，我想咨询一下这是由于采取了训练好的backbone网络参数导致的还是什么原因？
这是去除掉discriminator后的DANN训练结果
![image](https://github.com/jindongwang/transferlearning/assets/56581786/34f26d71-3819-42d0-aac3-0d3d5e97045e)
这是没有去除discriminator的DANN训练结果
![image](https://github.com/jindongwang/transferlearning/assets/56581786/77743da7-5c98-429f-b5bd-b962fe605d69)

**Comment by DocNR111** [comment]
您好，我想问一下您的问题解决了吗？可否交流一下。我发现我在用DANN训练的时候测试的精度会出现周期性的降低。

<img width="1820" height="650" alt="Image" src="https://github.com/user-attachments/assets/c858eb77-a7fe-4530-ba84-67949023bee1" />不知道是为什么，您有出现过吗？

**Comment by luhaifeng19947** [comment]
我已经收到您的邮件，会尽快处理。

**Comment by wlh-coconut** [comment]
你好，这是贺雯丽的自动回复，您的信息已经收到。祝身体健康，万事如意！                                                      贺雯丽
