### ISSUE TITLE
是否需要进行微调？

### ISSUE THREAD

**Issue by dawin2015** [jindongwang/transferlearning#433]
首先，感谢王老师出色的开源贡献。目前我想设计一个端到端的深度迁移学习模型，参考notebooks/deep_transfer_tutorial.ipynb。里面主要是两部分，第一部分是微调，第二部分是领域适应。

问题：
- 第一部分的微调模型是否在第二部分使用？看代码是第二部分直接基于resnet50进行训练了，没有使用第一部分微调的模型，不知道理解是否正确？
- 如果第一个问题是正确，是否直接使用第二部分进行领域适应即可，没必要进行微调了？

希望能抽空答疑，感谢王老师！

**Comment by jindongwang** [comment]
一般你能微调效果好就不需要DA了，可以先调一下看看。

**Comment by dawin2015** [comment]
明白。感谢王老师的回复
