### ISSUE TITLE
王老师您好，Domain Generalization for Activity Recognition via Adaptive Feature Fusion请问这篇论文的代码具体在哪个文件夹里？找了很久没找到

### ISSUE THREAD

**Issue by goesfor** [jindongwang/transferlearning#438]
**Before you open an issue**
If it's code running error, maybe you want to check the python or pytorch version before submitting an issue.

**Describe the bug**

**To Reproduce**
Where is this bug happen?

**Screenshots**

**Comment by jindongwang** [comment]
这个应该没开源吧，你可以给一作发邮件
