### ISSUE TITLE
A question about Resnet structure in DAN

### ISSUE THREAD

**Issue by HyoKong** [jindongwang/transferlearning#45]
Thank u very much for providing a nice reference. After reading the article of DAN and python code you provided, i have a deeper comprehension about the article. 

My question, generally speaking, is that the deep learning structure you choose is Resnet, which is different from the original article. But i have no idea about which layers have you **fixed, fine-tuned and tailored**. Can you propose a detailed explanation?

Thank u very much!

**Comment by jindongwang** [comment]
@HyoKong Good question!
However, the original authors of DAN paper only fine-tune the last layer of the network in their codes (github/thuml), which is not consistent with their paper. More concretely, it is MK-MMD + DDC. We don't know why.

**Comment by HyoKong** [comment]
@jindongwang Got it, thank you~

**Comment by shopeth** [comment]
@jindongwang thank you for the insight. It seems this code is adapting all layers of Resnet with MMD? Could you please confirm?

**Comment by ChengYeung1222** [comment]
Are the params in SharedNet loaded by pre_trained .pth and then fine-tuned in training step?Or just loaded and frozen when training DAN?

**Comment by jindongwang** [comment]
load and fine-tune. You need to freeze the layers accordingly.

**Comment by ChengYeung1222** [comment]
> load and fine-tune. You need to freeze the layers accordingly.

Understood. Thank U.
