### ISSUE TITLE
NaN matrix produced by TCA python code

### ISSUE THREAD

**Issue by zzbslayer** [jindongwang/transferlearning#46]
```
...
72    n_eye = m if self.kernel_type == 'primal' else n
73    a, b = np.linalg.multi_dot([K, M, K.T]) + self.lamb * np.eye(n_eye), np.linalg.multi_dot([K, H, K.T])
74    w, V = scipy.linalg.eig(a, b)
...
```

When I use the code, the value in matrix K, M, H is so small that the result of **line 73** is two matrix of NaN. Then the program stops due to the NaN matrix.

So does this mean some dataset might be unable to use TCA code ? Maybe I should do some pre-process with my dataset ?

**Comment by zzbslayer** [comment]
[
![nan](https://user-images.githubusercontent.com/24487419/48484732-dfd3e100-e851-11e8-992d-05b7701d8971.png)
](url)

**Comment by jindongwang** [comment]
@zzbslayer Could you please send me your data? It's better in the Xs, Ys, Xt, Yt format

**Comment by jindongwang** [comment]
@zzbslayer I know what happened. It's not the problem of too small values, it's the divide by 0 issue during the normalization of X and Z (basically your data contains too many 0s):

Line 64: X = `np.dot(X, np.diag(1 / (np.sum(X ** 2, axis=0) ** 0.5)))`
Line 78 `Z = np.dot(Z, np.diag(1 / (np.sum(Z ** 2, axis=0) ** 0.5)))`

If you uncomment these two lines, TCA will work.
You can replace these two lines with other normalization methods.

**Comment by zzbslayer** [comment]
@jindongwang  Oh so surprising.. I really appreciate it !
