### ISSUE TITLE
关于Benchmark中的实验结果

### ISSUE THREAD

**Issue by DengBinbin** [jindongwang/transferlearning#47]
你好，我想请问下benchmark中的那些对比的实验结果，是你复现之后的结果吗？GFK、TCA在Office-31任务上和论文中公布的结果（DCORAL有和GFK、TCA等对比）有一定的出入，想请教下，谢谢！

**Comment by jindongwang** [comment]
因为这些方法都要设定一些参数，不同的参数，结果自然不同。我这里公布的结果都来自于其他和它对比的文章，可能参数与原始文章不一样，所以结果也有不同。

**Comment by DengBinbin** [comment]
谢谢回复，还有一个问题，关于DaNN (Domain Adaptive Neural Network, PRICAI-14)和DANN（Domain-Adversarial Training of Neural Networks (JMLR-16)），在Office-31任务上是不是给的DaNN的结果，我看只有39.3的Average，不像是DANN的结果，另外Office-31数据集的那些结果也是收集来自多篇不同论文吧？看你没有注明来源。

**Comment by jindongwang** [comment]
是的，这个DANN应该是DaNN，笔误

**Comment by DengBinbin** [comment]
非常感谢！
