### ISSUE TITLE
出错 MyJGSA (line 93)  ， [W,~] = eigs(Smax, Smin+1e-9*eye(2*nst), dim, 'LM');我试了几次，总是有问题

### ISSUE THREAD

**Issue by kind-hearted-Tbag** [jindongwang/transferlearning#5]
错误信息如下，希望大家看一下，谢谢！
错误使用 eigs/checkInputs/LUfactorB (line 952)
B 为奇异矩阵。
无法计算指定的特征值，因为存在无穷大的特征值。

出错 eigs/checkInputs (line 791)
            [LB,UB,ppB,qqB,dgB] = LUfactorB;

出错 eigs (line 94)
[A,Amatrix,isrealprob,issymA,n,B,classAB,k,eigs_sigma,whch, ...

出错 MyJGSA (line 93)
 [W,~] = eigs(Smax, Smin+1e-9*eye(2*nst), dim, 'LM');

**Comment by jindongwang** [comment]
换别的参数组合呢？

**Comment by kind-hearted-Tbag** [comment]
可以给出这几个方法默认的options吗，参考一下。参数比较多，我又不是太懂。谢谢！

**Comment by jindongwang** [comment]
MyJGSA方法的参数请看原文及作者源码：https://www.uow.edu.au/~jz960/#Datasets
其他方法也基本上按照各自的原文来做的。
其实我觉得你出那个错，就随便再试试几个参数组合，看看是数据的问题还是代码的问题就可以了。

**Comment by kind-hearted-Tbag** [comment]
![image](https://user-images.githubusercontent.com/24237829/32475304-0d12c56c-c3ac-11e7-9939-769c12579bce.png)  原文我看了一下，只有五个参数，只给出了俩个的值，而代码中有7个参数

**Comment by jindongwang** [comment]
作者的源码里有参数

**Comment by kind-hearted-Tbag** [comment]
好的，我再看看。谢谢！

**Comment by kind-hearted-Tbag** [comment]
谢谢你的指点，又学到了许多。  可能我的数据没归一化。  原文代码用到了normc()函数，比如Xs = normc（Xs）等，对输入数据做相应处理后，错误消失。 再次感谢！
