### ISSUE TITLE
请问MEDA的结果是从哪里得到的

### ISSUE THREAD

**Issue by wyf0912** [jindongwang/transferlearning#52]
比如论文中并没有image-clef da的结果
谢谢~

**Comment by jindongwang** [comment]
MEDA是一个通用的方法，论文中由于篇幅限制，只展示了部分数据集的结果。详细的结果我们在附件中(论文的某一页下面有一个脚注)进行了展示。如果你有兴趣，我也可以将MEDA跑这些数据集的参数公开。

**Comment by jindongwang** [comment]
Office-home：lambda=4.5，dimension=200
ImageCLEF: lambda=4.5, dimension=60
Office31: lambda=4.5, dimension=50
其他参数和MEDA的demo中一致
