### ISSUE TITLE
DaNN.py处的代码是不是有个地方写错了导致有点理解上的误导？

### ISSUE THREAD

**Issue by DianLyu** [jindongwang/transferlearning#54]
第19行，`x_src = self.layer_hidden(x_src_mmd)`
这里如果没有理解错的话应该是`y_src = self.layer_hidden(x_src_mmd)`吧？
根据main.py里train函数（第41行）`y_src, x_src_mmd, x_tar_mmd = model(data, x_tar)`里来看也应该是这样，虽然只是个命名的问题不会影响什么，但是改成y_src是不是更容易理解一点，前后也比较对应？

**Comment by jindongwang** [comment]
@DianLyu 感谢建议！已修改

**Comment by DianLyu** [comment]
> @DianLyu 感谢建议！已修改

王老师客气了！您的这些教程与研究我获益匪浅！
