### ISSUE TITLE
DAN and DDC中的load_pretrain(model)函数 

### ISSUE THREAD

**Issue by WUzhusihan** [jindongwang/transferlearning#56]
你好大神，我是在知乎上请教你的本科学生，来这边继续提问。有关我的精度100的问题，已经在issue里面找到答案了
除此之外，我觉得在DAN and DDC中的load_pretrain(model)函数是否有问题
#     for k, v in model_dict.items():
#          if not "cls_fc" in k:
#                 model_dict[k] = pretrained_dict[k[k.find(".") + 1:]]
这是您的源代码，我跑出来会出现num_batches_tracked错误，查了一些资料，我做了如下修改
-------->
#  1    pretrained_dict = {k: v for k, v in pretrained_dict.items() if k in model_dict}
#  2   pretrained_dict ={ k:v for k,v in pretrained_dict.items() if k in model_dict and v.size() == model_dict[k].size() }
#  3  model_dict.update(pretrained_dict)
#  4  model.load_state_dict(model_dict)
其中1 2 步做任意一个即可。我刚接触python以及pytorch，不知道是否与环境有很大关系 。这里提供一个可能是解决方案的方法。

**Comment by WUzhusihan** [comment]
1

**Comment by WUzhusihan** [comment]
试了一些DDC，数据是W->D，跑出来只有不到50%的accuracy，是不是我哪里弄错了呢

**Comment by ChengYeung1222** [comment]
我也照着[How to load part of pre trained model?](https://discuss.pytorch.org/t/how-to-load-part-of-pre-trained-model/1113/33)这上面提到的修改方法尝试过滤KeyError的参数，同样也不能解决，现在也只能降级PyTorch了

**Comment by ChengYeung1222** [comment]
然后降级CUDA以后就会出现这个警告：
`GPU0 TITAN V which requires CUDA_VERSION >= 9000 for optimal performance and fast startup time, but your PyTorch was compiled with CUDA_VERSION 8000. Please install the correct PyTorch binary using instructions from http://pytorch.org`
