### ISSUE TITLE
DDC中参数frozen

### ISSUE THREAD

**Issue by zhaoguangyao** [jindongwang/transferlearning#57]
王老师您好，在阅读您的迁移学习教程的时候，个人认为DDC和DAN的前几层参数应该设置为frozen。
但是您的代码带load resnet50模型的时候，只是固定的weight中data的requires_grad=False.
这样是不是固定不住参数呢？
我认为实际上应该吧weight.requies_grad=False.
比如conv1的参数，如图：
![ddc1](https://user-images.githubusercontent.com/19162817/53676393-9910d680-3cdc-11e9-9b16-14e6400cb240.png)
![ddc2](https://user-images.githubusercontent.com/19162817/53676396-a4fc9880-3cdc-11e9-85b6-5f8afb310091.png)
可能理解的不是很准确，请指教。

**Comment by jindongwang** [comment]
我觉得你可能说的对。不妨先做个实验验证一下，哪种是正确的？

在2019年3月2日 11:10，Guangyao ZHAO<notifications@github.com><mailto:notifications@github.com> 写道：

王老师您好，在阅读您的迁移学习教程的时候，个人认为DDC和DAN的前几层参数应该设置为frozen。
但是您的代码带load resnet50模型的时候，只是固定的weight中data的requires_grad=False.
这样是不是固定不住参数呢？
我认为实际上应该吧weight.requies_grad=False.
比如conv1的参数，如图：
weight.requires_grad<https://zhaokuanyew.nos-eastchina1.126.net/DDC1.png>
weight.data.requires_grad<https://zhaokuanyew.nos-eastchina1.126.net/DDC2.png>

**Comment by DianLyu** [comment]
您好，想请教下您说的这个问题，在王老师的DAN代码中是在何处呢？我没有找到王老师有对DAN load resnet50时对层进行操作呀？还请指点一下 @zhaoguangyao

**Comment by zhaoguangyao** [comment]
> 您好，想请教下您说的这个问题，在王老师的DAN代码中是在何处呢？我没有找到王老师有对DAN load resnet50时对层进行操作呀？还请指点一下 @zhaoguangyao

就是在加载模型参数的时候，117行model = load_pretrain(model)这个函数就是加载残差网络的模型的。

我的问题就是发现：
这个加载resnet50的方法，只是覆盖了模型中每一层的weight，使weight中的data的参数requires_grad=Fasle。
但是pytorch1.0中应该把每一层中weight的requires_grad=False,这样才frozen所有的参数。（如上图）
我也很困惑，pytorch中为什么会有多个requires_grad参数。

经过简单测试，在pytorch1.0中只固定weight.data.requires_grad=False无法frozen参数。

这个问题好像是pytorch版本的问题，可能在王老师使用的pytorch 0.3中不存在这个问题吧。

**Comment by DianLyu** [comment]
> > 您好，想请教下您说的这个问题，在王老师的DAN代码中是在何处呢？我没有找到王老师有对DAN load resnet50时对层进行操作呀？还请指点一下 @zhaoguangyao
> 
> 就是在加载模型参数的时候，117行model = load_pretrain(model)这个函数就是加载残差网络的模型的。
> 
> 我的问题就是发现：
> 这个加载resnet50的方法，只是覆盖了模型中每一层的weight，使weight中的data的参数requires_grad=Fasle,这种做法无法frozen参数。
> 
> pytorch1.0中应该把每一层中weight的requires_grad=False,这样才frozen所有的参数。（如上图）
> 我也很困惑，pytorch1.0中为什么会有多个requires_grad参数。
> 
> 经过简单测试，在pytorch1.0中只固定weight.data.requires_grad=False无法frozen参数。
> 
> 这个问题好像是pytorch版本的问题，可能在王老师使用的pytorch 0.3中不存在这个问题吧。

明白了，多谢指教！
