### ISSUE TITLE
KeyError: 'bn1.num_batches_tracked'

### ISSUE THREAD

**Issue by Jacob12138xieyuan** [jindongwang/transferlearning#58]
KeyError                                  Traceback (most recent call last)
<ipython-input-14-c438d9ae2c55> in <module>()
    115     if cuda:
    116         model.cuda()
--> 117     model = load_pretrain(model)
    118     for epoch in range(1, epochs + 1):
    119         train(epoch, model)

<ipython-input-14-c438d9ae2c55> in load_pretrain(model)
     48     for k, v in model_dict.items():
     49         if not "cls_fc" in k:
---> 50             model_dict[k] = pretrained_dict[k[k.find(".") + 1:]]
     51     model.load_state_dict(model_dict)
     52     return model

KeyError: 'bn1.num_batches_tracked'

**Comment by easezyc** [comment]
pytorch=0.3.1 not 0.4 or 1.0
