### ISSUE TITLE
关于MyARTL,总是有些问题。

### ISSUE THREAD

**Issue by kind-hearted-Tbag** [jindongwang/transferlearning#6]
![image](https://user-images.githubusercontent.com/24237829/32492281-affd0c18-c3f4-11e7-893d-07bf84241d88.png)
。。。
每次迭代没有变化。
大家有没有该算法代码的最原始出处？
请教大家。谢谢！

**Comment by jindongwang** [comment]
迭代没有变化也是正常的，你不妨换个参数试试？
原代码的出处是作者Mingsheng Long的主页，你可以去看看

**Comment by kind-hearted-Tbag** [comment]
我又试了一下，原文代码好像没有迭代部分，我的数据Acc=0.9284。而您的代码有一个迭代部分，通过T设置迭代次数，但每次迭代就像我贴的图片一样，没有变化，并且Acc=0.0701(比较离谱)。我对比了一下，在Construct MMD matrix这块，原码有训练一个model。而您的代码没有model，加入了一个N，是希望每次迭代变化吗？但是迭代没有变化，我觉得是代码可能有问题，导致迭代环节没有变化。

**Comment by jindongwang** [comment]
好的，我稍后看一下，有可能上传的时候出问题了，在我这里是没问题的。
ARTL文章中提到了迭代，迭代精度会更高。

________________________________
祝好
王晋东

发件人： kind-hearted-Tbag<mailto:notifications@github.com>
发送时间： 2017-11-08 16:09:56
收件人：  jindongwang/transferlearning<mailto:transferlearning@noreply.github.com>
抄送：  Jindong Wang<mailto:jindongwang@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [jindongwang/transferlearning] 关于MyARTL,总是有些问题。 (#6)

我又试了一下，原文代码好像没有迭代部分，我的数据Acc=0.9284。而您的代码有一个迭代部分，通过T设置迭代次数，但每次迭代就像我贴的图片一样，没有变化，并且Acc=0.0701(比较离谱)。我对比了一下，在Construct MMD matrix这块，原码有训练一个model。而您的代码没有model，加入了一个N，是希望每次迭代变化吗？但是迭代没有变化，我觉得是代码可能有问题，导致迭代环节没有变化。

**Comment by jindongwang** [comment]
@kind-hearted-Tbag 我刚更新了一下ARTL方法的代码，如果你还在用的话，可以再看一下有没有问题。我是基于我目前正在用的代码做的，应该是可以跑的。

**Comment by kind-hearted-Tbag** [comment]
非常感谢！  现在好了，就45和51行有点小问题，n_neighbor改为p，mu是多余的。  现在正确率是0.9299（挺好），但每次迭代任然没有变化，是不是所有的数据都这样。这方面我会继续尝试的。
