### ISSUE TITLE
why is feature  255 Dimensions in your Resnet-50 example dataset?

### ISSUE THREAD

**Issue by jiangzhubo** [jindongwang/transferlearning#60]
I download your example dataset: OFFICE-31 resnet 50 features, however they are only 255 dimensions and no lable, however, you mention it in readme that the features should be 2048 dimensions and last colunmn should be label. May i ask what happened ?

**Comment by jindongwang** [comment]
@jiangzhubo Thanks for the feedback. May I ask from which link that you download the features? I checked the link that I provided in this repo: 

https://pan.baidu.com/s/1UoyJSqoCKCda-NcP-zraVg?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=#list/path=%2F&parentPath=%2Fsharelink625495253-203006936129457

It is correct.
