### ISSUE TITLE
No class names are found in input labels.

### ISSUE THREAD

**Issue by jiangzhubo** [jindongwang/transferlearning#61]
when i run the matlab code with my own features for MEDA, classes is binary, and feature dim is 2944, i run the demo code in matlab folder without change any parameters in 'option', a error happens:

Error using ClassificationLinear.prepareData (line 553)
No class names are found in input labels.

Error in classreg.learning.FitTemplate/fit (line 213)
                    this.PrepareData(X,Y,this.BaseFitObjectArgs{:});

Error in ClassificationLinear.fit (line 374)
            [varargout{1:nargout}] = fit(temp,X,Y);

Error in fitclinear (line 164)
    [varargout{1:nargout}] = ClassificationLinear.fit(X,y,RemainingArgs{:});

Error in estimate_mu>adist (line 30)
    model_linear = fitclinear([Xs;Xt],[Yss;Ytt],'learner','svm');

Error in estimate_mu (line 10)
        adist_i = adist(Xsi,Xtj);

Error in MEDA (line 93)
        mu = estimate_mu(Xs',Ys,Xt',Cls);

Error in demo_office_caltech_surf (line 23)
        [Acc,~,~,~] = MEDA(Xs,Ys,Xt,Yt,options);
Can you tell me what the problem?

**Comment by jindongwang** [comment]
Did you check you own inputs to MEDA, i.e. Xs, Ys, Xt, Yt, to make sure it satisfies the inputs of the method?

**Comment by jindongwang** [comment]
@jiangzhubo Did you solve the problem?

**Comment by jiangzhubo** [comment]
@jindongwang  thanks for replying, i have check it clearly my train code  and data shape are following , 
<img width="268" alt="Screenshot 2019-04-03 at 2 11 51 PM" src="https://user-images.githubusercontent.com/26918997/55456801-932f4d80-561a-11e9-9b6b-b53ab3192b51.png">
<img width="605" alt="Screenshot 2019-04-03 at 2 11 21 PM" src="https://user-images.githubusercontent.com/26918997/55456802-93c7e400-561a-11e9-9db9-2ee1f96db6d0.png">
the error is still there , and my matlab is 2018B

**Comment by jindongwang** [comment]
@jiangzhubo I still cannot see what's wrong. Maybe you can dive into the code, and try to debug it to see what's going on. I will be here to discuss with you.

**Comment by jindongwang** [comment]
Did your problem solved?

**Comment by Nneeiill** [comment]
I met the same error, did this issue have been solved?

**Comment by Yan9564** [comment]
I met the same error too, 
![图片](https://user-images.githubusercontent.com/62475249/116682570-00239600-a9e1-11eb-9a2f-44c46771881e.png)
![图片](https://user-images.githubusercontent.com/62475249/116682607-087bd100-a9e1-11eb-911e-57dedbf34ad1.png)

**Comment by jindongwang** [comment]
Can Xs, Ys, Xt, Yt be accessed? Which line is wrong?
![image](https://user-images.githubusercontent.com/6158206/116683208-d9b22a80-a9e1-11eb-8b88-95882eb4077a.png)
