### ISSUE TITLE
JDA 和 BDA的论文问题

### ISSUE THREAD

**Issue by burgess666** [jindongwang/transferlearning#62]
大神你好，看了JDA和BDA的论文，想问一下为什么使用NN作为分类器，而不用SVM？期待解惑。谢谢

**Comment by jindongwang** [comment]
用什么分类器都是可以的。详细比较可以看我的MEDA文章

在2019年4月9日 08:08，Kaiqiang Huang<notifications@github.com><mailto:notifications@github.com> 写道：

大神你好，看了JDA和BDA的论文，想问一下为什么使用NN作为分类器，而不用SVM？期待解惑。谢谢

**Comment by burgess666** [comment]
感谢指点，我这几天看一下。多谢
