### ISSUE TITLE
baidu links are a problem

### ISSUE THREAD

**Issue by kowshikthopalli** [jindongwang/transferlearning#63]
Hi. Thank you for maintaining this amazing repo for domain adaptation and also giving us pre-trained resnet features and models.
I am trying to download the visda features/model but I am unable to do it as baidu asks me to install some software and log-in which requires chinese phone number.

I was wondering if you would be kind enough to upload those to other cloud or send just the fine tuned resnet-50 models of Visda, ImageCLEF, office home to me via email (kthopall@asu.edu). I will extract the features in my local system.
Thanks a lot

**Comment by jindongwang** [comment]
I'll provide an alternative for downloading these files in another cloud service.

Currently, you can try to download the files from Baidu one by one, see if that helps.

I'll tell you when another cloud service is ready.

On 4/18/2019 09:40，Kowshik Thopalli<notifications@github.com><mailto:notifications@github.com> wrote：

Hi. Thank you for maintaining this amazing repo for domain adaptation and also giving us pre-trained resnet features and models.
I am trying to download the visda features/model but I am unable to do it as baidu asks me to install some software and log-in which requires chinese phone number.
I was wondering if you would be kind enough to upload those to other cloud or send just the fine tuned models of Visda, ImageCLEF, office home to me via email (kthopall@asu.edu<mailto:kthopall@asu.edu>).
Thanks

**Comment by jindongwang** [comment]
@kowshikthopalli I have added Mega links to all the datasets. Please check the new updated md file.
