### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by JJMLeo** [jindongwang/transferlearning#64]
代码路径：`code/traditional/JDA/JDA.py`
1、运行代码JDA.py报错 `AttributeError:'JDA' object has no attribute 'Ys'`，定位到问题行为82行。
2、82行代码`e[np.where(tt == True)] = 1 / len(Ys[np.where(self.Ys == c)])`
**self.Ys**应改为**Ys**，因为在定义类JDA时，self中没有Ys。
3、改后运行结果：
`JDA iteration [1/10]: Acc: 0.3713
JDA iteration [2/10]: Acc: 0.3687
JDA iteration [3/10]: Acc: 0.3660
JDA iteration [4/10]: Acc: 0.3642
JDA iteration [5/10]: Acc: 0.3624
JDA iteration [6/10]: Acc: 0.3660
JDA iteration [7/10]: Acc: 0.3678
JDA iteration [8/10]: Acc: 0.3678
JDA iteration [9/10]: Acc: 0.3695
JDA iteration [10/10]: Acc: 0.3660
0.3659839715048976`

**Comment by jindongwang** [comment]
@JJMLeo 感谢指正，已修改代码。我这边运行结果为0.46左右
