### ISSUE TITLE
TCA.py memory error

### ISSUE THREAD

**Issue by JarvisXX** [jindongwang/transferlearning#65]
您好，我在运行TCA.py时遇到了内存错误。源码中对H的操作如下。其中Xs输入是(样本数量, 特征维度)吧。那么转制整合之后n就是样本数量维度，然后创建H矩阵就是(样本数量, 样本数量)的维度。我处理的问题是有50000个训练样本，这样就超内存了。请问代码本就如此，还是我有那个地方理解错误？谢谢。
`X = np.hstack((Xs.T, Xt.T))`
`m, n = X.shape`
`H = np.eye(n) - 1 / n * np.ones((n, n))`

**Comment by jindongwang** [comment]
@JarvisXX 本来就是这样的，如果矩阵太大就不能算了，不是方法的bug

**Comment by JarvisXX** [comment]
OK. Thank you very much!
