### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by Pastuzo** [jindongwang/transferlearning#66]
王博，您好，

1. 

在code/traditional/jda/jda.py 34行对于rbf高斯核求解的第三部分您似乎少打了2，  源代码为D = (np.ones((n2, 1)) * n1sq).T + np.ones((n1, 1)) * n2sq - 2 * np.dot(X.T, X)，实际上应该是  D = (np.ones((n2, 1)) * n1sq).T + np.ones((n1, 1)) * n2sq - 2 * np.dot(X.T, _**X2**_)

2.

在code/traditional/jda/jda.py  98行 ，您直接将kernel返回的值源域X 带入目标函数求解，但是根据论文应该是[X.T. X2.T]是源域和目标域特征拼接在一起的矩阵

3.
在code/traditional/jda/jda.py  103行 ，您对Z做归一化处理，实际上可能并不需要这么做，因为在之前的步骤就已经对X进行了归一化，直接使用A.T * X 的结果作为Z就可以了

**Comment by jindongwang** [comment]
@Pastuzo 感谢如此细致的指正！
1. 你说的是对的，是我复制后忘记加X2了
2. kernel传入的参数没有X2，X本身就是Xs和Xt的集合，你可以对照代码看一下X的定义
3. 确实对Z不需要再归一化。不过习惯了就写上了，哈哈

**Comment by Pastuzo** [comment]
王博，您好：
感谢您的回复，关于第二条kernel传入参数的问题，确实如您所说，直接传入X即可。
另外，我是刚入门迁移学习的小白，想请教您关于迁移学习方面的问题，您方便留您的邮箱给我吗

**Comment by jindongwang** [comment]
@Pastuzo Github主页上有我的联系方式
