### ISSUE TITLE
when run DAN.py KeyError: 'bn1.num_batches_tracked'

### ISSUE THREAD

**Issue by caihengyu520** [jindongwang/transferlearning#67]
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/rainbow/.torch/models/resnet50-19c8e357.pth
100%|█████████████████████████████████████████████████| 102502400/102502400 [00:02<00:00, 38628901.09it/s]
Traceback (most recent call last):
  File "DAN.py", line 121, in <module>
    model = load_pretrain(model)
  File "DAN.py", line 54, in load_pretrain
    model_dict[k] = pretrained_dict[k[k.find(".") + 1:]]
KeyError: 'bn1.num_batches_tracked'

**Comment by jindongwang** [comment]
@easezyc

**Comment by easezyc** [comment]
版本问题，用pytorch0.3.1版本不会报错

**Comment by caihengyu520** [comment]
嗯嗯，之前已经看到了别人的恢复了，已经改过了，谢谢您的回复。




------------------ 原始邮件 ------------------
发件人: "Yongchun Zhu"<notifications@github.com>;
发送时间: 2019年4月21日(星期天) 下午3:12
收件人: "jindongwang/transferlearning"<transferlearning@noreply.github.com>;
抄送: "caihengyu"<chy520@mail.ustc.edu.cn>; "Author"<author@noreply.github.com>; 
主题: Re: [jindongwang/transferlearning] when run DAN.py KeyError:'bn1.num_batches_tracked' (#67)




版本问题，用pytorch0.3.1版本不会报错

**Comment by ashiqimran** [comment]
use pytorch=0.3.1, torchvision=0.2.0
