### ISSUE TITLE
关于GFK应用上的一些问题寻求帮助

### ISSUE THREAD

**Issue by leshansanren** [jindongwang/transferlearning#7]
王老师您好！
我是一名学生，我在使用您编写的GFK算法matlab代码程序的时候出现了一些问题，我做了一些努力但问题能没有解决，希望能得到您的帮助。

我的程序是在matlab2016b上运行的，我的输入为X_src：400x16的矩阵，Y_src：400x1的列向量，X_tar：400x16的矩阵，Y_tar：400x1的列向量，dim：8；（源域样本和目标域样本的特征维数均为16（16个时域统计特征，未归一化），样本个数均为400）
程序在运行到：G = GFK_core([Ps,null(Ps')], Pt(:,1:dim))；这一步报错了。具体错误为：

警告: 此串联操作包含列数不正确的空数组。
在未来的版本中，包含空数组的串联要求所有数组的列数相同。

In MyGFK>GFK_core (line 54)
In MyGFK (line 13)
In main (line 11)
错误使用 *
内部矩阵维度必须一致。
出错 MyGFK>GFK_core (line 53)
G = Q * [V1, zeros(dim,N-dim); zeros(N-dim,dim), V2] ...

出错 MyGFK (line 13)
G = GFK_core([Ps,null(Ps')], Pt(:,1:dim));

出错 main (line 11)
[acc,G] = MyGFK(X_src,Y_src,X_tar,Y_tar,10);

我对GFK_core进行了检查，发现在
G = Q * [V1, zeros(dim,N-dim); zeros(N-dim,dim), V2] ...
* [B1,B2,zeros(dim,N-2dim);B3,B4,zeros(dim,N-2dim);zeros(N-2dim,N)]...
* [V1, zeros(dim,N-dim); zeros(N-dim,dim), V2]' * Q';
这一步中，根据前面的程序得到的矩阵维数确实不一致：
Q为16x16，
[V1, zeros(dim,N-dim); zeros(N-dim,dim), V2]为16x16，
[B1,B2,zeros(dim,N-2dim);B3,B4,zeros(dim,N-2dim);zeros(N-2dim,N)].为20x20，
[V1, zeros(dim,N-dim); zeros(N-dim,dim), V2]' * Q'为16x16

此后，我对Q的值进行了检查，发现在Q=[Ps,null(Ps')]中，Ps为16x16矩阵，而null(Ps')的计算结果为空（16x0的矩阵）！而null函数在matlab中的功能是求解AX=0的解，null(Ps')的计算结果为空（16x0的矩阵）是否说明其无解？
此外，在zeros(dim,N-2dim)中，由于我设置的dim=8，因此,N-2dim<0，zeros(dim,N-2dim)为空矩阵。
由此，在程序
G = Q * [V1, zeros(dim,N-dim); zeros(N-dim,dim), V2] ...
* [B1,B2,zeros(dim,N-2dim);B3,B4,zeros(dim,N-2dim);zeros(N-2dim,N)]...
* [V1, zeros(dim,N-dim); zeros(N-dim,dim), V2]' * Q';
中出现的矩阵维数不匹配的问题是否由Q=[Ps,null(Ps')]以及zeros(dim,N-2*dim)为空？
期待您的帮助，谢谢！

**Comment by jindongwang** [comment]
- 你的matlab版本是多少？
- 你现在的情况是，16维要用GFK降到8维。我之前在用GFK的时候，也出现类似的问题，就是降维后的维度要小于原维度的一半，否则它就会出错。用的都是作者的代码，至今无解。
- 方便的话，可以把你的x_src,y_src,x_tar,y_tar发到我邮箱jindongwang@outlook.com，我晚上帮你看一下。

**Comment by leshansanren** [comment]
我的matlab版本是2016b，嗯，我稍后会把文件发给你

**Comment by leshansanren** [comment]
王老师，实在是不好意思！我们这边的数据不方便外传，请您谅解！
我的matlab是2016b版本
不过我之前根据您的回复：“降维后的维度要小于原维度的一半”，我将dim设置为dim<=8，程序已经可以正常运行了。
不过我的识别精度不高，这可能是我提取的特征不太好？
此外，我发现，源域样本数量和目标域样本数量发生变化时，识别精度也会发生改变？并且差异性较大（28.5%~58.5%）？
这是因为原算法的特性？

**Comment by jindongwang** [comment]
对，你改了数据那当然会发生变化。程序没有问题就好。

________________________________
祝好
王晋东

发件人： leshansanren<mailto:notifications@github.com>
发送时间： 2017-11-22 17:34:28
收件人：  jindongwang/transferlearning<mailto:transferlearning@noreply.github.com>
抄送：  Jindong Wang<mailto:jindongwang@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题： Re: [jindongwang/transferlearning] 关于GFK应用上的一些问题寻求帮助 (#7)

王老师，实在是不好意思！我们这边的数据不方便外传，请您谅解！
我的matlab是2016b版本
不过我之前根据您的回复：“降维后的维度要小于原维度的一半”，我将dim设置为dim<=8，程序已经可以正常运行了。
不过我的识别精度不高，这可能是我提取的特征不太好？
此外，我发现，源域样本数量和目标域样本数量发生变化时，识别精度也会发生改变？并且差异性较大（28.5%~58.5%）？
这是因为原算法的特性？

**Comment by leshansanren** [comment]
嗯嗯，谢谢王老师！祝好！

**Comment by Guoleming** [comment]
王老师你好，我现在有 source train data,  target train data, target test data , 在跑GFK的时候， target train data 不加载，程序会报错，提示维度不一致

**Comment by jindongwang** [comment]
@Guoleming 请具体说一下你跑的哪个程序，数据是什么，自己有没有试着去调，尽可能提供完整的信息。否则我无法帮到你

**Comment by Guoleming** [comment]
![image](https://user-images.githubusercontent.com/14157748/55220541-7b368300-5242-11e9-95f3-5403e871f48c.png)
王老师你好，这是我的程序截图， Xr 是训练数据包含源域+目标域， Yr,只有源域标签， Xt,Yt 是目标域测试数据和标签。
变量b 的shape 与 a, c 不一致

**Comment by jindongwang** [comment]
你的输入符合程序输入要求吗？

**Comment by Guoleming** [comment]
![image](https://user-images.githubusercontent.com/14157748/55221293-154afb00-5244-11e9-8050-5a7b90a5a92c.png)

谢谢反馈，代码的要求，X_src, 需要与 Y_src 第一维，维数需要一致。而我的， X_src, 比Y_src 维数多了,这是我代码跑不通的原因.
