### ISSUE TITLE
ValueError: Can Only tuple-index with a MultiIndex

### ISSUE THREAD

**Issue by SAwxl** [jindongwang/transferlearning#71]
王老师，您好。我在运行 JDA.py 代码的时候，遇到了错误
        ValueError: Can Only tuple-index with a MultiIndex
![Inked图片1_LI](https://user-images.githubusercontent.com/31943683/56792349-030cae80-683c-11e9-9b0a-b08ad63ed2b2.jpg)
         图中红线部分给出了报错的位置。请问如何修改呢

**Comment by jindongwang** [comment]
@SAwxl 你运行的demo有错吗？

**Comment by SAwxl** [comment]
@jindongwang   王老师，我已经可以运行了。
我把  **e = np.zeros((n, 1))**  分成了**es = np.zeros((ns, 1)); et = np.zeros((nt, 1))**   
把后面的对 **e** 赋值改成分别对 **es** 、 **et** 赋值，之后执行 **e = np.concatenate((ns, nt), axis=0)**  就行了。
上面报错是说 **e** 与  **tt** 行数不同

**Comment by jindongwang** [comment]
@SAwxl 是代码本身就得这样改，还是你的问题需要这样改？

**Comment by SAwxl** [comment]
@jindongwang  代码本身要这样改。
