### ISSUE TITLE
Please add following paper related to Domain Adaptation(Accepted IJCNN19, Oral)

### ISSUE THREAD

**Issue by vinodkkurmi** [jindongwang/transferlearning#73]
HI @jindongwang  
Please add the following paper related to Domain Adaptation. It has been accepted in IJCNN2019 Oral.
Paper: https://arxiv.org/abs/1904.01341
Project page: https://vinodkkurmi.github.io/DiscriminatorDomainAdaptation/
Code: https://github.com/vinodkkurmi/DiscriminatorDomainAdaptation

Thanks

**Comment by jindongwang** [comment]
@vinodkkurmi Please create a pull request to recommend articles as you wish.
