### ISSUE TITLE
关于GFK算法中的数据处理

### ISSUE THREAD

**Issue by stevenguo88** [jindongwang/transferlearning#79]
王老师，您好，在看您的GFK代码的时候，有一个问题一直没能理解，您代码中的
Ps = self.train_pca(source, mu_source, std_source, 0.99)
Pt = self.train_pca(target, mu_target, std_target, 0.99)
对数据进行了处理，对于train_pca函数中的subspace_dim这个参数的作用不是很理解,这与直接调用sklearn中的PCA函数的区别在哪里呢？

**Comment by jindongwang** [comment]
这个和sklearn的pca还是很不一样的。你可以看一下sklearn文档。我这个代码是参考了一个GFK的python包写的，就是GFK readme下面那个包。

**Comment by stevenguo88** [comment]
好的，我去看一下这个包，谢谢王老师。
