### ISSUE TITLE
其他领域的多任务学习

### ISSUE THREAD

**Issue by chao1224** [jindongwang/transferlearning#8]
楼主介绍的很多都是CV领域的迁移学习
Sebastian有一篇整体介绍的[博客](http://ruder.io/multi-task/)，包括CV和NLP
生物、基因、药物领域都有很多迁移学习，不过都没有survey形式的整体介绍

**Comment by jindongwang** [comment]
欢迎你一起加入，推荐更好的资源

Best regards,
Jindong

2017年12月6日 +0800 11:52 Shengchao Liu <notifications@github.com>，写道：

楼主介绍的很多都是CV领域的迁移学习
Sebastian有一篇整体介绍的博客<http://ruder.io/multi-task/>，包括CV和NLP
生物、基因、药物领域都有很多迁移学习，不过都没有survey形式的介绍
