### ISSUE TITLE
关于归一化的一些问题

### ISSUE THREAD

**Issue by TianyangLiang** [jindongwang/transferlearning#81]
王老师，您好！
TCA，JDA，MEDA算法代码里都有X = X*diag(sparse(1./sqrt(sum(X.^2)))); 这句，注释写的是normalization，但是不知道是属于哪种归一化？
另外，这些算法的输入项X_src，X_tar是否是已经归一化过的数据呢？

**Comment by jindongwang** [comment]
这行可删除的，数据本身已经是归一化过的了

**Comment by TianyangLiang** [comment]
我的输入数据使用的是min-max归一化，如果不删除X = X*diag(sparse(1./sqrt(sum(X.^2)))); ，也就是说两个归一化都使用了，效果反而更好，这个做法不知道对不对？
另外，MEDA算是一个不同于1NN和SVM的新的分类器吗？能否像TCA，JDA那样，生成迁移后的数据放入1NN或SVM进行分类预测？

**Comment by jindongwang** [comment]
归一化这个我觉得可能是对你数据比较敏感，所以效果会好点，就是个trick吧。另外，MEDA自己就是一个分类器，它是直接学习到label的，不需要像TCA和JDA一样学习一个特征变换，再用别的分类器进行分类。这也是它的好处之一。如果想用MEDA去学习特征，可考虑用深度网络和对抗网络进行。

**Comment by TianyangLiang** [comment]
我想问一下，仅使用1NN分类器，也就是不进行迁移学习，输入的数据是否需要进行归一化呢？
另外，不知道MEDA文章State-of-the-art Comparison Methods里“1NN, SVM, and PCA”中的PCA是不是指的主成分分析。如果是，是不是应该在PCA后使用一个分类器？

**Comment by jindongwang** [comment]
你的理解没有错，我也是这样做的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Tianyang Liang <notifications@github.com>
发送时间: Thursday, May 30, 2019 4:06:43 PM
收件人: jindongwang/transferlearning
抄送: Jindong Wang; Comment
主题: Re: [jindongwang/transferlearning] 关于归一化的一些问题 (#81)


我想问一下，仅使用1NN分类器，也就是不进行迁移学习，输入的数据是否需要进行归一化呢？
另外，不知道MEDA文章State-of-the-art Comparison Methods里“1NN, SVM, and PCA”中的PCA是不是指的主成分分析。如果是，是不是应该在PCA后使用一个分类器？

―
