### ISSUE TITLE
loss_mmd in DAN

### ISSUE THREAD

**Issue by ChengYeung1222** [jindongwang/transferlearning#82]
The mmd loss in training process always in the interval from 0.11 to 0.13 like this:

`Train Epoch: 1 [320/2817 (11%)]	Loss: 3.084191	soft_Loss: 3.081104	mmd_Loss: 0.123539
Train Epoch: 1 [640/2817 (23%)]	Loss: 1.750981	soft_Loss: 1.747856	mmd_Loss: 0.125048
Train Epoch: 1 [960/2817 (34%)]	Loss: 1.149839	soft_Loss: 1.146510	mmd_Loss: 0.133170
Train Epoch: 1 [1280/2817 (45%)]	Loss: 1.146459	soft_Loss: 1.143212	mmd_Loss: 0.129908
Train Epoch: 1 [1600/2817 (57%)]	Loss: 1.035381	soft_Loss: 1.032508	mmd_Loss: 0.114955
Train Epoch: 1 [1920/2817 (68%)]	Loss: 0.811917	soft_Loss: 0.808676	mmd_Loss: 0.129674
Train Epoch: 1 [2240/2817 (80%)]	Loss: 0.855911	soft_Loss: 0.852732	mmd_Loss: 0.127182
Train Epoch: 1 [2560/2817 (91%)]	Loss: 0.940946	soft_Loss: 0.937858	mmd_Loss: 0.123550`
and in Train Epoch 200:
`Train Epoch: 200 [320/2817 (11%)]	Loss: 0.140697	soft_Loss: 0.015895	mmd_Loss: 0.124814
Train Epoch: 200 [640/2817 (23%)]	Loss: 0.134810	soft_Loss: 0.017002	mmd_Loss: 0.117819
Train Epoch: 200 [960/2817 (34%)]	Loss: 0.133160	soft_Loss: 0.018198	mmd_Loss: 0.114972
Train Epoch: 200 [1280/2817 (45%)]	Loss: 0.139317	soft_Loss: 0.020981	mmd_Loss: 0.118346
Train Epoch: 200 [1600/2817 (57%)]	Loss: 0.172128	soft_Loss: 0.036544	mmd_Loss: 0.135596
Train Epoch: 200 [1920/2817 (68%)]	Loss: 0.162846	soft_Loss: 0.030337	mmd_Loss: 0.132522
Train Epoch: 200 [2240/2817 (80%)]	Loss: 0.139701	soft_Loss: 0.018627	mmd_Loss: 0.121085
Train Epoch: 200 [2560/2817 (91%)]	Loss: 0.143591	soft_Loss: 0.022363	mmd_Loss: 0.121239`
The mmd_loss didn't change a lot from epoch 1 to epoch 200. Shouldn't it decrease along with the classifier loss? Or is it just a regularizer?

**Comment by jindongwang** [comment]
MMD is just a regularizer

**Comment by ChengYeung1222** [comment]
Got it. Thank u!

**Comment by talentCODE** [comment]
how to understand  MMD just a regularizer ？ Don't recognize it as a common loss but as a adaptor？
