### ISSUE TITLE
Cannot increase batch_size value in DAN

### ISSUE THREAD

**Issue by ChengYeung1222** [jindongwang/transferlearning#83]
The batch_size in this model is set to 32 as default. However, when the value was doubled to 64, it would raise an OOM error. Does anyone have an idea about fixing the problem? Thanks in advance.

**Comment by jindongwang** [comment]
@easezyc

**Comment by ChengYeung1222** [comment]
I changed the calculation about the gaussian kernel from
`total0 = total.unsqueeze(0).expand(int(total.size(0)), int(total.size(0)),
                                       int(total.size(1)))
    total1 = total.unsqueeze(1).expand(int(total.size(0)), int(total.size(0)), int(total.size(1)))
    L2_distance = ((total0 - total1) ** 2).sum(2)`
to
`L2_distance=torch.zeros(int(total.size(0)), int(total.size(0))).cuda()
    L2_distance = Variable(L2_distance)
    for i in range(total.size()[0]):
        L2_distance[i,:]=torch.sum((total[i,:]-total)**2,1)`
and it was solved.
