### ISSUE TITLE
关于JDA以及BDA代码中边缘分布对应MMD矩阵M的问题

### ISSUE THREAD

**Issue by SAwxl** [jindongwang/transferlearning#84]
![图片1](https://user-images.githubusercontent.com/31943683/58934828-2feaa480-879e-11e9-9300-34362a1baa64.png)
王老师，图中第一个红色方框内的等式是计算边缘分布部分的MMD，即M_0，M_0在训练过程中是不变的。而后面迭代过程中，第二个红色方框内的等式M是边缘分布和条件分布MMD之和，这个地方没有把M与M_0区分，导致在每次训练过程中，M_0的值都发生了变化。在BDA的代码中也有相同的错误。
改为已下即可，望采纳。
![图片2](https://user-images.githubusercontent.com/31943683/58935192-5a892d00-879f-11e9-8ccf-4770275936e9.png)

**Comment by jindongwang** [comment]
感谢指正！已修改！
