### ISSUE TITLE
JDA ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by s0rel** [jindongwang/transferlearning#85]
王博，您好，我把您写的JDA.py用到了我的数据集上，发现运行到`e[tuple(inds)] = -1 / len(Y_tar_pseudo[np.where(Y_tar_pseudo == c)])`的过程中会抛出ZeroDivisionError: division by zero，我尝试去解决这个问题，但没找到方法，刚看到您更新了JDA.py，用新的代码试了一下，现在一运行就马上抛出ZeroDivisionError，请问这个问题应该如何解决

**Comment by jindongwang** [comment]
@s0rel 你试着调试一下程序，看看为什么为报这个错？

**Comment by tjzjp** [comment]
我的也会报这个错，我看了下，是因为分母会出现零。也不知道如何解决

**Comment by tjzjp** [comment]
> 王博，您好，我把您写的JDA.py用到了我的数据集上，发现运行到e[tuple(inds)] = -1 / len(Y_tar_pseudo[np.where(Y_tar_pseudo == c)])的过程中会抛出ZeroDivisionError: division by zero，我尝试去解决这个问题，但没找到方法，刚看到您更新了JDA.py，用新的代码试了一下，现在一运行就马上抛出ZeroDivisionError，请问这个问题应该如何解决

你是否用的是自己的数据集？
那么可能是在第79行：for c in range(1, C + 1):
王博是从1到10这么的标签
如果你的标签从0开始，那么就要改成for c in range(0, C):

**Comment by jindongwang** [comment]
@tjzjp 这么说来这个代码最好还是改得更通用一些，把class弄成动态获取label的，这样比较稳妥

**Comment by s0rel** [comment]
@tjzjp @jindongwang 是用的自己的数据集，后面已经自己解决了，谢谢两位

**Comment by wenruirui** [comment]
能否请问一下，你是怎么解决这个问题的呀，我现在也是遇到了这个问题，求解

**Comment by Byomyyt** [comment]
> @tjzjp @jindongwang 是用的自己的数据集，后面已经自己解决了，谢谢两位
你好，想请问下最后是怎么解决division by zero的问题呢？感谢！

**Comment by Byomyyt** [comment]
> @tjzjp @jindongwang 是用的自己的数据集，后面已经自己解决了，谢谢两位

你好，想请问下最后是怎么解决division by zero的问题呢？感谢！

**Comment by GuokaiLiu** [comment]
有的数据集，预测伪标签的集合是C的子集，此时，应做如下修改：
# for c in range(0, C):
> for c in set(Y_tar_pseudo):

**Comment by ilagemm** [comment]
> @tjzjp @jindongwang 是用的自己的数据集，后面已经自己解决了，谢谢两位

能请问以下是怎么解决的呢，感谢！
