### ISSUE TITLE
KMM算法中参数B的设定

### ISSUE THREAD

**Issue by stevenguo88** [jindongwang/transferlearning#86]
王老师，您好，在看完您的KMM代码以及阅读Correcting Sample Selection Bias by Unlabeled Data
这篇论文之后，对于KMM类中参数B的值有一些疑问，这个值是根据什么设定的？

**Comment by jindongwang** [comment]
@stevenguo88 这个值可以自己设定，作为一个参数可以调整的

**Comment by stevenguo88** [comment]
好的，谢谢王老师
