### ISSUE TITLE
DAN

### ISSUE THREAD

**Issue by Dr-Zhou** [jindongwang/transferlearning#87]
![image](https://user-images.githubusercontent.com/26479520/60312878-9a52c700-998f-11e9-8fdb-8d3a21912211.png)what should I solve this problem

**Comment by Dr-Zhou** [comment]
![image](https://user-images.githubusercontent.com/26479520/60391717-d587fe00-9b27-11e9-9c8c-86bf56eb3940.png)
![image](https://user-images.githubusercontent.com/26479520/60391720-e2a4ed00-9b27-11e9-9c93-36410405a880.png)
这个错误该如何解决，总是找不到对应的键值

**Comment by jindongwang** [comment]
@Dr-Zhou I think it is due to the different version of pytorch you are using. Please check the requirement of this code and make sure you are using the same version.

**Comment by Dr-Zhou** [comment]
ok。thank you.

**Comment by Dr-Zhou** [comment]
My pytorch version is 1.0.1.You can try it.Thank you.

**Comment by jindongwang** [comment]
Please look up in the previously solved issues, I remember someone asked the same question as you.

**Comment by Dr-Zhou** [comment]
thank you。

**Comment by Dr-Zhou** [comment]
I don't find it.

**Comment by jindongwang** [comment]
@easezyc Please help @Dr-Zhou  to see what's wrong with his code

**Comment by Dr-Zhou** [comment]
> @easezyc Please help @Dr-Zhou to see what's wrong with his code

my problem can't be sloved  util now.

**Comment by jindongwang** [comment]
@Dr-Zhou Is your problem solved? If not, please @easezyc help him to see what wrong with his code.

**Comment by Dr-Zhou** [comment]
@easezyc  please help me to solve my problem.

**Comment by easezyc** [comment]
pytorch = 0.3 not 1.0

**Comment by Dr-Zhou** [comment]
> pytorch = 0.3 not 1.0

pytorch =0.4.Can it work?

**Comment by easezyc** [comment]
It can not work with pytorch >=0.4
