### ISSUE TITLE
Unsupervised domain adaptation for regression

### ISSUE THREAD

**Issue by off99555** [jindongwang/transferlearning#88]
Do you know of any paper and code that deals with regression problem instead of classification?
My problem involves predicting a scalar from an image.

**Comment by jindongwang** [comment]
You can replace the classification loss with regression loss easily in a lot of methods if that method is not specified to classification. The general idea is that transfer learning deals with invariant representation learning, it does not belong to classification only.

**Comment by off99555** [comment]
Yeah. I did that to a method called `DeepJDOT`. It's working but the reason I want to know the paper is that I want to see a benchmark on regression task so that I know which method performs best in such a setting. Because it's hard to conclude that it will perform the same way with classification.

**Comment by jindongwang** [comment]
There is currently no such benchmark available since the papers that focus on regression are so few.

**Comment by off99555** [comment]
OK. So we'll assume that there is no unsupervised domain adaptation for regression paper for now.
