### ISSUE TITLE
pretrain data problem

### ISSUE THREAD

**Issue by ygjwd12345** [jindongwang/transferlearning#89]
我在用office-home数据集,我想问 label里的0:64分别代表什么class?就是原文作者的顺序吗? @jindongwang

**Comment by ygjwd12345** [comment]
若果我想做 domain adaption. x 到y 可以用 XX 到YY 而不是 XX XY吗

**Comment by jindongwang** [comment]
0-64代表65个类别，类别的顺序可以看代码的dataloader，默认是按照音序排列生成的。

第二个问题看不明白。

**Comment by ygjwd12345** [comment]
> 0-64代表65个类别，类别的顺序可以看代码的dataloader，默认是按照音序排列生成的。
> 
> 第二个问题看不明白。

你提取的特征里以office-31为例,有a_a,a_w,a_d,也有w_w,d_d .假如我想训练a  to d, 我是应该用 d_d z做target Domain呢 还是用 a_d?

**Comment by ygjwd12345** [comment]
@jindongwang

**Comment by jindongwang** [comment]
Readme里写的很清楚，你想做a to d，需要用a_a作为source，a_d作为target。建议好好理解一下readme中xy格式的意思。

**Comment by ygjwd12345** [comment]
我可不可以用d_d呢? 或者说d_d会差一点? @jindongwang

**Comment by jindongwang** [comment]
不可以。因为d_d表示在d上训练模型，然后在d上提特征。在你的问题a to d中，d是target domain，它没有label，因此你又如何能用d_d这个feature呢？这岂不是将测试集的label也加入训练了吗？

**Comment by ygjwd12345** [comment]
有label 但我可以不用啊. 也就是说,只要我不用d_d中的label,d_d和a_d都可以做target Domain吧

**Comment by jindongwang** [comment]
你不用d这个domain的label，如何训练d_d模型？

**Comment by ygjwd12345** [comment]
明白了
