### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Dr-Zhou** [jindongwang/transferlearning#90]
![image](https://user-images.githubusercontent.com/26479520/61588157-47081900-abc9-11e9-8827-d9baa637d186.png)

**Comment by jindongwang** [comment]
Please indicate which code folder it belongs to

**Comment by jindongwang** [comment]
@Dr-Zhou Is your problem solved?

**Comment by jindongwang** [comment]
@Dr-Zhou Is your problem solved?
