### ISSUE TITLE
Please add a new related paper on Unsupervised Domain Adaptation via Disentangled Representations

### ISSUE THREAD

**Issue by Junlin639** [jindongwang/transferlearning#93]
Hi,

Could you please add our new work into this list? The paper is about Unsupervised Domain Adaptation via Disentangled Representations.

You could find the paper here: https://arxiv.org/abs/1907.13590

Thank you!

Best,
Junlin

**Comment by jindongwang** [comment]
Hello, Thanks for recommending. You are encouraged to add new papers by following the instructions in this issue: #75
