### ISSUE TITLE
ERROR when import the dataset MNIST. 

### ISSUE THREAD

**Issue by 459548764** [jindongwang/transferlearning#95]
The error means that the output size is [1,28,28] not [3,28,28]. What should I do to solve this?

**Comment by jindongwang** [comment]
Please indicate where the error occurs, then I can help you

**Comment by 459548764** [comment]
![微信图片_20190804103523](https://user-images.githubusercontent.com/12037196/62418747-9bb89300-b6a3-11e9-843a-ef3320a5d54a.png)

**Comment by 459548764** [comment]
As for my observation, that means the MNIST size is (1,28,28). How can I get the size to become (3,28,28)?

**Comment by jindongwang** [comment]
Hello, there are multiple code directory in this repo. When reporting issues, you should mention which code it belongs to, or I can't help you

**Comment by 459548764** [comment]
After several testing，DANN demo can be run on the server. But i observed that the err_s_domain and err_t_domain loss will soon approaches to 0(below 0.1) then at epoch 10 it will turn to be 0.1--0.2, is that a normal phenomenon? It is means that the domain adversarial will 'collapse' at the beginning of the training?

**Comment by jindongwang** [comment]
@459548764 Is your problem solved?
