### ISSUE TITLE
demo_BDA提示未定义函数或变量fts

### ISSUE THREAD

**Issue by Dr-Zhou** [jindongwang/transferlearning#96]
![image](https://user-images.githubusercontent.com/26479520/62470393-eeda3500-b7cc-11e9-947e-cadcb5900c88.png)
总是提示这个变量未定义。

**Comment by jindongwang** [comment]
你实际看一下你的数据里面有没有fts这个字段，可能经过很多版本，下载到的office-caltech数据集有一些变化，你根据实际的数据内容赋值即可。

**Comment by Dr-Zhou** [comment]
> 你实际看一下你的数据里面有没有fts这个字段，可能经过很多版本，下载到的office-caltech数据集有一些变化，你根据实际的数据内容赋值即可。

是的。数据集应该更换成有surf特征的.mat文件

**Comment by jindongwang** [comment]
好的
