### ISSUE TITLE
关于office31数据集上的finetune

### ISSUE THREAD

**Issue by NaivePawn** [jindongwang/transferlearning#98]
您好！
在benchmark.md中，您给出了在Office31上微调resnet50后的模型，请问这模型具体是怎么微调的？（微调过程中那些层是冻结的，分类器有哪些层、优化器及其参数），这些细节能否告知一下或是有没有源码供参考一下。
（最近用torchvision中的models加载预训练好的resnet50，然后固定前几层的参数，用office31中的A上训练，但在W上的测试得到准确率百分之二十都不到）
谢谢！

**Comment by jindongwang** [comment]
源码在code/feature_extractor下

**Comment by NaivePawn** [comment]
好的，谢谢
